import { z } from 'npm:zod@3.23.8';

export const recipeSchema = z.object({ title:z.string().min(3),description:z.string(),servings:z.number().int().positive().max(24),prepMinutes:z.number().int().nonnegative().max(480),cookMinutes:z.number().int().positive().max(720),difficulty:z.enum(['Easy','Medium','Ambitious']),estimatedCost:z.string().regex(/^\d+(\.\d{1,2})?$/),ingredients:z.array(z.object({ingredientId:z.string().min(1),name:z.string().min(1),quantity:z.string().regex(/^\d+(\.\d{1,4})?$/),unit:z.enum(['count','serving','tsp','tbsp','fl_oz','cup','oz','lb','g','kg','ml','l','package','bag','can','bottle','bunch']),optional:z.boolean().optional()})).min(1).max(40),steps:z.array(z.string().min(3)).min(1).max(30),equipment:z.array(z.string()).max(20),safetyNotes:z.array(z.string()).max(20),substitutions:z.array(z.string()).max(20),tags:z.array(z.string()).max(20),cuisine:z.string().min(1),protein:z.string().min(1),cleanup:z.number().int().min(1).max(5),leftoverQuality:z.number().int().min(1).max(5),leftoverDays:z.number().int().min(0).max(7),reheating:z.string(),flavorProfile:z.array(z.string()),leftoverGuidance:z.string(),imageSearchQuery:z.string().min(3).max(160),confidence:z.number().min(0).max(1),unresolvedIngredientMappings:z.array(z.string()) });
const prepQuantity=z.string().regex(/^\d+(\.\d{1,4})?$/);const prepUnit=z.enum(['count','serving','tsp','tbsp','fl_oz','cup','oz','lb','g','kg','ml','l','package','bag','can','bottle','bunch']);
export const weeklyPrepPlanSchema=z.object({weekStart:z.string().date(),summary:z.string().min(3).max(1000),totalMinutes:z.number().int().min(1).max(720),estimatedWeeknightMinutesSaved:z.number().int().min(0).max(2000),generatedAt:z.string().datetime(),tasks:z.array(z.object({id:z.string().min(1).max(120),order:z.number().int().min(1).max(100),title:z.string().min(3).max(200),action:z.string().min(3).max(1000),estimatedMinutes:z.number().int().min(1).max(240),weekdayMinutesSaved:z.number().int().min(0).max(480),storage:z.string().min(3).max(1000),foodSafety:z.string().max(1000).optional(),ingredients:z.array(z.object({ingredientId:z.string().min(1).max(200),name:z.string().min(1).max(160),totalQuantity:prepQuantity,unit:prepUnit,allocations:z.array(z.object({mealId:z.string().min(1).max(120),mealTitle:z.string().min(1).max(200),mealDate:z.string().date(),quantity:prepQuantity,unit:prepUnit})).min(1).max(20)})).min(1).max(20)})).min(1).max(100)});
export type GeneratedRecipe=z.infer<typeof recipeSchema>;

export interface AIProvider { generateRecipe(input:Record<string,unknown>):Promise<GeneratedRecipe>; adaptRecipe(input:Record<string,unknown>):Promise<GeneratedRecipe>; interpretFeedback(input:{notes:string;tags:string[]}):Promise<Record<string,unknown>>; explainRecommendation(input:Record<string,unknown>):Promise<string>; parseReceipt?(input:{imageBase64:string}):Promise<Record<string,unknown>> }

export class MockAIProvider implements AIProvider {
  async generateRecipe(input:Record<string,unknown>):Promise<GeneratedRecipe>{const protein=String(input.protein??'chicken breast');return {title:`One-pan lemon ${protein}`,description:'A practical, bright weeknight meal generated locally without an external model.',servings:Number(input.servings??4),prepMinutes:10,cookMinutes:25,difficulty:'Easy',estimatedCost:'11.50',ingredients:[{ingredientId:'unresolved-protein',name:protein,quantity:'1.25',unit:'lb'},{ingredientId:'unresolved-vegetable',name:'seasonal vegetables',quantity:'12',unit:'oz'},{ingredientId:'unresolved-lemon',name:'lemon',quantity:'1',unit:'count'}],steps:['Heat the oven to 425°F and arrange the seasoned ingredients on a sheet pan.','Roast until vegetables are tender and the protein reaches its safe internal temperature.','Rest briefly, finish with lemon, and adjust seasoning.'],equipment:['Sheet pan','Instant-read thermometer'],safetyNotes:['Verify the selected protein reaches its USDA-recommended safe temperature.'],substitutions:['Use any quick-cooking vegetable already available.'],tags:['weekday','one-pan','leftovers'],cuisine:'American',protein,cleanup:1,leftoverQuality:4,leftoverDays:3,reheating:'Reheat gently until steaming hot.',flavorProfile:['lemon','savory'],leftoverGuidance:'Cool promptly and refrigerate up to three days.',imageSearchQuery:`${protein} lemon sheet pan dinner`,confidence:.78,unresolvedIngredientMappings:['unresolved-protein','unresolved-vegetable','unresolved-lemon']};}
  adaptRecipe(input:Record<string,unknown>){return this.generateRecipe(input)}
  async interpretFeedback(input:{notes:string;tags:string[]}){const text=input.notes.toLowerCase();return {positiveSignals:text.includes('sauce')?[{type:'flavor_profile',value:'sauce'}]:[],negativeSignals:[...(text.includes('dry')?[{type:'preparation_result',value:'dry'}]:[]),...(text.includes('pan')?[{type:'cleanup_burden',value:'too many pans'}]:[])],recipeAdjustments:text.includes('pan')?['Prefer a one-pan adaptation']:[],requiresReview:true}}
  async explainRecommendation(){return 'This meal uses available ingredients, stays practical for a weekday, and makes useful leftovers.'}
}

export class OpenAICompatibleProvider implements AIProvider {
  constructor(private baseUrl:string,private apiKey:string,private model:string){}
  private async call(system:string,input:Record<string,unknown>):Promise<any>{const controller=new AbortController();const timeout=setTimeout(()=>controller.abort(),25_000);try{const response=await fetch(`${this.baseUrl.replace(/\/$/,'')}/chat/completions`,{method:'POST',headers:{authorization:`Bearer ${this.apiKey}`,'content-type':'application/json'},body:JSON.stringify({model:this.model,response_format:{type:'json_object'},temperature:.4,messages:[{role:'system',content:system},{role:'user',content:JSON.stringify(input)}]}),signal:controller.signal});if(!response.ok)throw new Error(`ai_http_${response.status}`);const body=await response.json();return JSON.parse(body.choices[0].message.content)}finally{clearTimeout(timeout)}}
  async generateRecipe(input:Record<string,unknown>){return recipeSchema.parse(await this.call('Return one safe coherent recipe as JSON matching the supplied recipe schema. Never include HTML.',input))}
  adaptRecipe(input:Record<string,unknown>){return this.generateRecipe(input)}
  async interpretFeedback(input:{notes:string;tags:string[]}){return await this.call('Extract proposed preference signals. Distinguish ingredient, method, execution, recipe, portion, and temporary circumstance. Return JSON for user review.',input)}
  async explainRecommendation(input:Record<string,unknown>){const result=await this.call('Rewrite only the supplied deterministic reasons into one concise explanation. Add no new claims.',input);return String(result.explanation)}
}

export function getAIProvider():AIProvider {const kind=Deno.env.get('AI_PROVIDER')??'mock';if(kind==='mock')return new MockAIProvider();const key=Deno.env.get('AI_API_KEY');if(!key)throw new Error('AI provider is enabled but AI_API_KEY is missing');return new OpenAICompatibleProvider(Deno.env.get('AI_API_BASE_URL')??'https://api.openai.com/v1',key,Deno.env.get('AI_RECIPE_MODEL')??'gpt-4.1-mini')}
