import { z } from 'npm:zod@3.23.8';

const recipeSchema = z.object({ title:z.string(),description:z.string(),servings:z.number(),prepMinutes:z.number(),cookMinutes:z.number(),difficulty:z.enum(['Easy','Medium','Ambitious']),estimatedCost:z.string(),ingredients:z.array(z.object({ingredientId:z.string(),name:z.string(),quantity:z.string(),unit:z.string(),optional:z.boolean().optional()})),steps:z.array(z.string()),equipment:z.array(z.string()),safetyNotes:z.array(z.string()),substitutions:z.array(z.string()),tags:z.array(z.string()),cuisine:z.string(),flavorProfile:z.array(z.string()),leftoverGuidance:z.string(),confidence:z.number(),unresolvedIngredientMappings:z.array(z.string()) });
export type GeneratedRecipe=z.infer<typeof recipeSchema>;

export interface AIProvider { generateRecipe(input:Record<string,unknown>):Promise<GeneratedRecipe>; adaptRecipe(input:Record<string,unknown>):Promise<GeneratedRecipe>; interpretFeedback(input:{notes:string;tags:string[]}):Promise<Record<string,unknown>>; explainRecommendation(input:Record<string,unknown>):Promise<string>; parseReceipt?(input:{imageBase64:string}):Promise<Record<string,unknown>> }

export class MockAIProvider implements AIProvider {
  async generateRecipe(input:Record<string,unknown>):Promise<GeneratedRecipe>{const protein=String(input.protein??'chicken breast');return {title:`One-pan lemon ${protein}`,description:'A practical, bright weeknight meal generated locally without an external model.',servings:Number(input.servings??4),prepMinutes:10,cookMinutes:25,difficulty:'Easy',estimatedCost:'11.50',ingredients:[{ingredientId:'unresolved-protein',name:protein,quantity:'1.25',unit:'lb'},{ingredientId:'unresolved-vegetable',name:'seasonal vegetables',quantity:'12',unit:'oz'},{ingredientId:'unresolved-lemon',name:'lemon',quantity:'1',unit:'count'}],steps:['Heat the oven to 425°F and arrange the seasoned ingredients on a sheet pan.','Roast until vegetables are tender and the protein reaches its safe internal temperature.','Rest briefly, finish with lemon, and adjust seasoning.'],equipment:['Sheet pan','Instant-read thermometer'],safetyNotes:['Verify the selected protein reaches its USDA-recommended safe temperature.'],substitutions:['Use any quick-cooking vegetable already available.'],tags:['weekday','one-pan','leftovers'],cuisine:'American',flavorProfile:['lemon','savory'],leftoverGuidance:'Cool promptly and refrigerate up to three days.',confidence:.78,unresolvedIngredientMappings:['unresolved-protein','unresolved-vegetable','unresolved-lemon']};}
  adaptRecipe(input:Record<string,unknown>){return this.generateRecipe(input)}
  async interpretFeedback(input:{notes:string;tags:string[]}){const text=input.notes.toLowerCase();return {positiveSignals:text.includes('sauce')?[{type:'flavor_profile',value:'sauce'}]:[],negativeSignals:[...(text.includes('dry')?[{type:'preparation_result',value:'dry'}]:[]),...(text.includes('pan')?[{type:'cleanup_burden',value:'too many pans'}]:[])],recipeAdjustments:text.includes('pan')?['Prefer a one-pan adaptation']:[],requiresReview:true}}
  async explainRecommendation(){return 'This meal uses available ingredients, stays practical for a weekday, and makes useful leftovers.'}
}

export class OpenAICompatibleProvider implements AIProvider {
  constructor(private baseUrl:string,private apiKey:string,private model:string){}
  private async call(system:string,input:Record<string,unknown>):Promise<any>{const controller=new AbortController();const timeout=setTimeout(()=>controller.abort(),25_000);try{const response=await fetch(`${this.baseUrl.replace(/\/$/,'')}/chat/completions`,{method:'POST',headers:{authorization:`Bearer ${this.apiKey}`,'content-type':'application/json'},body:JSON.stringify({model:this.model,response_format:{type:'json_object'},temperature:.4,messages:[{role:'system',content:system},{role:'user',content:JSON.stringify(input)}]}),signal:controller.signal});if(!response.ok)throw new Error(`ai_http_${response.status}`);const body=await response.json();return JSON.parse(body.choices[0].message.content)}finally{clearTimeout(timeout)}}
  async generateRecipe(input:Record<string,unknown>){return recipeSchema.parse(await this.call('Return one safe coherent recipe as JSON matching the supplied recipe schema. Never include HTML.',input))}
  adaptRecipe(input:Record<string,unknown>){return this.generateRecipe(input)}
  async interpretFeedback(input:{notes:string;tags:string[]}){return await this.call('Extract proposed preference signals. Distinguish ingredient, method, execution, recipe, portion, and temporary circumstance. Return JSON for user review.',input)}
  async explainRecommendation(input:Record<string,unknown>){const result=await this.call('Rewrite only the supplied deterministic reasons into one concise explanation. Add no new claims.',input);return String(result.explanation)}
}

export function getAIProvider():AIProvider {const kind=Deno.env.get('AI_PROVIDER')??'mock';if(kind==='mock')return new MockAIProvider();const key=Deno.env.get('AI_API_KEY');if(!key)throw new Error('AI provider is enabled but AI_API_KEY is missing');return new OpenAICompatibleProvider(Deno.env.get('AI_API_BASE_URL')??'https://api.openai.com/v1',key,Deno.env.get('AI_RECIPE_MODEL')??'gpt-4.1-mini')}
