import type { InventoryItem, Recipe } from '@mise/domain';

const ing = (ingredientId: string, name: string, quantity: string, unit: any, optional = false) => ({ ingredientId, name, quantity, unit, optional });
const make = (id: string, title: string, description: string, cuisine: string, protein: string, servings: number, prepMinutes: number, cookMinutes: number, estimatedCost: string, cleanup: 1|2|3|4|5, leftoverQuality: 1|2|3|4|5, ingredients: ReturnType<typeof ing>[], steps: string[], tags: string[], difficulty: Recipe['difficulty'] = 'Easy', safetyNote?: string): Recipe => ({ id, version: 1, title, description, cuisine, protein, servings, prepMinutes, cookMinutes, difficulty, estimatedCost, cleanup, leftoverQuality, leftoverDays: leftoverQuality >= 4 ? 3 : 2, ingredients, steps, tags, reheating: leftoverQuality >= 4 ? 'Reheat gently with a splash of water.' : 'Best served fresh.', equipment: cleanup <= 2 ? ['Large skillet', 'Cutting board'] : ['Sheet pan', 'Saucepan', 'Cutting board'], ...(safetyNote ? { safetyNote } : {}) });

export const recipes: Recipe[] = [
  make('lemon-chicken-pasta','Lemon garlic chicken pasta','Silky lemon sauce, tender chicken, and spinach in a weeknight pasta.','Italian-inspired','Chicken',4,15,25,'13.20',3,4,[ing('chicken','Chicken breast','1.25','lb'),ing('pasta','Pasta','12','oz'),ing('spinach','Spinach','4','oz'),ing('lemon','Lemon','1','count'),ing('garlic','Garlic','4','count'),ing('parmesan','Parmesan','2','oz')],['Boil the pasta until just al dente; reserve one cup of cooking water.','Season and sear thin chicken cutlets to 165°F, then rest and slice.','Sauté garlic, fold in spinach, lemon, pasta, and enough cooking water to gloss the sauce.','Add chicken and parmesan; taste before seasoning.'],['weekday','leftovers','favorite'],'Easy','Cook chicken to 165°F.'),
  make('chicken-rice-bowls','Ginger chicken rice bowls','Savory glazed chicken with crisp vegetables and rice.','Asian-inspired','Chicken',4,15,20,'11.80',2,5,[ing('chicken','Chicken breast','1.25','lb'),ing('rice','Rice','1.5','cup'),ing('broccoli','Broccoli','12','oz'),ing('carrot','Carrots','2','count'),ing('soy','Soy sauce','3','tbsp'),ing('ginger','Ginger','1','tbsp')],['Cook rice.','Sear bite-size chicken until cooked through.','Steam broccoli and carrots until crisp-tender.','Simmer soy, ginger, and a little water into a glaze; assemble bowls.'],['one-pan','meal-prep','leftovers'],'Easy','Cook chicken to 165°F.'),
  make('salmon-sheet-pan','Maple mustard salmon','A handsome sheet-pan salmon dinner with crisp potatoes and green beans.','American','Salmon',2,15,30,'17.40',2,3,[ing('salmon','Salmon fillet','12','oz'),ing('potato','Baby potatoes','1','lb'),ing('green-beans','Green beans','8','oz'),ing('mustard','Dijon mustard','1','tbsp'),ing('maple','Maple syrup','2','tsp')],['Roast halved potatoes at 425°F for 18 minutes.','Whisk mustard and maple; brush over salmon.','Add salmon and green beans to the pan and roast until salmon flakes and reaches 145°F.'],['weekend','sheet-pan','fish'],'Medium','Cook fish to 145°F.'),
  make('beef-stir-fry','Beef & vegetable stir-fry','Fast ground beef, colorful vegetables, and a deeply savory sauce.','Chinese-inspired','Ground beef',4,15,15,'12.60',2,4,[ing('ground-beef','Ground beef','1','lb'),ing('bell-pepper','Bell pepper','2','count'),ing('broccoli','Broccoli','10','oz'),ing('soy','Soy sauce','3','tbsp'),ing('rice','Rice','1.5','cup')],['Cook rice.','Brown beef, breaking it into craggy pieces; drain excess fat.','Stir-fry vegetables until crisp-tender.','Add soy sauce and return beef; toss and serve.'],['quick','leftovers','budget'],'Easy','Cook ground beef to 160°F.'),
  make('chickpea-pasta','Chickpea tomato pasta','Jammy tomatoes and chickpeas make a filling meatless pasta.','Mediterranean','Chickpeas',4,10,25,'7.30',2,5,[ing('chickpeas','Chickpeas','2','can'),ing('tomatoes','Crushed tomatoes','1','can'),ing('pasta','Pasta','12','oz'),ing('garlic','Garlic','3','count'),ing('parmesan','Parmesan','1','oz',true)],['Boil pasta until al dente.','Bloom garlic in olive oil, then add tomatoes and chickpeas.','Simmer 15 minutes, fold in pasta, and finish with parmesan if desired.'],['meatless','budget','pantry'],'Easy'),
  make('tilapia-rice','Crispy tilapia with herbed rice','Lightly crusted fish with lemony rice and peas.','American','White fish',2,15,20,'10.90',2,2,[ing('tilapia','Tilapia fillets','12','oz'),ing('rice','Rice','1','cup'),ing('peas','Frozen peas','1','cup'),ing('lemon','Lemon','1','count'),ing('flour','Flour','3','tbsp')],['Cook rice and fold in peas.','Pat fish dry, season, and dust lightly with flour.','Pan-sear fish until opaque and 145°F; finish with lemon.'],['quick','fish','weekday'],'Easy','Cook fish to 145°F.'),
  make('frittata','Spinach, pepper & feta frittata','A flexible egg dinner that turns refrigerator odds and ends into something special.','Mediterranean','Eggs',4,10,25,'7.80',1,4,[ing('eggs','Eggs','8','count'),ing('spinach','Spinach','3','oz'),ing('bell-pepper','Bell pepper','1','count'),ing('feta','Feta','3','oz')],['Whisk eggs with salt and pepper.','Soften pepper and spinach in an oven-safe skillet.','Add eggs and feta; bake at 375°F until barely set.'],['meatless','one-pan','breakfast-for-dinner'],'Easy','Cook eggs until the center is set.'),
  make('tofu-curry','Coconut tofu curry','Golden tofu and vegetables in a warm coconut curry.','Thai-inspired','Tofu',4,15,25,'10.40',2,5,[ing('tofu','Extra-firm tofu','14','oz'),ing('coconut-milk','Coconut milk','1','can'),ing('broccoli','Broccoli','10','oz'),ing('curry-paste','Curry paste','2','tbsp'),ing('rice','Rice','1.5','cup')],['Cook rice.','Pat tofu dry and brown on all sides.','Fry curry paste briefly, add coconut milk and broccoli, then simmer.','Return tofu and season to taste.'],['meatless','leftovers','explore'],'Medium'),
  make('lentil-soup','Smoky red lentil soup','A low-cost, cozy soup with tomatoes and warm spices.','Middle Eastern-inspired','Lentils',5,10,35,'6.90',1,5,[ing('lentils','Red lentils','1.5','cup'),ing('tomatoes','Crushed tomatoes','1','can'),ing('carrot','Carrots','3','count'),ing('onion','Onion','1','count'),ing('lemon','Lemon','1','count')],['Soften onion and carrots.','Toast cumin and smoked paprika, then add lentils, tomatoes, and water.','Simmer until creamy; finish with lemon.'],['meatless','budget','freezer'],'Easy'),
  make('steak-dinner','Peppercorn steak with smashed potatoes','A bistro-style end-of-week dinner with a glossy pan sauce.','French-inspired','Beef',2,20,35,'24.00',4,2,[ing('steak','Sirloin steak','12','oz'),ing('potato','Baby potatoes','1','lb'),ing('green-beans','Green beans','8','oz'),ing('cream','Cream','0.25','cup')],['Boil potatoes, smash, and roast until crisp.','Sear seasoned steak to desired doneness and rest.','Cook green beans and make a quick peppercorn cream sauce in the steak pan.'],['ambitious','weekend','date-night'],'Ambitious','Use an instant-read thermometer and rest steak before slicing.'),
  make('shrimp-tacos','Easy shrimp tacos','Quick-seared shrimp with crunchy slaw and lime crema.','Mexican-inspired','Shrimp',4,15,12,'14.60',2,2,[ing('shrimp','Peeled shrimp','1','lb'),ing('tortilla','Corn tortillas','12','count'),ing('cabbage','Cabbage','8','oz'),ing('lime','Lime','2','count'),ing('yogurt','Greek yogurt','0.5','cup')],['Mix cabbage with lime and salt.','Sear peeled shrimp with chili powder until opaque.','Warm tortillas and assemble with lime yogurt.'],['quick','seafood','low-prep'],'Easy','Cook shrimp until opaque and 145°F.'),
  make('tuna-bowls','Sesame tuna crunch bowls','Seared tuna, cucumber, and rice with a sesame-soy drizzle.','Japanese-inspired','Tuna',2,20,15,'19.20',2,1,[ing('tuna','Yellowfin tuna','10','oz'),ing('rice','Rice','1','cup'),ing('cucumber','Cucumber','1','count'),ing('soy','Soy sauce','2','tbsp')],['Cook rice.','Mix soy with sesame oil.','Sear tuna briefly on each side, slice, and assemble bowls with cucumber.'],['weekend','fish','fresh'],'Medium','Use sushi-grade tuna if serving below 145°F.'),
  make('chicken-tacos','One-pan chicken fajita tacos','Smoky chicken and peppers with almost no cleanup.','Mexican-inspired','Chicken',4,15,20,'12.10',1,4,[ing('chicken','Chicken breast','1.25','lb'),ing('bell-pepper','Bell pepper','3','count'),ing('onion','Onion','1','count'),ing('tortilla','Flour tortillas','10','count'),ing('lime','Lime','1','count')],['Slice chicken and vegetables.','Sear chicken, then add peppers, onion, and spices.','Cook to 165°F; finish with lime and serve in warm tortillas.'],['one-pan','quick','leftovers'],'Easy','Cook chicken to 165°F.'),
  make('salmon-pasta','Creamy salmon & pea pasta','A practical pasta that stretches salmon across four servings.','Italian-inspired','Salmon',4,10,25,'15.50',2,3,[ing('salmon','Salmon fillet','10','oz'),ing('pasta','Pasta','12','oz'),ing('peas','Frozen peas','1','cup'),ing('cream','Cream','0.5','cup'),ing('lemon','Lemon','1','count')],['Boil pasta and peas.','Pan-cook salmon to 145°F and flake.','Simmer cream with lemon zest; fold in pasta, peas, and salmon.'],['weekday','fish','pasta'],'Medium','Cook fish to 145°F.'),
  make('beef-ragu','Weeknight beef ragu','A fast, rich tomato sauce designed for tomorrow’s lunch.','Italian','Ground beef',5,15,35,'12.90',2,5,[ing('ground-beef','Ground beef','1','lb'),ing('tomatoes','Crushed tomatoes','1','can'),ing('pasta','Pasta','16','oz'),ing('onion','Onion','1','count'),ing('carrot','Carrots','1','count')],['Brown beef well.','Add minced onion and carrot; cook until soft.','Add tomatoes and simmer while pasta cooks; combine.'],['leftovers','batch','family-style'],'Easy','Cook ground beef to 160°F.'),
  make('egg-fried-rice','Vegetable egg fried rice','A speedy use for cold rice and stray vegetables.','Chinese-inspired','Eggs',3,10,12,'5.80',1,3,[ing('eggs','Eggs','4','count'),ing('rice','Cooked rice','3','cup'),ing('peas','Frozen peas','1','cup'),ing('carrot','Carrots','1','count'),ing('soy','Soy sauce','2','tbsp')],['Scramble eggs and set aside.','Stir-fry carrot and peas.','Add cold rice and soy; fry until hot, then fold in eggs.'],['budget','quick','meatless'],'Easy','Reheat rice until steaming hot.'),
  make('chicken-soup','Lemony chicken orzo soup','Bright, restorative soup with chicken, spinach, and tender pasta.','Mediterranean','Chicken',5,15,35,'11.40',1,5,[ing('chicken','Chicken breast','1','lb'),ing('pasta','Orzo','8','oz'),ing('spinach','Spinach','4','oz'),ing('carrot','Carrots','2','count'),ing('lemon','Lemon','1','count')],['Poach chicken in seasoned broth and shred.','Simmer carrots and orzo until tender.','Return chicken, wilt spinach, and finish with lemon.'],['freezer','leftovers','one-pot'],'Easy','Cook chicken to 165°F.'),
  make('bean-quesadillas','Black bean & corn quesadillas','Crisp, cheesy, and pantry-friendly with a fresh lime bite.','Mexican-inspired','Beans',4,10,15,'7.20',1,3,[ing('black-beans','Black beans','1','can'),ing('corn','Corn','1','cup'),ing('tortilla','Flour tortillas','8','count'),ing('cheddar','Cheddar','6','oz'),ing('lime','Lime','1','count')],['Mash half the beans and combine with corn and lime.','Fill tortillas with beans and cheese.','Toast in a dry skillet until crisp and molten.'],['meatless','budget','quick'],'Easy'),
  make('garlic-tilapia','Garlic butter tilapia & broccoli','A simple fish dinner with a lemony pan sauce.','American','White fish',2,10,18,'10.20',1,2,[ing('tilapia','Tilapia fillets','12','oz'),ing('broccoli','Broccoli','12','oz'),ing('garlic','Garlic','3','count'),ing('lemon','Lemon','1','count'),ing('rice','Rice','1','cup')],['Cook rice and steam broccoli.','Sear seasoned tilapia until 145°F.','Melt butter with garlic and lemon in the pan; spoon over fish.'],['quick','fish','one-pan'],'Easy','Cook fish to 145°F.'),
  make('chicken-pot-pie','Skillet chicken biscuit pie','Creamy chicken and vegetables under a golden biscuit lid.','American','Chicken',5,25,40,'15.30',4,5,[ing('chicken','Chicken breast','1.25','lb'),ing('peas','Frozen peas','1','cup'),ing('carrot','Carrots','2','count'),ing('flour','Flour','1.5','cup'),ing('cream','Cream','0.5','cup')],['Cook chicken and vegetables in an oven-safe skillet.','Make a light cream gravy in the skillet.','Mix quick biscuit dough, place on top, and bake until golden.'],['ambitious','comfort','leftovers'],'Ambitious','Cook chicken to 165°F and filling until bubbling.')
];

const now = new Date(); const iso = (days: number) => new Date(now.getTime() + days * 86400000).toISOString().slice(0,10);
export const initialInventory: InventoryItem[] = [
  { id:'inv-chicken',ingredientId:'chicken',name:'Chicken breast',quantity:'2.5',reserved:'0',unit:'lb',confidence:.82,expiresOn:iso(2),location:'Fridge',lastConfirmedAt:new Date(now.getTime()-4*86400000).toISOString() },
  { id:'inv-eggs',ingredientId:'eggs',name:'Eggs',quantity:'7',reserved:'0',unit:'count',confidence:.65,expiresOn:iso(9),location:'Fridge',lastConfirmedAt:new Date(now.getTime()-7*86400000).toISOString() },
  { id:'inv-spinach',ingredientId:'spinach',name:'Baby spinach',quantity:'5',reserved:'0',unit:'oz',confidence:.55,expiresOn:iso(1),location:'Fridge',lastConfirmedAt:new Date(now.getTime()-5*86400000).toISOString() },
  { id:'inv-broccoli',ingredientId:'broccoli',name:'Broccoli',quantity:'12',reserved:'0',unit:'oz',confidence:.9,expiresOn:iso(4),location:'Fridge',lastConfirmedAt:new Date(now.getTime()-2*86400000).toISOString() },
  { id:'inv-rice',ingredientId:'rice',name:'Rice',quantity:'8',reserved:'0',unit:'cup',confidence:.95,location:'Pantry',lastConfirmedAt:new Date(now.getTime()-3*86400000).toISOString() },
  { id:'inv-pasta',ingredientId:'pasta',name:'Pasta',quantity:'24',reserved:'0',unit:'oz',confidence:.9,location:'Pantry',lastConfirmedAt:new Date(now.getTime()-8*86400000).toISOString() },
  { id:'inv-chickpeas',ingredientId:'chickpeas',name:'Chickpeas',quantity:'2',reserved:'0',unit:'can',confidence:.95,location:'Pantry',lastConfirmedAt:new Date(now.getTime()-10*86400000).toISOString() },
  { id:'inv-lemon',ingredientId:'lemon',name:'Lemons',quantity:'2',reserved:'0',unit:'count',confidence:.75,expiresOn:iso(6),location:'Fridge',lastConfirmedAt:new Date(now.getTime()-6*86400000).toISOString() }
];
