import type { InventoryItem, Recipe } from '@mise/domain';

const ing = (ingredientId: string, name: string, quantity: string, unit: any, optional = false) => ({ ingredientId, name, quantity, unit, optional });
const nutrition=(protein:string,ingredients:ReturnType<typeof ing>[])=>{const key=protein.toLowerCase();const proteinGramsPerServing=key.includes('chicken')?43:key.includes('salmon')?38:key.includes('tuna')?39:key.includes('fish')?35:key.includes('shrimp')?34:key.includes('beef')?37:key.includes('steak')?39:key.includes('egg')?25:key.includes('tofu')?22:key.includes('bean')||key.includes('chickpea')||key.includes('lentil')?19:24;const starch=ingredients.some(item=>/(rice|pasta|potato|tortilla|bread|noodle|gnocchi|flour|oat)/i.test(item.name));return {caloriesPerServing:(starch?620:490)+(key.includes('cheese')?80:0),proteinGramsPerServing}};
const scaled=(quantity:string,factor:number)=>String(Number((Number(quantity)*factor).toFixed(4)));
const make = (id: string, title: string, description: string, cuisine: string, protein: string, servings: number, prepMinutes: number, cookMinutes: number, estimatedCost: string, cleanup: 1|2|3|4|5, leftoverQuality: 1|2|3|4|5, ingredients: ReturnType<typeof ing>[], steps: string[], tags: string[], difficulty: Recipe['difficulty'] = 'Easy', safetyNote?: string): Recipe => {const factor=2/servings;const twoServingIngredients=ingredients.map(item=>({...item,quantity:scaled(item.quantity,factor)}));return { id, version: 1, title, description, cuisine, protein, servings:2, prepMinutes, cookMinutes, difficulty, estimatedCost:(Number(estimatedCost)*factor).toFixed(2),...nutrition(protein,twoServingIngredients),cleanup, leftoverQuality, leftoverDays:1, ingredients:twoServingIngredients, steps, tags, reheating:'Refrigerate the second serving promptly and reheat it until steaming for lunch tomorrow.', equipment: cleanup <= 2 ? ['Large skillet', 'Cutting board'] : ['Sheet pan', 'Saucepan', 'Cutting board'], ...(safetyNote ? { safetyNote } : {}) }};

export const recipes: Recipe[] = [
  make('lemon-chicken-pasta','Lemon garlic chicken pasta','Silky lemon sauce, tender chicken, and spinach in a weeknight pasta.','Italian-inspired','Chicken',4,15,25,'13.20',3,4,[ing('chicken','Chicken breast','1.25','lb'),ing('pasta','Pasta','12','oz'),ing('spinach','Spinach','4','oz'),ing('lemon','Lemon','1','count'),ing('garlic','Garlic','4','count'),ing('parmesan','Parmesan','2','oz')],['Boil the pasta until just al dente; reserve one cup of cooking water.','Season and sear thin chicken cutlets to 165°F, then rest and slice.','Sauté garlic, fold in spinach, lemon, pasta, and enough cooking water to gloss the sauce.','Add chicken and parmesan; taste before seasoning.'],['weekday','leftovers','favorite'],'Easy','Cook chicken to 165°F.'),
  make('chicken-rice-bowls','Ginger chicken rice bowls','Savory glazed chicken with crisp vegetables and rice.','Asian-inspired','Chicken',4,15,20,'11.80',2,5,[ing('chicken','Chicken breast','1.25','lb'),ing('rice','Rice','1.5','cup'),ing('broccoli','Broccoli','12','oz'),ing('carrot','Carrots','2','count'),ing('soy','Soy sauce','3','tbsp'),ing('ginger','Ginger','1','tbsp')],['Cook rice.','Sear bite-size chicken until cooked through.','Steam broccoli and carrots until crisp-tender.','Simmer soy, ginger, and a little water into a glaze; assemble bowls.'],['one-pan','meal-prep','leftovers'],'Easy','Cook chicken to 165°F.'),
  make('salmon-sheet-pan','Hot honey lime salmon','A bright sheet-pan salmon dinner with crisp potatoes and green beans.','American','Salmon',2,15,30,'17.40',2,3,[ing('salmon','Boneless salmon fillet','12','oz'),ing('potato','Baby potatoes','1','lb'),ing('green-beans','Green beans','8','oz'),ing('hot-honey','Hot honey','2','tbsp'),ing('lime','Lime','1','count')],['Roast halved potatoes at 425°F for 18 minutes.','Brush the salmon with hot honey and lime.','Add boneless salmon and green beans to the pan and roast until the fish flakes and reaches 145°F.'],['weekend','sheet-pan','fish'],'Medium','Check the salmon carefully for pin bones and cook fish to 145°F.'),
  make('beef-stir-fry','Beef & vegetable stir-fry','Fast ground beef, colorful vegetables, and a deeply savory sauce.','Chinese-inspired','Ground beef',4,15,15,'12.60',2,4,[ing('ground-beef','Ground beef','1','lb'),ing('bell-pepper','Bell pepper','2','count'),ing('broccoli','Broccoli','10','oz'),ing('soy','Soy sauce','3','tbsp'),ing('rice','Rice','1.5','cup')],['Cook rice.','Brown beef, breaking it into craggy pieces; drain excess fat.','Stir-fry vegetables until crisp-tender.','Add soy sauce and return beef; toss and serve.'],['quick','leftovers','budget'],'Easy','Cook ground beef to 160°F.'),
  make('chickpea-pasta','Chickpea tomato pasta','Jammy tomatoes and chickpeas make a filling meatless pasta.','Mediterranean','Chickpeas',4,10,25,'7.30',2,5,[ing('chickpeas','Chickpeas','2','can'),ing('tomatoes','Crushed tomatoes','1','can'),ing('pasta','Pasta','12','oz'),ing('garlic','Garlic','3','count'),ing('parmesan','Parmesan','1','oz',true)],['Boil pasta until al dente.','Bloom garlic in olive oil, then add tomatoes and chickpeas.','Simmer 15 minutes, fold in pasta, and finish with parmesan if desired.'],['meatless','budget','pantry'],'Easy'),
  make('tilapia-rice','Crispy tilapia with herbed rice','Lightly crusted fish with lemony rice and peas.','American','White fish',2,15,20,'10.90',2,2,[ing('tilapia','Tilapia fillets','12','oz'),ing('rice','Rice','1','cup'),ing('peas','Frozen peas','1','cup'),ing('lemon','Lemon','1','count'),ing('flour','Flour','3','tbsp')],['Cook rice and fold in peas.','Pat fish dry, season, and dust lightly with flour.','Pan-sear fish until opaque and 145°F; finish with lemon.'],['quick','fish','weekday'],'Easy','Cook fish to 145°F.'),
  make('frittata','Spinach, pepper & feta frittata','A flexible egg dinner that turns refrigerator odds and ends into something special.','Mediterranean','Eggs',4,10,25,'7.80',1,4,[ing('eggs','Eggs','8','count'),ing('spinach','Spinach','3','oz'),ing('bell-pepper','Bell pepper','1','count'),ing('feta','Feta','3','oz')],['Whisk eggs with salt and pepper.','Soften pepper and spinach in an oven-safe skillet.','Add eggs and feta; bake at 375°F until barely set.'],['meatless','one-pan','breakfast-for-dinner'],'Easy','Cook eggs until the center is set.'),
  make('tofu-curry','Coconut tofu curry','Golden tofu and vegetables in a warm coconut curry.','Thai-inspired','Tofu',4,15,25,'10.40',2,5,[ing('tofu','Extra-firm tofu','14','oz'),ing('coconut-milk','Coconut milk','1','can'),ing('broccoli','Broccoli','10','oz'),ing('curry-paste','Curry paste','2','tbsp'),ing('rice','Rice','1.5','cup')],['Cook rice.','Pat tofu dry and brown on all sides.','Fry curry paste briefly, add coconut milk and broccoli, then simmer.','Return tofu and season to taste.'],['meatless','leftovers','explore'],'Medium'),
  make('lentil-soup','Smoky red lentil soup','A low-cost, cozy soup with tomatoes and warm spices.','Middle Eastern-inspired','Lentils',5,10,35,'6.90',1,5,[ing('lentils','Red lentils','1.5','cup'),ing('tomatoes','Crushed tomatoes','1','can'),ing('carrot','Carrots','3','count'),ing('onion','Onion','1','count'),ing('lemon','Lemon','1','count')],['Soften onion and carrots.','Toast cumin and smoked paprika, then add lentils, tomatoes, and water.','Simmer until creamy; finish with lemon.'],['meatless','budget','freezer'],'Easy'),
  make('steak-dinner','Peppercorn steak with smashed potatoes','A bistro-style end-of-week dinner with a glossy pan sauce.','French-inspired','Beef',2,20,35,'24.00',4,2,[ing('steak','Sirloin steak','12','oz'),ing('potato','Baby potatoes','1','lb'),ing('green-beans','Green beans','8','oz'),ing('cream','Cream','0.25','cup')],['Boil potatoes, smash, and roast until crisp.','Sear seasoned steak to desired doneness and rest.','Cook green beans and make a quick peppercorn cream sauce in the steak pan.'],['ambitious','weekend','date-night'],'Ambitious','Use an instant-read thermometer and rest steak before slicing.'),
  make('shrimp-tacos','Easy shrimp tacos','Quick-seared shrimp with crunchy slaw and lime crema.','Mexican-inspired','Shrimp',4,15,12,'14.60',2,2,[ing('shrimp','Peeled shrimp','1','lb'),ing('tortilla','Corn tortillas','12','count'),ing('cabbage','Cabbage','8','oz'),ing('lime','Lime','2','count'),ing('yogurt','Greek yogurt','0.5','cup')],['Mix cabbage with lime and salt.','Sear peeled shrimp with chili powder until opaque.','Warm tortillas and assemble with lime yogurt.'],['quick','seafood','low-prep'],'Easy','Cook shrimp until opaque and 145°F.'),
  make('tuna-bowls','Sesame tuna crunch bowls','Seared tuna, cucumber, and rice with a sesame-soy drizzle.','Japanese-inspired','Tuna',2,20,15,'19.20',2,1,[ing('tuna','Yellowfin tuna','10','oz'),ing('rice','Rice','1','cup'),ing('cucumber','Cucumber','1','count'),ing('soy','Soy sauce','2','tbsp')],['Cook rice.','Mix soy with sesame oil.','Sear tuna briefly on each side, slice, and assemble bowls with cucumber.'],['weekend','fish','fresh'],'Medium','Use sushi-grade tuna if serving below 145°F.'),
  make('chicken-tacos','One-pan chicken fajita tacos','Smoky chicken and peppers with almost no cleanup.','Mexican-inspired','Chicken',4,15,20,'12.10',1,4,[ing('chicken','Chicken breast','1.25','lb'),ing('bell-pepper','Bell pepper','3','count'),ing('onion','Onion','1','count'),ing('tortilla','Flour tortillas','10','count'),ing('lime','Lime','1','count')],['Slice chicken and vegetables.','Sear chicken, then add peppers, onion, and spices.','Cook to 165°F; finish with lime and serve in warm tortillas.'],['one-pan','quick','leftovers'],'Easy','Cook chicken to 165°F.'),
  make('salmon-pasta','Creamy salmon & pea pasta','A practical pasta that stretches salmon across four servings.','Italian-inspired','Salmon',4,10,25,'15.50',2,3,[ing('salmon','Salmon fillet','10','oz'),ing('pasta','Pasta','12','oz'),ing('peas','Frozen peas','1','cup'),ing('cream','Cream','0.5','cup'),ing('lemon','Lemon','1','count')],['Boil pasta and peas.','Pan-cook salmon to 145°F and flake.','Simmer cream with lemon zest; fold in pasta, peas, and salmon.'],['weekday','fish','pasta'],'Medium','Cook fish to 145°F.'),
  make('beef-ragu','Weeknight beef ragu','A fast, rich tomato sauce designed for tomorrow’s lunch.','Italian','Ground beef',5,15,35,'12.90',2,5,[ing('ground-beef','Ground beef','1','lb'),ing('tomatoes','Crushed tomatoes','1','can'),ing('pasta','Pasta','16','oz'),ing('onion','Onion','1','count'),ing('carrot','Carrots','1','count')],['Brown beef well.','Add minced onion and carrot; cook until soft.','Add tomatoes and simmer while pasta cooks; combine.'],['leftovers','batch','family-style'],'Easy','Cook ground beef to 160°F.'),
  make('egg-fried-rice','Vegetable egg fried rice','A speedy use for cold rice and stray vegetables.','Chinese-inspired','Eggs',3,10,12,'5.80',1,3,[ing('eggs','Eggs','4','count'),ing('rice','Cooked rice','3','cup'),ing('peas','Frozen peas','1','cup'),ing('carrot','Carrots','1','count'),ing('soy','Soy sauce','2','tbsp')],['Scramble eggs and set aside.','Stir-fry carrot and peas.','Add cold rice and soy; fry until hot, then fold in eggs.'],['budget','quick','meatless'],'Easy','Reheat rice until steaming hot.'),
  make('chicken-soup','Lemony chicken orzo soup','Bright, restorative soup with chicken, spinach, and tender pasta.','Mediterranean','Chicken',5,15,35,'11.40',1,5,[ing('chicken','Chicken breast','1','lb'),ing('pasta','Orzo','8','oz'),ing('spinach','Spinach','4','oz'),ing('carrot','Carrots','2','count'),ing('lemon','Lemon','1','count')],['Poach chicken in seasoned broth and shred.','Simmer carrots and orzo until tender.','Return chicken, wilt spinach, and finish with lemon.'],['freezer','leftovers','one-pot'],'Easy','Cook chicken to 165°F.'),
  make('bean-quesadillas','Black bean & corn quesadillas','Crisp, cheesy, and pantry-friendly with a fresh lime bite.','Mexican-inspired','Beans',4,10,15,'7.20',1,3,[ing('black-beans','Black beans','1','can'),ing('corn','Corn','1','cup'),ing('tortilla','Flour tortillas','8','count'),ing('cheddar','Cheddar','6','oz'),ing('lime','Lime','1','count')],['Mash half the beans and combine with corn and lime.','Fill tortillas with beans and cheese.','Toast in a dry skillet until crisp and molten.'],['meatless','budget','quick'],'Easy'),
  make('garlic-tilapia','Garlic butter tilapia & broccoli','A simple fish dinner with a lemony pan sauce.','American','White fish',2,10,18,'10.20',1,2,[ing('tilapia','Tilapia fillets','12','oz'),ing('broccoli','Broccoli','12','oz'),ing('garlic','Garlic','3','count'),ing('lemon','Lemon','1','count'),ing('rice','Rice','1','cup')],['Cook rice and steam broccoli.','Sear seasoned tilapia until 145°F.','Melt butter with garlic and lemon in the pan; spoon over fish.'],['quick','fish','one-pan'],'Easy','Cook fish to 145°F.'),
  make('chicken-pot-pie','Skillet chicken biscuit pie','Creamy chicken and vegetables under a golden biscuit lid.','American','Chicken',5,25,40,'15.30',4,5,[ing('chicken','Chicken breast','1.25','lb'),ing('peas','Frozen peas','1','cup'),ing('carrot','Carrots','2','count'),ing('flour','Flour','1.5','cup'),ing('cream','Cream','0.5','cup')],['Cook chicken and vegetables in an oven-safe skillet.','Make a light cream gravy in the skillet.','Mix quick biscuit dough, place on top, and bake until golden.'],['ambitious','comfort','leftovers'],'Ambitious','Cook chicken to 165°F and filling until bubbling.'),
  make('chicken-shawarma','Sheet-pan chicken shawarma bowls','Warm-spiced chicken, roasted vegetables, rice, and cool yogurt sauce.','Middle Eastern-inspired','Chicken',4,20,30,'13.80',2,5,[ing('chicken','Chicken thighs','1.5','lb'),ing('rice','Rice','1.5','cup'),ing('bell-pepper','Bell pepper','2','count'),ing('onion','Red onion','1','count'),ing('yogurt','Greek yogurt','0.5','cup')],['Coat chicken and sliced vegetables with cumin, paprika, garlic, and oil.','Roast at 425°F until the chicken reaches 165°F.','Serve over rice with seasoned yogurt.'],['sheet-pan','meal-prep','leftovers'],'Easy','Cook chicken to 165°F.'),
  make('pesto-chicken','Nut-free pesto chicken pasta','Juicy chicken breast, nut-free basil pesto, pasta, and jammy cherry tomatoes.','Italian-inspired','Chicken',4,10,20,'14.20',1,4,[ing('chicken','Chicken breast','1.25','lb'),ing('tomatoes-fresh','Cherry tomatoes','12','oz'),ing('nut-free-pesto','Nut-free basil pesto','0.33','cup'),ing('pasta','Pasta','12','oz')],['Boil pasta until al dente.','Sear thin chicken cutlets to 165°F and set aside.','Burst tomatoes in the skillet, add verified nut-free pesto and pasta, then return the chicken.'],['quick','one-pan','weekday','nut-free'],'Easy','Verify every pesto ingredient and label is peanut- and tree-nut-free. Cook chicken to 165°F.'),
  make('teriyaki-chicken','Teriyaki chicken broccoli bowls','Glossy homemade teriyaki chicken with broccoli and rice.','Japanese-inspired','Chicken',4,15,20,'11.90',2,5,[ing('chicken','Chicken breast','1.25','lb'),ing('rice','Rice','1.5','cup'),ing('broccoli','Broccoli','12','oz'),ing('soy','Soy sauce','0.25','cup'),ing('ginger','Ginger','1','tbsp')],['Cook rice and steam broccoli.','Brown bite-size chicken until cooked through.','Simmer soy, ginger, garlic, and a little brown sugar into a glaze; toss with chicken and serve.'],['meal-prep','family','leftovers'],'Easy','Cook chicken to 165°F.'),
  make('chicken-enchiladas','Salsa verde chicken enchiladas','Tender chicken and beans rolled under bright salsa verde and cheese.','Mexican-inspired','Chicken',6,25,30,'16.40',3,5,[ing('chicken','Cooked shredded chicken','3','cup'),ing('tortilla','Corn tortillas','12','count'),ing('black-beans','Black beans','1','can'),ing('salsa-verde','Salsa verde','2','cup'),ing('cheddar','Monterey Jack','8','oz')],['Mix chicken with beans and a little salsa.','Roll into tortillas and arrange seam-side down in a baking dish.','Top with remaining salsa and cheese; bake until bubbling.'],['batch','freezer','family'],'Medium','Heat the filling to 165°F.'),
  make('chicken-curry','Weeknight tomato chicken curry','Tender chicken in a warmly spiced tomato sauce finished with yogurt.','Indian-inspired','Chicken',4,15,30,'12.70',2,5,[ing('chicken','Chicken thighs','1.5','lb'),ing('tomatoes','Crushed tomatoes','1','can'),ing('onion','Onion','1','count'),ing('yogurt','Greek yogurt','0.5','cup'),ing('rice','Rice','1.5','cup')],['Cook rice.','Brown chicken, then soften onion with curry spices.','Add tomatoes and simmer until chicken reaches 165°F; finish with yogurt off heat.'],['one-pot','leftovers','comfort'],'Medium','Cook chicken to 165°F.'),
  make('honey-soy-salmon','Honey soy salmon rice bowls','Caramelized salmon with cucumber, rice, and a sweet-savory glaze.','Asian-inspired','Salmon',4,15,18,'18.60',2,3,[ing('salmon','Salmon fillet','1.25','lb'),ing('rice','Rice','1.5','cup'),ing('cucumber','Cucumber','1','count'),ing('soy','Soy sauce','3','tbsp'),ing('honey','Honey','2','tbsp')],['Cook rice and slice cucumber.','Brush salmon with honey-soy glaze and roast at 425°F.','Flake salmon into bowls when it reaches 145°F and spoon over remaining glaze.'],['quick','fish','bowls'],'Easy','Cook salmon to 145°F.'),
  make('salmon-cakes','Crispy salmon cakes with lemon slaw','Golden pantry-friendly salmon cakes with a crisp cabbage salad.','American','Salmon',4,20,15,'10.80',2,3,[ing('canned-salmon','Canned salmon','2','can'),ing('eggs','Eggs','1','count'),ing('breadcrumbs','Breadcrumbs','0.75','cup'),ing('cabbage','Cabbage','8','oz'),ing('lemon','Lemon','1','count')],['Mix drained salmon with egg, breadcrumbs, and seasoning; form patties.','Pan-sear until deeply golden and hot throughout.','Toss cabbage with lemon and serve alongside.'],['budget','pantry','fish'],'Easy','Heat salmon cakes to 165°F.'),
  make('beef-taco-skillet','One-pan beef taco skillet','Seasoned beef, beans, corn, and rice with a melty cheese finish.','Mexican-inspired','Ground beef',5,10,25,'12.30',1,5,[ing('ground-beef','Ground beef','1','lb'),ing('black-beans','Black beans','1','can'),ing('corn','Corn','1','cup'),ing('rice','Rice','1','cup'),ing('cheddar','Cheddar','5','oz')],['Brown beef to 160°F and drain excess fat.','Stir in spices, rice, beans, corn, and water; cover and simmer.','Top with cheese and rest until melted.'],['one-pan','budget','leftovers'],'Easy','Cook ground beef to 160°F.'),
  make('beef-meatballs','Baked beef meatballs and marinara','Tender oven-baked meatballs simmered briefly in tomato sauce.','Italian','Ground beef',5,20,30,'13.60',2,5,[ing('ground-beef','Ground beef','1.25','lb'),ing('breadcrumbs','Breadcrumbs','0.5','cup'),ing('eggs','Eggs','1','count'),ing('tomatoes','Crushed tomatoes','1','can'),ing('pasta','Pasta','16','oz')],['Mix beef, breadcrumbs, egg, and seasoning; shape into meatballs.','Bake at 425°F until the centers reach 160°F.','Simmer in tomato sauce and serve over pasta.'],['family','freezer','batch'],'Easy','Cook ground beef to 160°F.'),
  make('classic-chili','Weeknight beef and bean chili','A thick, smoky chili built for toppings and next-day lunches.','American','Ground beef',6,15,40,'12.40',1,5,[ing('ground-beef','Ground beef','1','lb'),ing('kidney-beans','Kidney beans','2','can'),ing('tomatoes','Crushed tomatoes','1','can'),ing('onion','Onion','1','count'),ing('bell-pepper','Bell pepper','1','count')],['Brown beef to 160°F.','Add onion, pepper, chili powder, and cumin; cook until softened.','Add beans and tomatoes, then simmer until thick.'],['one-pot','freezer','leftovers'],'Easy','Cook ground beef to 160°F.'),
  make('chimichurri-chicken','Chimichurri chicken with crispy potatoes','Seared chicken breast with bright herb sauce, crispy potatoes, and green beans.','Latin American','Chicken',2,15,25,'11.80',2,4,[ing('chicken','Chicken breast','0.75','lb'),ing('potato','Baby potatoes','0.75','lb'),ing('green-beans','Green beans','6','oz'),ing('chimichurri','Nut-free chimichurri','0.25','cup')],['Air-fry or roast the potatoes until crisp.','Sear chicken breast to 165°F and cook the green beans until tender.','Slice and plate the chicken beside the potatoes and beans; spoon chimichurri over the top.'],['complete-meal','air-fryer','tangy'],'Easy','Verify the chimichurri is nut-free and cook chicken to 165°F.'),
  make('chicken-adobo','Filipino chicken breast adobo','Tangy soy-vinegar chicken breast with garlic rice and green beans.','Filipino','Chicken',2,15,25,'9.80',2,5,[ing('chicken','Chicken breast','0.75','lb'),ing('rice','Rice','0.75','cup'),ing('green-beans','Green beans','6','oz'),ing('soy','Soy sauce','3','tbsp'),ing('vinegar','Cane or white vinegar','3','tbsp')],['Start the rice.','Simmer sliced chicken breast with soy, vinegar, plenty of garlic, and bay until it reaches 165°F.','Cook the green beans and plate them with the glossy adobo and rice.'],['filipino','tangy','leftovers'],'Easy','Cook chicken to 165°F.'),
  make('greek-chicken-plate','Lemon herb chicken rice plate','Garlicky chicken breast, herbed rice, roasted zucchini, and cool yogurt sauce.','Mediterranean','Chicken',2,15,25,'11.20',2,5,[ing('chicken','Chicken breast','0.75','lb'),ing('rice','Rice','0.75','cup'),ing('zucchini','Zucchini','1','count'),ing('yogurt','Greek yogurt','0.5','cup'),ing('lemon','Lemon','1','count')],['Cook the rice with parsley and lemon zest.','Roast zucchini and sear chicken breast to 165°F.','Arrange distinct portions on the plate and add garlic-lemon yogurt sauce.'],['plated','mediterranean','leftovers'],'Easy','Cook chicken to 165°F.'),
  make('buffalo-chicken-potato','Buffalo chicken loaded potatoes','Crisp baked potatoes topped with saucy chicken breast, broccoli, and yogurt ranch.','American','Chicken',2,15,30,'10.40',2,4,[ing('chicken','Chicken breast','0.75','lb'),ing('potato','Russet potatoes','2','count'),ing('broccoli','Broccoli','8','oz'),ing('hot-sauce','Buffalo hot sauce','3','tbsp'),ing('yogurt','Greek yogurt','0.5','cup')],['Microwave then air-fry the potatoes until crisp.','Cook diced chicken breast to 165°F, toss with buffalo sauce, and steam the broccoli.','Split the potatoes and top with broccoli, chicken, and herbed yogurt.'],['air-fryer','complete-meal','spicy'],'Easy','Cook chicken to 165°F.'),
  make('chicken-mushroom-risotto','Chicken and mushroom risotto','Sliced chicken breast and savory mushrooms over creamy parmesan rice.','Italian','Chicken',2,15,35,'12.60',3,4,[ing('chicken','Chicken breast','0.75','lb'),ing('arborio','Arborio rice','0.75','cup'),ing('mushrooms','Mushrooms','6','oz'),ing('broth','Chicken broth','2.5','cup'),ing('parmesan','Parmesan','1.5','oz')],['Sear chicken breast to 165°F, rest, and slice.','Brown mushrooms, toast rice, and add warm broth gradually until creamy.','Fold in parmesan and plate the sliced chicken over the mushroom risotto.'],['plated','comfort','italian'],'Medium','Cook chicken to 165°F.'),
  make('chicken-black-bean-bowl','Lime chicken black bean bowls','Cumin-lime chicken breast with black beans, rice, corn, and fresh-style salsa verde.','Latin American','Chicken',2,15,20,'9.60',2,5,[ing('chicken','Chicken breast','0.75','lb'),ing('black-beans','Black beans','0.5','can'),ing('rice','Rice','0.75','cup'),ing('corn','Corn','0.5','cup'),ing('salsa-verde','Fresh-style salsa verde','0.33','cup')],['Cook the rice and warm the beans and corn.','Sear cumin-seasoned chicken breast to 165°F and finish with lime.','Build bowls with separate sections and spoon over fresh-style salsa verde.'],['rice-bowl','latin','leftovers'],'Easy','Cook chicken to 165°F.'),
  make('chicken-korma','Coconut chicken korma','Chicken breast and cooked vegetables in a gently spiced coconut sauce with rice.','Indian-inspired','Chicken',2,20,25,'11.90',2,5,[ing('chicken','Chicken breast','0.75','lb'),ing('cauliflower','Cauliflower','0.5','count'),ing('carrot','Carrots','1','count'),ing('coconut-milk','Coconut milk','0.5','can'),ing('rice','Rice','0.75','cup')],['Cook the rice.','Brown chicken breast, then soften cauliflower and carrot with curry spices.','Add coconut milk and simmer until the chicken reaches 165°F; serve with rice.'],['curry','complete-meal','leftovers'],'Medium','Use only nut-free curry ingredients and cook chicken to 165°F.'),
  make('chicken-baked-ziti','Chicken spinach baked ziti','A two-serving pasta bake with chicken breast, spinach, tomato sauce, ricotta, and mozzarella.','Italian-American','Chicken',2,20,30,'11.40',3,5,[ing('chicken','Chicken breast','0.625','lb'),ing('pasta','Ziti','6','oz'),ing('tomatoes','Tomato sauce','1','cup'),ing('spinach','Spinach','3','oz'),ing('mozzarella','Mozzarella','3','oz')],['Cook the ziti just shy of al dente and sear diced chicken to 165°F.','Combine pasta, chicken, sauce, spinach, and cheese in a small baking dish.','Bake at 400°F until bubbling and browned.'],['pasta','two-serving','leftovers'],'Easy','Cook chicken to 165°F.'),
  make('shakshuka','Smoky tomato shakshuka','Eggs gently poached in a spiced tomato and pepper sauce.','North African-inspired','Eggs',4,10,25,'7.60',1,2,[ing('eggs','Eggs','6','count'),ing('tomatoes','Crushed tomatoes','1','can'),ing('bell-pepper','Bell pepper','1','count'),ing('onion','Onion','1','count')],['Soften onion and pepper with cumin and smoked paprika.','Add tomatoes and simmer until thick.','Make wells, add eggs, cover, and cook until whites are set.'],['meatless','one-pan','brunch'],'Easy','Cook eggs until the whites and centers are set.'),
  make('beef-stuffed-peppers','Beef and rice stuffed peppers','Bell peppers packed with lean ground beef, tomato rice, herbs, and mozzarella.','Italian-inspired','Ground beef',2,20,35,'10.80',2,5,[ing('bell-pepper','Bell pepper','2','count'),ing('ground-beef','Lean ground beef','0.5','lb'),ing('rice','Cooked rice','1','cup'),ing('tomatoes','Tomato sauce','0.75','cup'),ing('mozzarella','Mozzarella','2.5','oz')],['Roast halved peppers cut-side down for 12 minutes.','Brown lean beef to 160°F and mix with rice, tomato sauce, and herbs.','Fill peppers, top with mozzarella, and bake until tender.'],['plated','beef','leftovers'],'Easy','Cook ground beef to 160°F.'),
  make('chicken-pesto-gnocchi','Nut-free pesto chicken gnocchi','Chicken breast, crisp gnocchi, zucchini, and tomatoes in nut-free basil pesto.','Italian-inspired','Chicken',2,15,20,'11.90',1,4,[ing('chicken','Chicken breast','0.75','lb'),ing('gnocchi','Shelf-stable gnocchi','1','package'),ing('zucchini','Zucchini','1','count'),ing('tomatoes-fresh','Cherry tomatoes','5','oz'),ing('nut-free-pesto','Nut-free basil pesto','0.25','cup')],['Sear diced chicken breast to 165°F and set aside.','Brown gnocchi, then cook zucchini and tomatoes until tender.','Return chicken and fold in verified nut-free pesto.'],['quick','one-pan','nut-free'],'Easy','Verify every pesto ingredient and label is peanut- and tree-nut-free. Cook chicken to 165°F.'),
  make('hot-honey-chicken-sweet-potato','Hot honey chicken with sweet potatoes','Spicy-sweet chicken breast with roasted sweet potatoes and garlicky broccoli.','American','Chicken',2,15,30,'10.60',2,4,[ing('chicken','Chicken breast','0.75','lb'),ing('sweet-potato','Sweet potato','1','count'),ing('broccoli','Broccoli','8','oz'),ing('hot-honey','Hot honey','2','tbsp'),ing('lime','Lime','1','count')],['Roast sweet potato cubes until browned.','Add broccoli and chicken breast; roast until the chicken reaches 165°F.','Plate the components and drizzle the chicken with hot honey and lime.'],['sheet-pan','complete-meal','spicy'],'Easy','Cook chicken to 165°F.'),
  make('white-bean-skillet','Garlicky white bean tomato skillet','Creamy beans, tomatoes, and greens finished with lemon and herbs.','Mediterranean','Beans',4,10,20,'7.90',1,5,[ing('white-beans','White beans','2','can'),ing('tomatoes-fresh','Cherry tomatoes','12','oz'),ing('spinach','Spinach','5','oz'),ing('garlic','Garlic','4','count'),ing('lemon','Lemon','1','count')],['Sizzle garlic in olive oil and add tomatoes.','Fold in beans and simmer until creamy.','Wilt in spinach and finish with lemon.'],['one-pan','meatless','pantry'],'Easy'),
  make('shrimp-scampi','Lemony shrimp scampi pasta','Garlicky shrimp and pasta brightened with lemon and parsley.','Italian-American','Shrimp',4,15,15,'15.10',2,2,[ing('shrimp','Peeled shrimp','1','lb'),ing('pasta','Pasta','12','oz'),ing('garlic','Garlic','5','count'),ing('lemon','Lemon','1','count')],['Boil pasta and reserve cooking water.','Sauté shrimp until opaque and 145°F; remove from the pan.','Bloom garlic, add lemon and pasta water, then toss with pasta and shrimp.'],['quick','seafood','pasta'],'Easy','Cook shrimp to 145°F.'),
  make('cod-tacos','Crispy baked cod tacos','Spiced baked white fish with crunchy slaw and lime sauce.','Mexican-inspired','White fish',4,20,18,'13.30',2,2,[ing('cod','Cod fillets','1.25','lb'),ing('tortilla','Corn tortillas','12','count'),ing('cabbage','Cabbage','8','oz'),ing('lime','Lime','2','count'),ing('yogurt','Greek yogurt','0.5','cup')],['Coat fish with spices and a light breadcrumb crust.','Bake at 425°F until flaky and 145°F.','Flake into tortillas with lime slaw and yogurt sauce.'],['fish','tacos','weekday'],'Easy','Cook fish to 145°F.'),
  make('coconut-shrimp-curry','Coconut shrimp and spinach curry','Quick shrimp, spinach, and peppers in a fragrant coconut curry.','Thai-inspired','Shrimp',4,15,20,'14.40',2,3,[ing('shrimp','Peeled shrimp','1','lb'),ing('coconut-milk','Coconut milk','1','can'),ing('spinach','Spinach','5','oz'),ing('bell-pepper','Bell pepper','1','count'),ing('rice','Rice','1.5','cup')],['Cook rice.','Simmer pepper, curry paste, and coconut milk until slightly thickened.','Add shrimp and spinach; cook until shrimp are opaque and 145°F.'],['quick','seafood','curry'],'Medium','Cook shrimp to 145°F.'),
  make('breakfast-burritos','Freezer breakfast burritos','Eggs, potatoes, beans, and cheese wrapped for easy breakfasts or dinners.','Southwestern','Eggs',8,25,25,'11.20',2,5,[ing('eggs','Eggs','10','count'),ing('potato','Potatoes','1','lb'),ing('black-beans','Black beans','1','can'),ing('tortilla','Flour tortillas','8','count'),ing('cheddar','Cheddar','6','oz')],['Roast diced potatoes until crisp and scramble eggs until set.','Layer eggs, potatoes, beans, and cheese in tortillas.','Roll tightly; toast now or wrap and freeze for later.'],['freezer','batch','breakfast-for-dinner'],'Easy','Cook eggs until set and reheat burritos to 165°F.'),
  make('broccoli-quiche','Broccoli cheddar crustless quiche','A tender, make-ahead egg bake with broccoli and sharp cheddar.','French-inspired','Eggs',6,15,35,'8.90',1,4,[ing('eggs','Eggs','8','count'),ing('broccoli','Broccoli','8','oz'),ing('cheddar','Cheddar','5','oz'),ing('milk','Milk','1','cup')],['Steam broccoli until just tender.','Whisk eggs with milk and fold in broccoli and cheese.','Bake at 375°F until puffed and set in the center.'],['meatless','make-ahead','brunch'],'Easy','Cook until the center is fully set.'),
  make('chicken-parmesan-sandwich','Air-fryer chicken parmesan sandwiches','Crisp chicken breast, tomato sauce, mozzarella, and a cooked zucchini side.','Italian-American','Chicken',2,20,20,'11.80',2,3,[ing('chicken','Chicken breast','0.75','lb'),ing('breadcrumbs','Breadcrumbs','0.75','cup'),ing('rolls','Sandwich rolls','2','count'),ing('tomatoes','Tomato sauce','0.75','cup'),ing('zucchini','Zucchini','1','count')],['Bread the chicken and air-fry until crisp and 165°F.','Warm tomato sauce, melt mozzarella over the chicken, and toast the rolls.','Assemble sandwiches and serve with sautéed zucchini.'],['air-fryer','sandwich','complete-meal'],'Medium','Verify breadcrumbs and rolls are nut-free and cook chicken to 165°F.'),
  make('garlic-chicken-minestrone','Garlic chicken pasta and vegetable stew','A smaller two-serving stew with chicken breast, pasta, beans, tomatoes, and vegetables.','Italian','Chicken',2,15,30,'9.40',1,5,[ing('chicken','Chicken breast','0.625','lb'),ing('white-beans','White beans','0.5','can'),ing('tomatoes','Crushed tomatoes','0.5','can'),ing('pasta','Small pasta','3','oz'),ing('zucchini','Zucchini','1','count')],['Brown diced chicken breast, then soften garlic and zucchini.','Add tomatoes, beans, broth, and pasta; simmer until tender.','Confirm the chicken reaches 165°F and finish with lemon and parsley.'],['two-serving','one-pot','leftovers'],'Easy','Cook chicken to 165°F.'),
  make('chicken-alfredo-tortellini','Chicken Alfredo tortellini skillet','Chicken breast, cheese tortellini, spinach, and broccoli in a creamy garlic sauce.','Italian-inspired','Chicken',2,15,20,'12.20',1,4,[ing('chicken','Chicken breast','0.75','lb'),ing('tortellini','Cheese tortellini','8','oz'),ing('spinach','Spinach','3','oz'),ing('broccoli','Broccoli','6','oz'),ing('cream','Cream','0.5','cup')],['Sear sliced chicken breast to 165°F and set aside.','Cook tortellini and broccoli, then make a garlic cream sauce in the skillet.','Fold in spinach, tortellini, broccoli, and chicken; plate with parmesan.'],['alfredo','one-pan','leftovers'],'Easy','Cook chicken to 165°F.'),
  make('sesame-chicken-noodles','Sesame chicken vegetable noodles','Chicken breast, noodles, and broccoli in a savory soy-sesame sauce with no nuts.','Chinese-inspired','Chicken',2,15,20,'10.80',2,4,[ing('chicken','Chicken breast','0.75','lb'),ing('noodles','Noodles','6','oz'),ing('broccoli','Broccoli','8','oz'),ing('soy','Soy sauce','3','tbsp'),ing('sesame-oil','Sesame oil','2','tsp')],['Cook noodles and steam broccoli.','Sear sliced chicken breast until it reaches 165°F.','Whisk soy, sesame oil, garlic, and vinegar; toss with noodles, broccoli, and chicken.'],['noodles','nut-free','quick'],'Easy','Use a nut-free facility if required for sesame products and cook chicken to 165°F.')
];

const now = new Date(); const iso = (days: number) => new Date(now.getTime() + days * 86400000).toISOString().slice(0,10);
export const initialInventory: InventoryItem[] = [
  { id:'inv-chicken',ingredientId:'chicken',name:'Chicken breast',quantity:'2.5',reserved:'0',unit:'lb',confidence:.82,expiresOn:iso(2),location:'Fridge',lastConfirmedAt:new Date(now.getTime()-4*86400000).toISOString() },
  { id:'inv-eggs',ingredientId:'eggs',name:'Eggs',quantity:'7',reserved:'0',unit:'count',confidence:.65,expiresOn:iso(9),location:'Fridge',lastConfirmedAt:new Date(now.getTime()-7*86400000).toISOString() },
  { id:'inv-spinach',ingredientId:'spinach',name:'Baby spinach',quantity:'5',reserved:'0',unit:'oz',confidence:.55,expiresOn:iso(1),location:'Fridge',lastConfirmedAt:new Date(now.getTime()-5*86400000).toISOString() },
  { id:'inv-broccoli',ingredientId:'broccoli',name:'Broccoli',quantity:'12',reserved:'0',unit:'oz',confidence:.9,expiresOn:iso(4),location:'Fridge',lastConfirmedAt:new Date(now.getTime()-2*86400000).toISOString() },
  { id:'inv-rice',ingredientId:'rice',name:'Rice',quantity:'8',reserved:'0',unit:'cup',confidence:.95,location:'Pantry',lastConfirmedAt:new Date(now.getTime()-3*86400000).toISOString() },
  { id:'inv-pasta',ingredientId:'pasta',name:'Pasta',quantity:'24',reserved:'0',unit:'oz',confidence:.9,location:'Pantry',lastConfirmedAt:new Date(now.getTime()-8*86400000).toISOString() },
  { id:'inv-chickpeas',ingredientId:'chickpeas',name:'Chickpeas',quantity:'2',reserved:'0',unit:'can',confidence:.95,location:'Pantry',lastConfirmedAt:new Date(now.getTime()-10*86400000).toISOString() },
  { id:'inv-lemon',ingredientId:'lemon',name:'Lemons',quantity:'2',reserved:'0',unit:'count',confidence:.75,expiresOn:iso(6),location:'Fridge',lastConfirmedAt:new Date(now.getTime()-6*86400000).toISOString() }
];
