import { BookOpen, CalendarDays, ChefHat, ClipboardCheck, ClipboardList, CookingPot, History, Home, Menu, Settings, WifiOff, X } from 'lucide-react';
import { useEffect, useState } from 'react';
import { NavLink, Outlet } from 'react-router-dom';

const nav=[['/','Dashboard',Home],['/plan','Plan Week',CalendarDays],['/week','This Week',ClipboardList],['/prep','Sunday Prep',ClipboardCheck],['/kitchen','Kitchen',CookingPot],['/recipes','Recipes',BookOpen],['/groceries','Grocery List',ChefHat],['/history','History & Insights',History],['/settings','Settings',Settings]] as const;
export function Shell(){const [open,setOpen]=useState(false);const [online,setOnline]=useState(navigator.onLine);useEffect(()=>{const on=()=>setOnline(true),off=()=>setOnline(false);addEventListener('online',on);addEventListener('offline',off);return()=>{removeEventListener('online',on);removeEventListener('offline',off)}},[]);return <div className="min-h-screen bg-cream lg:grid lg:grid-cols-[250px_1fr]">
  <header className="sticky top-0 z-30 flex items-center justify-between border-b border-black/5 bg-cream/95 px-5 py-4 backdrop-blur lg:hidden"><Logo/><button aria-label="Open navigation" className="rounded-full p-2" onClick={()=>setOpen(true)}><Menu/></button></header>
  <aside className={`${open?'fixed inset-0 z-40 flex':'hidden'} bg-black/30 lg:sticky lg:top-0 lg:flex lg:h-screen lg:bg-transparent`} onClick={()=>setOpen(false)}><div className="flex h-full w-[280px] flex-col bg-[#f0eadf] p-5" onClick={e=>e.stopPropagation()}><div className="flex items-center justify-between"><Logo/><button aria-label="Close navigation" className="p-2 lg:hidden" onClick={()=>setOpen(false)}><X/></button></div><nav aria-label="Main navigation" className="mt-10 space-y-1">{nav.map(([to,label,Icon])=><NavLink key={to} end={to==='/'} to={to} onClick={()=>setOpen(false)} className={({isActive})=>`flex items-center gap-3 rounded-2xl px-4 py-3 text-sm font-medium ${isActive?'bg-white text-herb-700 shadow-sm':'text-ink/65 hover:bg-white/60 hover:text-ink'}`}><Icon size={19}/>{label}</NavLink>)}</nav><div className="mt-auto rounded-2xl bg-herb-700 p-4 text-white"><p className="font-display text-lg">Weekend rhythm</p><p className="mt-1 text-xs text-white/70">Confirm the uncertain. Plan what sounds good. Waste less.</p></div></div></aside>
  <main className="min-w-0"><div className="mx-auto max-w-[1400px] px-5 py-7 sm:px-8 lg:px-10 lg:py-10">{!online&&<div role="status" className="mb-5 flex items-center gap-2 rounded-2xl bg-amber-100 px-4 py-3 text-sm text-amber-900"><WifiOff size={17}/>You’re offline. Recipes and your active cooking session remain available.</div>}<Outlet/></div></main></div>}
function Logo(){return <div className="flex items-center gap-2.5"><span className="grid size-10 place-items-center rounded-2xl bg-herb-600 text-white"><ChefHat size={21}/></span><div><div className="font-display text-2xl leading-none">Shua</div><div className="text-[10px] font-semibold uppercase tracking-[.16em] text-ink/45">Plan · cook · enjoy</div></div></div>}
