import { ArrowRight, Clock, Sparkles, Trash2, Users } from 'lucide-react';
import { Link } from 'react-router-dom';
import type { Recipe } from '@mise/domain';

export function PageTitle({eyebrow,title,description,action}:{eyebrow:string;title:string;description:string;action?:React.ReactNode}){return <div className="mb-8 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="eyebrow">{eyebrow}</p><h1 className="mt-2 text-4xl leading-tight sm:text-5xl">{title}</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-ink/60">{description}</p></div>{action}</div>}
export function RecipeArtwork({recipe,loading='lazy'}:{recipe:Recipe;loading?:'eager'|'lazy'}){if(recipe.photoUrl)return <img src={recipe.photoUrl} alt={`Representative serving of ${recipe.title}`} loading={loading} className="absolute inset-0 size-full object-cover"/>;const emoji=recipe.protein==='Chicken'?'🍗':recipe.protein==='Salmon'||recipe.protein==='White fish'||recipe.protein.toLowerCase().includes('fish')?'🐟':recipe.protein==='Eggs'?'🍳':recipe.protein==='Ground beef'||recipe.protein==='Beef'?'🥩':'🥬';return <div role="img" aria-label={`Recipe placeholder for ${recipe.title}`} className="absolute inset-0 grid place-items-center"><div className="absolute inset-0 opacity-25" style={{backgroundImage:'radial-gradient(circle at 20% 20%,white 0 2px,transparent 3px)',backgroundSize:'24px 24px'}}/><span className="relative text-5xl opacity-80" aria-hidden>{emoji}</span></div>}
export function RecipeCard({recipe,reason,compact=false,onDelete,deleting=false}:{recipe:Recipe;reason?:string;compact?:boolean;onDelete?:()=>void;deleting?:boolean}){
  const colors:Record<string,string>={Chicken:'from-[#d9ad72] to-[#8d6b3f]',Salmon:'from-[#e59a7d] to-[#b95c49]','Ground beef':'from-[#a97b60] to-[#664a3c]',Eggs:'from-[#e6c56d] to-[#b78e38]','White fish':'from-[#98c6bd] to-[#4d8077]',Tofu:'from-[#c7b792] to-[#857759]',Lentils:'from-[#ca835c] to-[#895039]',Chickpeas:'from-[#d5b56f] to-[#8f743c]'};
  return <article className={`group overflow-hidden rounded-3xl border border-black/5 bg-white shadow-soft ${compact?'':'h-full'}`}>
    <div className={`relative ${compact?'h-32':'h-44'} bg-gradient-to-br ${colors[recipe.protein]??'from-herb-500 to-herb-700'}`}>
      <RecipeArtwork recipe={recipe}/>
      {onDelete&&<button type="button" disabled={deleting} onClick={onDelete} aria-label={`Delete ${recipe.title}`} className="absolute right-3 top-3 grid size-9 place-items-center rounded-full bg-white/90 text-red-700 shadow-sm transition hover:bg-white disabled:opacity-50"><Trash2 size={16}/></button>}
    </div>
    <Link to={`/recipes/${recipe.id}`} className="block p-5"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-wider text-herb-600">{recipe.cuisine}</p><h3 className="mt-1 text-xl leading-tight group-hover:text-herb-700">{recipe.title}</h3></div><ArrowRight className="mt-2 shrink-0 text-ink/30 transition group-hover:translate-x-1 group-hover:text-herb-600" size={18}/></div>{!compact&&<p className="mt-2 line-clamp-2 text-sm leading-5 text-ink/55">{recipe.description}</p>}<div className="mt-4 flex flex-wrap gap-3 text-xs text-ink/55"><span className="flex items-center gap-1"><Clock size={14}/>{recipe.prepMinutes+recipe.cookMinutes} min</span><span className="flex items-center gap-1"><Users size={14}/>{recipe.servings}</span><span>${recipe.estimatedCost}</span></div>{reason&&<p className="mt-4 flex items-start gap-2 rounded-xl bg-herb-50 p-3 pr-24 text-xs leading-5 text-herb-700"><Sparkles size={14} className="mt-0.5 shrink-0"/>{reason}</p>}</Link>
  </article>
}
export function EmptyState({title,body,action}:{title:string;body:string;action?:React.ReactNode}){return <div className="rounded-3xl border border-dashed border-black/15 p-10 text-center"><p className="font-display text-2xl">{title}</p><p className="mx-auto mt-2 max-w-md text-sm text-ink/55">{body}</p>{action&&<div className="mt-5">{action}</div>}</div>}
