import { createClient } from 'npm:@supabase/supabase-js@2.45.1';
import { getAIProvider, recipeSchema, weeklyPrepPlanSchema, type GeneratedRecipe } from '../_shared/ai.ts';

const cors={'access-control-allow-origin':Deno.env.get('APP_URL')??'http://localhost:5173','access-control-allow-headers':'authorization,content-type,idempotency-key,x-confirmation-token','access-control-allow-methods':'GET,POST,PATCH,DELETE,OPTIONS','x-content-type-options':'nosniff','referrer-policy':'no-referrer'};
const admin=createClient(Deno.env.get('SUPABASE_URL')!,Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!);
type Auth={userId:string;tokenId?:string;scopes:string[]};
const json=(requestId:string,data:unknown,status=200)=>new Response(JSON.stringify(status>=400?{requestId,error:data}:{requestId,data}),{status,headers:{...cors,'content-type':'application/json','x-request-id':requestId}});
const error=(id:string,code:string,message:string,status=400,retryable=false)=>json(id,{code,message,retryable},status);
const hash=async(value:string)=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(`${Deno.env.get('INTEGRATION_TOKEN_PEPPER')}:${value}`)))).map(x=>x.toString(16).padStart(2,'0')).join('');
async function authenticate(req:Request):Promise<Auth|null>{const bearer=req.headers.get('authorization')?.replace(/^Bearer /i,'');if(!bearer)return null;if(bearer.startsWith('shua_')||bearer.startsWith('mise_')){const tokenHash=await hash(bearer);const {data}=await admin.from('integration_tokens').select('id,user_id,scopes,expires_at,revoked_at').eq('token_hash',tokenHash).maybeSingle();if(!data||data.revoked_at||(data.expires_at&&new Date(data.expires_at)<new Date()))return null;await admin.from('integration_tokens').update({last_used_at:new Date().toISOString()}).eq('id',data.id);return {userId:data.user_id,tokenId:data.id,scopes:data.scopes}}const {data}=await admin.auth.getUser(bearer);return data.user?{userId:data.user.id,scopes:['*']}:null}
const requireScope=(auth:Auth,scope:string)=>auth.scopes.includes('*')||auth.scopes.includes(scope);
async function audit(auth:Auth,requestId:string,action:string,resource?:string){if(auth.tokenId)await admin.from('integration_audit_logs').insert({user_id:auth.userId,token_id:auth.tokenId,request_id:requestId,action,resource_id:resource,summary:{source:'integration'}})}
const unsignedDecimal=/^\d+(\.\d{1,4})?$/;
const signedDecimal=/^-?\d+(\.\d{1,4})?$/;
const allowedUnits=new Set(['count','serving','tsp','tbsp','fl_oz','cup','oz','lb','g','kg','ml','l','package','bag','can','bottle','bunch']);
const startingTasteProfile='Favor chicken breast first; then salmon, boneless white fish, ground beef, burgers, steak, eggs, and easy-prep shrimp. Never use peanuts, tree nuts, nut-derived sauces, or pork. Avoid fatty pieces, bones, cartilage, gristle, wraps, pickled onions, mustard-forward sauces, and labor-intensive shrimp prep. Prefer cooked vegetables and a complete, nicely plated meal with protein plus rice, pasta, potatoes, and/or vegetables. Make exactly 2 servings for dinner and lunch tomorrow. Favor Latin American, Italian, Mediterranean, American, Middle Eastern, Filipino, and Chinese flavors; tangy lemon/lime/vinegar, garlic, herbs, cumin, paprika, curry, hot honey, soy, teriyaki, chimichurri, nut-free pesto, tomato sauce, Alfredo, hot sauce, fresh salsa verde, yogurt sauce, cream, cheese, and coconut milk. Keep meatless meals occasional and target about 35 minutes.';
const normalizeRecipeTitle=(value:string)=>value.toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();
async function priorIdempotent(auth:Auth,key:string,requestHash:string){const {data}=await admin.from('idempotency_records').select('*').eq('user_id',auth.userId).eq('key',key).maybeSingle();if(!data)return null;if(data.request_hash!==requestHash)return {conflict:true as const};return {conflict:false as const,response:data.response_body}}
async function rememberIdempotent(auth:Auth,key:string,requestHash:string,responseBody:unknown,status=200){await admin.from('idempotency_records').insert({user_id:auth.userId,key,request_hash:requestHash,response_status:status,response_body:responseBody,expires_at:new Date(Date.now()+86400000).toISOString()})}
const withUtm=(value:string)=>{const url=new URL(value);url.searchParams.set('utm_source','shua');url.searchParams.set('utm_medium','referral');return url.toString()};
async function findUnsplashPhotos(query:string){const accessKey=Deno.env.get('UNSPLASH_ACCESS_KEY');if(!accessKey)return [];const response=await fetch(`https://api.unsplash.com/search/photos?query=${encodeURIComponent(query)}&per_page=3&orientation=landscape&content_filter=high`,{headers:{authorization:`Client-ID ${accessKey}`,'accept-version':'v1'}});if(!response.ok)throw new Error(`unsplash_http_${response.status}`);const payload=await response.json();return (Array.isArray(payload.results)?payload.results:[]).slice(0,3).map((photo:any)=>({id:String(photo.id),imageUrl:String(photo.urls?.regular??photo.urls?.small),thumbUrl:String(photo.urls?.small??photo.urls?.thumb),altText:String(photo.alt_description??photo.description??query),photographerName:String(photo.user?.name??'Unsplash photographer'),photographerUrl:withUtm(String(photo.user?.links?.html??'https://unsplash.com')),sourceUrl:withUtm(String(photo.links?.html??'https://unsplash.com')),downloadLocation:String(photo.links?.download_location??''),provider:'unsplash'}))}
async function findRecipePhoto(recipe:{title:string;protein:string;cuisine:string}){for(const query of [recipe.title,`${recipe.protein} ${recipe.cuisine} dinner`]){const photo=(await findUnsplashPhotos(query))[0];if(photo)return photo}return null}
async function registerUnsplashDownload(photo:any){if(photo?.downloadLocation&&Deno.env.get('UNSPLASH_ACCESS_KEY'))await fetch(photo.downloadLocation,{headers:{authorization:`Client-ID ${Deno.env.get('UNSPLASH_ACCESS_KEY')}`,'accept-version':'v1'}}).catch(()=>undefined)}
const recipePhotoTypes:Record<string,string>={'image/jpeg':'jpg','image/png':'png','image/webp':'webp'};
async function validRecipePhoto(file:File){const bytes=new Uint8Array(await file.slice(0,12).arrayBuffer());if(file.type==='image/jpeg')return bytes[0]===0xff&&bytes[1]===0xd8&&bytes[2]===0xff;if(file.type==='image/png')return bytes.length>=8&&bytes[0]===0x89&&bytes[1]===0x50&&bytes[2]===0x4e&&bytes[3]===0x47&&bytes[4]===0x0d&&bytes[5]===0x0a&&bytes[6]===0x1a&&bytes[7]===0x0a;if(file.type==='image/webp')return bytes.length>=12&&String.fromCharCode(...bytes.slice(0,4))==='RIFF'&&String.fromCharCode(...bytes.slice(8,12))==='WEBP';return false}
function validatePrepMath(plan:any,request:any){const failures:string[]=[];const meals=new Map((Array.isArray(request?.meals)?request.meals:[]).map((meal:any)=>[String(meal.mealId),meal]));const ids=new Set<string>(),used=new Map<string,number>();let totalMinutes=0,saved=0;for(const task of plan.tasks){if(ids.has(task.id))failures.push('duplicate_task_id');ids.add(task.id);totalMinutes+=task.estimatedMinutes;saved+=task.weekdayMinutesSaved;for(const ingredient of task.ingredients){let sum=0;for(const allocation of ingredient.allocations){if(allocation.unit!==ingredient.unit)failures.push('incompatible_allocation_unit');const amount=Math.round(Number(allocation.quantity)*10000);sum+=amount;const meal:any=meals.get(allocation.mealId);if(!meal||meal.date!==allocation.mealDate||meal.title!==allocation.mealTitle)failures.push('unknown_meal_allocation');const source=meal?.ingredients?.find((item:any)=>item.ingredientId===ingredient.ingredientId&&item.unit===ingredient.unit&&item.name.toLowerCase()===ingredient.name.toLowerCase());const sourceKey=`${allocation.mealId}:${ingredient.ingredientId}:${ingredient.name.toLowerCase()}:${ingredient.unit}`;used.set(sourceKey,(used.get(sourceKey)??0)+amount);if(!source||(used.get(sourceKey)??0)>Math.round(Number(source.quantity)*10000))failures.push('allocation_exceeds_recipe');}if(sum!==Math.round(Number(ingredient.totalQuantity)*10000))failures.push('ingredient_total_mismatch')}}if(totalMinutes!==plan.totalMinutes)failures.push('duration_total_mismatch');if(saved!==plan.estimatedWeeknightMinutesSaved)failures.push('savings_total_mismatch');return [...new Set(failures)]}

Deno.serve(async req=>{const requestId=req.headers.get('x-request-id')??crypto.randomUUID();if(req.method==='OPTIONS')return new Response(null,{status:204,headers:cors});try{const auth=await authenticate(req);if(!auth)return error(requestId,'unauthorized','A valid user session or integration token is required.',401);const url=new URL(req.url);const path=url.pathname.replace(/^.*\/api\/v1/,'');
  if(req.method==='GET'&&path==='/ingredients'){if(!requireScope(auth,'inventory:read'))return error(requestId,'forbidden','Missing inventory:read scope.',403);const query=url.searchParams.get('q')?.trim();let lookup=admin.from('ingredients').select('id,slug,name,category,default_unit,perishable,default_shelf_days').order('name').limit(100);if(query)lookup=lookup.ilike('name',`%${query.replaceAll('%','')}%`);const {data,error:e}=await lookup;if(e)throw e;return json(requestId,data)}
  const ingredientPhotoMatch=path.match(/^\/ingredients\/([0-9a-f-]+)\/photo$/i);
  if(req.method==='GET'&&ingredientPhotoMatch){if(!requireScope(auth,'inventory:read'))return error(requestId,'forbidden','Missing inventory:read scope.',403);const {data:ingredient,error:ingredientError}=await admin.from('ingredients').select('id,name,photo_url').eq('id',ingredientPhotoMatch[1]).maybeSingle();if(ingredientError)throw ingredientError;if(!ingredient)return error(requestId,'not_found','Ingredient not found.',404);if(ingredient.photo_url)return json(requestId,{imageUrl:ingredient.photo_url});const photos=await findUnsplashPhotos(ingredient.name);const photo=photos[0]??null;if(!photo)return json(requestId,{imageUrl:null});const {error:updateError}=await admin.from('ingredients').update({photo_url:photo.imageUrl,photo_attribution:photo}).eq('id',ingredient.id);if(updateError)throw updateError;if(photo.downloadLocation&&Deno.env.get('UNSPLASH_ACCESS_KEY'))await fetch(photo.downloadLocation,{headers:{authorization:`Client-ID ${Deno.env.get('UNSPLASH_ACCESS_KEY')}`,'accept-version':'v1'}}).catch(()=>undefined);return json(requestId,{imageUrl:photo.imageUrl})}
  if(req.method==='GET'&&path==='/inventory'){if(!requireScope(auth,'inventory:read'))return error(requestId,'forbidden','Missing inventory:read scope.',403);const {data,error:e}=await admin.from('inventory_items').select('*,ingredients(name,category,photo_url),storage_locations(name)').eq('user_id',auth.userId).order('estimated_expiration_date',{ascending:true,nullsFirst:false});if(e)throw e;return json(requestId,data)}
  if(req.method==='GET'&&path==='/inventory/expiring'){if(!requireScope(auth,'inventory:read'))return error(requestId,'forbidden','Missing inventory:read scope.',403);const cutoff=new Date(Date.now()+3*86400000).toISOString().slice(0,10);const {data}=await admin.from('inventory_items').select('*,ingredients(name)').eq('user_id',auth.userId).lte('estimated_expiration_date',cutoff).gt('quantity',0);return json(requestId,data)}
  if(req.method==='POST'&&path==='/inventory'){
    if(!requireScope(auth,'inventory:write'))return error(requestId,'forbidden','Missing inventory:write scope.',403);
    const body=await req.json();const quantity=String(body.quantity??'');
    if(typeof body.ingredientId!=='string'||!unsignedDecimal.test(quantity)||Number(quantity)<=0||typeof body.unit!=='string')return error(requestId,'validation_error','Ingredient, positive quantity, and unit are required.');
    const key=req.headers.get('idempotency-key');if(!key)return error(requestId,'idempotency_required','Idempotency-Key is required.',400);
    const payloadHash=await hash(JSON.stringify(body));const prior=await priorIdempotent(auth,key,payloadHash);if(prior?.conflict)return error(requestId,'idempotency_conflict','This key was already used for a different request.',409);if(prior)return json(requestId,prior.response);
    const {data,error:e}=await admin.rpc('api_add_inventory_item',{p_user:auth.userId,p_ingredient:body.ingredientId,p_location:String(body.location??'Pantry'),p_quantity:quantity,p_unit:body.unit,p_expiration:body.expiresOn||null,p_idempotency:key});if(e)throw e;
    await rememberIdempotent(auth,key,payloadHash,data,201);await audit(auth,requestId,'add_inventory',data?.id);return json(requestId,data,201);
  }
  if(req.method==='POST'&&path==='/inventory/adjust'){
    if(!requireScope(auth,'inventory:write'))return error(requestId,'forbidden','Missing inventory:write scope.',403);
    const body=await req.json();const delta=String(body.quantityDelta??'');if(!signedDecimal.test(delta))return error(requestId,'validation_error','quantityDelta must be a fixed-precision decimal string.');
    const payloadHash=await hash(JSON.stringify(body));const suppliedConfirmation=req.headers.get('x-confirmation-token');
    if(Math.abs(Number(delta))>25&&!suppliedConfirmation){const token=`confirm_${crypto.randomUUID()}`;const expiresAt=new Date(Date.now()+10*60000).toISOString();const summary=`Adjust inventory by ${delta} ${body.unit}.`;await admin.from('confirmation_tokens').insert({user_id:auth.userId,token_hash:await hash(token),action:'inventory.adjust',payload_hash:payloadHash,summary,expires_at:expiresAt});return json(requestId,{code:'confirmation_required',message:summary,retryable:true,confirmationToken:token,summary,expiresAt},409)}
    if(Math.abs(Number(delta))>25&&suppliedConfirmation){const {data:confirmation}=await admin.from('confirmation_tokens').select('*').eq('user_id',auth.userId).eq('token_hash',await hash(suppliedConfirmation)).eq('action','inventory.adjust').eq('payload_hash',payloadHash).is('consumed_at',null).gt('expires_at',new Date().toISOString()).maybeSingle();if(!confirmation)return error(requestId,'invalid_confirmation','Confirmation is invalid, expired, consumed, or belongs to another payload.',409);await admin.from('confirmation_tokens').update({consumed_at:new Date().toISOString()}).eq('id',confirmation.id)}
    const key=req.headers.get('idempotency-key');if(!key)return error(requestId,'idempotency_required','Idempotency-Key is required.',400);const prior=await priorIdempotent(auth,key,payloadHash);if(prior?.conflict)return error(requestId,'idempotency_conflict','This key was already used for a different request.',409);if(prior)return json(requestId,prior.response);
    const {data,error:e}=await admin.rpc('api_adjust_inventory_quantity',{p_user:auth.userId,p_item:body.inventoryItemId,p_delta:delta,p_reason:String(body.reason??'manual'),p_idempotency:key});if(e?.message?.includes('inventory_item_not_found'))return error(requestId,'not_found','Inventory item not found.',404);if(e)throw e;
    await rememberIdempotent(auth,key,payloadHash,data);await audit(auth,requestId,'adjust_inventory',body.inventoryItemId);return json(requestId,data);
  }
  if(req.method==='GET'&&path==='/plans/current'){if(!requireScope(auth,'plans:read'))return error(requestId,'forbidden','Missing plans:read scope.',403);const today=new Date();const day=(today.getUTCDay()+6)%7;const monday=new Date(today);monday.setUTCDate(today.getUTCDate()-day);const {data}=await admin.from('weekly_plans').select('*,planned_meals(*,recipe_versions(*,recipes(*)))').eq('user_id',auth.userId).eq('week_start',monday.toISOString().slice(0,10)).maybeSingle();return json(requestId,data)}
  if(req.method==='GET'&&path==='/settings'){if(!auth.scopes.includes('*'))return error(requestId,'forbidden','Only the signed-in Shua app can read settings.',403);const [{data:prefs,error:prefsError},{data:purchases,error:purchaseError}]=await Promise.all([admin.from('user_preferences').select('monthly_grocery_budget,preferred_proteins,exclusions,exploration_mix,settings').eq('user_id',auth.userId).single(),admin.from('grocery_purchases').select('price').eq('user_id',auth.userId).gte('purchased_at',new Date(Date.UTC(new Date().getUTCFullYear(),new Date().getUTCMonth(),1)).toISOString())]);if(prefsError)throw prefsError;if(purchaseError)throw purchaseError;const stored=prefs.settings??{};return json(requestId,{monthlyBudget:String(prefs.monthly_grocery_budget),weekdayLimit:Number(stored.weekdayLimit??40),planLunch:stored.planLunch!==false,coveredStaples:stored.coveredStaples!==false,exploration:Number(stored.exploration??Math.round(Number(prefs.exploration_mix?.exploratory??.15)*100)),preferredProteins:(prefs.preferred_proteins??[]).join(', ')||'Chicken breast, Salmon, White fish, Ground beef, Steak, Eggs, Shrimp',exclusions:(prefs.exclusions??[]).join(' ')||'STRICT ALLERGY: no peanuts, tree nuts, or nut-derived sauces. No pork.',tasteProfile:String(stored.tasteProfile??startingTasteProfile),monthlySpent:String((purchases??[]).reduce((sum,row)=>sum+Number(row.price),0).toFixed(2))})}
  if(req.method==='PATCH'&&path==='/settings'){if(!auth.scopes.includes('*'))return error(requestId,'forbidden','Only the signed-in Shua app can update settings.',403);const body=await req.json();const monthlyBudget=Number(body.monthlyBudget),weekdayLimit=Number(body.weekdayLimit),exploration=Number(body.exploration);if(!Number.isFinite(monthlyBudget)||monthlyBudget<0||![30,40,60].includes(weekdayLimit)||!Number.isInteger(exploration)||exploration<0||exploration>100)return error(requestId,'validation_error','Review the budget, time limit, and exploration values.');const preferredProteins=String(body.preferredProteins??'').split(',').map((x:string)=>x.trim()).filter(Boolean).slice(0,30);const exclusions=String(body.exclusions??'').trim()?[String(body.exclusions).trim().slice(0,4000)]:[];const tasteProfile=String(body.tasteProfile??startingTasteProfile).trim().slice(0,8000);const settings={weekdayLimit,planLunch:Boolean(body.planLunch),coveredStaples:Boolean(body.coveredStaples),exploration,tasteProfile};const {error:e}=await admin.from('user_preferences').update({monthly_grocery_budget:monthlyBudget,preferred_proteins:preferredProteins,exclusions,exploration_mix:{familiar:(100-exploration)/100,variation:.25,exploratory:exploration/100},settings,updated_at:new Date().toISOString()}).eq('user_id',auth.userId);if(e)throw e;return json(requestId,{monthlyBudget:String(monthlyBudget),weekdayLimit,planLunch:settings.planLunch,coveredStaples:settings.coveredStaples,exploration,preferredProteins:preferredProteins.join(', '),exclusions:exclusions.join(' '),tasteProfile})}
  if(req.method==='GET'&&path==='/recipes'){if(!requireScope(auth,'recipes:read'))return error(requestId,'forbidden','Missing recipes:read scope.',403);const {data,error:e}=await admin.from('recipes').select('*,recipe_versions(*,recipe_ingredients(*,ingredients(name)),recipe_steps(*)),recipe_tags(tag)').or(`user_id.eq.${auth.userId},user_id.is.null`).is('archived_at',null).order('created_at',{ascending:false}).limit(100);if(e)throw e;const rows=data??[];if(!rows.length)return json(requestId,rows);const {data:uploads,error:uploadError}=await admin.from('recipe_photos').select('recipe_id,storage_path,created_at').eq('user_id',auth.userId).eq('is_primary',true).in('recipe_id',rows.map(row=>row.id)).order('created_at',{ascending:false});if(uploadError)throw uploadError;const customPhotos=new Map<string,string>();for(const upload of uploads??[]){if(customPhotos.has(upload.recipe_id))continue;const {data:signed}=await admin.storage.from('recipe-photos').createSignedUrl(upload.storage_path,604800);if(signed?.signedUrl)customPhotos.set(upload.recipe_id,signed.signedUrl)}return json(requestId,rows.map(row=>customPhotos.has(row.id)?{...row,primary_photo_url:customPhotos.get(row.id),photo_attribution:null}:row))}
  if(req.method==='DELETE'&&path==='/recipes'){if(!auth.scopes.includes('*'))return error(requestId,'forbidden','Only the signed-in Shua app can clear recipes.',403);const {data,error:e}=await admin.from('recipes').update({archived_at:new Date().toISOString()}).eq('user_id',auth.userId).is('archived_at',null).select('id');if(e)throw e;return json(requestId,{deleted:data?.length??0})}
  if(req.method==='POST'&&path==='/recipes'){if(!auth.scopes.includes('*'))return error(requestId,'forbidden','Only the signed-in Shua app can save a manual recipe.',403);const parsed=recipeSchema.safeParse(await req.json());if(!parsed.success)return json(requestId,{code:'validation_error',message:'Review the recipe fields before saving.',retryable:false,fields:parsed.error.flatten()},422);const {data,error:e}=await admin.rpc('save_manual_recipe',{p_user:auth.userId,p_recipe:parsed.data});if(e)throw e;const {error:nutritionError}=await admin.from('recipe_versions').update({calories_per_serving:parsed.data.caloriesPerServing,protein_grams_per_serving:parsed.data.proteinGramsPerServing,leftover_days:1}).eq('id',data.recipeVersionId);if(nutritionError)throw nutritionError;return json(requestId,data,201)}
  if(req.method==='POST'&&path==='/recipes/import'){
    if(!auth.scopes.includes('*'))return error(requestId,'forbidden','Only the signed-in Shua app can import recipes.',403);
    const body=await req.json();const parsed=recipeSchema.array().min(1).max(100).safeParse(body.recipes);
    if(!parsed.success)return json(requestId,{code:'validation_error',message:'The recipe collection could not be imported.',retryable:false,fields:parsed.error.flatten()},422);
    const retireTitles=Array.isArray(body.retireTitles)?body.retireTitles.map((title:unknown)=>String(title).slice(0,200)).filter(Boolean).slice(0,100):[];
    let retired=0;
    if(retireTitles.length){const {data:retiredRows,error:retireError}=await admin.from('recipes').update({archived_at:new Date().toISOString()}).eq('user_id',auth.userId).in('title',retireTitles).is('archived_at',null).select('id');if(retireError)throw retireError;retired=retiredRows?.length??0}
    const {data:existing,error:existingError}=await admin.from('recipes').select('id,title,primary_photo_url').eq('user_id',auth.userId).is('archived_at',null);
    if(existingError)throw existingError;
    const existingByTitle=new Map((existing??[]).map(row=>[row.title.trim().toLowerCase(),row]));
    let imported=0,skipped=0,imagesAdded=0,imagesMissing=0;
    const needsPhoto:Array<{id:string;recipe:GeneratedRecipe}>=[];
    for(const recipe of parsed.data){
      const title=recipe.title.trim().toLowerCase();const current=existingByTitle.get(title);
      if(current){
        if(!current.primary_photo_url)needsPhoto.push({id:current.id,recipe});
        skipped++;continue;
      }
      const {data:saved,error:e}=await admin.rpc('save_manual_recipe',{p_user:auth.userId,p_recipe:recipe});if(e)throw e;
      const {error:nutritionError}=await admin.from('recipe_versions').update({calories_per_serving:recipe.caloriesPerServing,protein_grams_per_serving:recipe.proteinGramsPerServing,leftover_days:1}).eq('id',saved.recipeVersionId);
      if(nutritionError)throw nutritionError;
      existingByTitle.set(title,{id:saved.recipeId,title:recipe.title,primary_photo_url:null});needsPhoto.push({id:saved.recipeId,recipe});imported++;
    }
    const photos=Deno.env.get('UNSPLASH_ACCESS_KEY')?await Promise.all(needsPhoto.map(async item=>({item,photo:await findRecipePhoto(item.recipe).catch(()=>null)}))):needsPhoto.map(item=>({item,photo:null}));
    for(const {item,photo} of photos){if(!photo){imagesMissing++;continue}const {error:photoError}=await admin.from('recipes').update({primary_photo_url:photo.imageUrl,photo_attribution:photo}).eq('id',item.id).eq('user_id',auth.userId);if(photoError)throw photoError;await registerUnsplashDownload(photo);imagesAdded++}
    return json(requestId,{imported,skipped,retired,imagesAdded,imagesMissing},201);
  }
  const recipePhotoUploadMatch=path.match(/^\/recipes\/([0-9a-f-]+)\/photo$/i);
  if(req.method==='POST'&&recipePhotoUploadMatch){
    if(!auth.scopes.includes('*'))return error(requestId,'forbidden','Only the signed-in Shua app can upload recipe photos.',403);
    const contentLength=Number(req.headers.get('content-length')??0);if(contentLength>6*1024*1024)return error(requestId,'file_too_large','Recipe photos must be 5 MB or smaller.',413);
    const {data:recipe,error:recipeError}=await admin.from('recipes').select('id,title,user_id').eq('id',recipePhotoUploadMatch[1]).is('archived_at',null).maybeSingle();if(recipeError)throw recipeError;if(!recipe||(recipe.user_id!==null&&recipe.user_id!==auth.userId))return error(requestId,'not_found','Recipe not found.',404);
    const form=await req.formData();const file=form.get('file');if(!(file instanceof File)||file.size<1||file.size>5*1024*1024||!recipePhotoTypes[file.type]||!await validRecipePhoto(file))return error(requestId,'invalid_image','Choose a valid JPEG, PNG, or WebP image no larger than 5 MB.',422);
    const storagePath=`${auth.userId}/${recipe.id}/${crypto.randomUUID()}.${recipePhotoTypes[file.type]}`;const bucket=admin.storage.from('recipe-photos');const {error:storageError}=await bucket.upload(storagePath,file,{contentType:file.type,cacheControl:'3600',upsert:false});if(storageError)throw storageError;
    const {data:previous,error:previousError}=await admin.from('recipe_photos').select('id,storage_path').eq('user_id',auth.userId).eq('recipe_id',recipe.id);if(previousError){await bucket.remove([storagePath]);throw previousError}
    const {data:created,error:createError}=await admin.from('recipe_photos').insert({user_id:auth.userId,recipe_id:recipe.id,storage_path:storagePath,alt_text:`Photo of ${recipe.title}`,is_primary:false}).select('id').single();if(createError){await bucket.remove([storagePath]);throw createError}
    const {error:disableError}=await admin.from('recipe_photos').update({is_primary:false}).eq('user_id',auth.userId).eq('recipe_id',recipe.id);if(disableError){await admin.from('recipe_photos').delete().eq('id',created.id);await bucket.remove([storagePath]);throw disableError}
    const {error:primaryError}=await admin.from('recipe_photos').update({is_primary:true}).eq('id',created.id).eq('user_id',auth.userId);if(primaryError){if(previous?.length)await admin.from('recipe_photos').update({is_primary:true}).in('id',previous.map(row=>row.id));await admin.from('recipe_photos').delete().eq('id',created.id);await bucket.remove([storagePath]);throw primaryError}
    if(previous?.length){await admin.from('recipe_photos').delete().in('id',previous.map(row=>row.id)).eq('user_id',auth.userId);await bucket.remove(previous.map(row=>row.storage_path)).catch(()=>undefined)}
    const {data:signed,error:signedError}=await bucket.createSignedUrl(storagePath,604800);if(signedError)throw signedError;return json(requestId,{imageUrl:signed.signedUrl},201);
  }
  const deleteRecipeMatch=path.match(/^\/recipes\/([0-9a-f-]+)$/i);
  if(req.method==='DELETE'&&deleteRecipeMatch){if(!auth.scopes.includes('*'))return error(requestId,'forbidden','Only the signed-in Shua app can delete a recipe.',403);const {data,error:e}=await admin.from('recipes').update({archived_at:new Date().toISOString()}).eq('id',deleteRecipeMatch[1]).eq('user_id',auth.userId).is('archived_at',null).select('id').maybeSingle();if(e)throw e;if(!data)return error(requestId,'not_found','Recipe not found or cannot be deleted.',404);return json(requestId,{deleted:true})}
  if(req.method==='POST'&&path==='/recipe-jobs'){if(!auth.scopes.includes('*'))return error(requestId,'forbidden','Only the signed-in Shua app can request a recipe.',403);const body=await req.json();const protein=String(body.protein??'Chicken breast').slice(0,80);const minutes=Number(body.minutes??35);const servings=Number(body.servings??2);const notes=String(body.notes??'').slice(0,2000);if(!Number.isInteger(minutes)||minutes<10||minutes>720||!Number.isInteger(servings)||servings<1||servings>24)return error(requestId,'validation_error','Minutes and servings are outside the allowed range.');const [{data:prefs},{data:savedRecipes},{data:priorJobs}]=await Promise.all([admin.from('user_preferences').select('preferred_proteins,exclusions,settings').eq('user_id',auth.userId).maybeSingle(),admin.from('recipes').select('title').or(`user_id.eq.${auth.userId},user_id.is.null`).is('archived_at',null).limit(1000),admin.from('recipe_generation_jobs').select('recipe_draft').eq('user_id',auth.userId).not('recipe_draft','is',null).limit(1000)]);const avoidRecipeTitles=[...new Set([...(savedRecipes??[]).map(row=>String(row.title)),...(priorJobs??[]).map(row=>String(row.recipe_draft?.title??'')).filter(Boolean)])];const preferences={preferredProteins:prefs?.preferred_proteins??['Chicken breast','Salmon','White fish','Ground beef','Steak','Eggs','Shrimp'],exclusions:prefs?.exclusions??['STRICT ALLERGY: no peanuts, tree nuts, or nut-derived sauces. No pork.'],tasteProfile:String(prefs?.settings?.tasteProfile??startingTasteProfile)};const {data,error:e}=await admin.from('recipe_generation_jobs').insert({user_id:auth.userId,request:{protein,minutes,servings,notes,preferences,avoidRecipeTitles}}).select('*').single();if(e)throw e;return json(requestId,data,201)}
  if(req.method==='GET'&&path==='/recipe-jobs/latest'){if(!auth.scopes.includes('*'))return error(requestId,'forbidden','Only the signed-in Shua app can read recipe requests.',403);const {data,error:e}=await admin.from('recipe_generation_jobs').select('*').eq('user_id',auth.userId).in('status',['queued','processing','ready','failed']).order('created_at',{ascending:false}).limit(1).maybeSingle();if(e)throw e;return json(requestId,data)}
  const jobMatch=path.match(/^\/recipe-jobs\/([0-9a-f-]+)$/i);
  if(req.method==='GET'&&jobMatch){const {data,error:e}=await admin.from('recipe_generation_jobs').select('*').eq('id',jobMatch[1]).eq('user_id',auth.userId).maybeSingle();if(e)throw e;if(!data)return error(requestId,'not_found','Recipe request not found.',404);return json(requestId,data)}
  if(req.method==='POST'&&path==='/recipe-jobs/claim'){if(!auth.tokenId||!requireScope(auth,'recipes:write'))return error(requestId,'forbidden','A Miso token with recipes:write is required.',403);const {data,error:e}=await admin.rpc('claim_recipe_generation_job',{p_user:auth.userId});if(e)throw e;const job=Array.isArray(data)?data[0]??null:data;return json(requestId,job)}
  const completeMatch=path.match(/^\/recipe-jobs\/([0-9a-f-]+)\/complete$/i);
  if(req.method==='POST'&&completeMatch){if(!auth.tokenId||!requireScope(auth,'recipes:write'))return error(requestId,'forbidden','A Miso token with recipes:write is required.',403);const parsed=recipeSchema.safeParse(await req.json());if(!parsed.success)return json(requestId,{code:'ai_invalid_response',message:'Miso returned a recipe that did not pass validation.',retryable:true,fields:parsed.error.flatten()},422);const {data:job}=await admin.from('recipe_generation_jobs').select('id,request').eq('id',completeMatch[1]).eq('user_id',auth.userId).eq('status','processing').maybeSingle();if(!job)return error(requestId,'not_found','Claimed recipe request not found.',404);if(parsed.data.servings!==Number(job.request?.servings??2))return error(requestId,'ai_invalid_response','Miso returned the wrong serving count.',422,true);const ingredientNames=parsed.data.ingredients.map(item=>item.name.toLowerCase());const prohibited=/(^|\W)(peanut|almond|walnut|cashew|pecan|pistachio|hazelnut|macadamia|pork|bacon|ham|pancetta|prosciutto|lard)(s)?($|\W)/;if(ingredientNames.some(name=>prohibited.test(name)||(name.includes('pesto')&&!name.includes('nut-free'))))return error(requestId,'allergy_conflict','Miso returned a recipe that conflicts with the nut allergy or pork exclusion.',422,true);const completeSide=/(rice|pasta|potato|noodle|bread|tortilla|broccoli|cauliflower|carrot|bean|lentil|chickpea|pepper|spinach|cabbage|zucchini|tomato|corn|peas|asparagus|brussels|salad|mushroom)/;if(!ingredientNames.some(name=>completeSide.test(name)))return error(requestId,'incomplete_meal','Miso must pair the protein with a starch and/or cooked vegetables.',422,true);const [{data:savedTitles},{data:priorDrafts}]=await Promise.all([admin.from('recipes').select('title').or(`user_id.eq.${auth.userId},user_id.is.null`).is('archived_at',null).limit(1000),admin.from('recipe_generation_jobs').select('recipe_draft').eq('user_id',auth.userId).neq('id',job.id).not('recipe_draft','is',null).limit(1000)]);const usedTitles=new Set([...(savedTitles??[]).map(row=>normalizeRecipeTitle(String(row.title))),...(priorDrafts??[]).map(row=>normalizeRecipeTitle(String(row.recipe_draft?.title??''))).filter(Boolean)]);if(usedTitles.has(normalizeRecipeTitle(parsed.data.title)))return error(requestId,'duplicate_recipe','Miso already created or saved a recipe with this title. Generate a genuinely different meal.',409,true);const photos=await findUnsplashPhotos(parsed.data.title);const {data,error:e}=await admin.from('recipe_generation_jobs').update({status:'ready',recipe_draft:{...parsed.data,leftoverDays:1,imageSearchQuery:parsed.data.title},photo_candidates:photos,lease_expires_at:null,completed_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('id',job.id).select('*').single();if(e)throw e;await audit(auth,requestId,'complete_recipe_draft',job.id);return json(requestId,data)}
  const failMatch=path.match(/^\/recipe-jobs\/([0-9a-f-]+)\/fail$/i);
  if(req.method==='POST'&&failMatch){if(!auth.tokenId||!requireScope(auth,'recipes:write'))return error(requestId,'forbidden','A Miso token with recipes:write is required.',403);const body=await req.json();await admin.from('recipe_generation_jobs').update({status:'failed',error_code:String(body.errorCode??'miso_failed').slice(0,120),lease_expires_at:null,updated_at:new Date().toISOString()}).eq('id',failMatch[1]).eq('user_id',auth.userId).eq('status','processing');await audit(auth,requestId,'fail_recipe_draft',failMatch[1]);return json(requestId,{failed:true})}
  const discardMatch=path.match(/^\/recipe-jobs\/([0-9a-f-]+)\/discard$/i);
  if(req.method==='POST'&&discardMatch){if(!auth.scopes.includes('*'))return error(requestId,'forbidden','Only the signed-in Shua app can discard a recipe request.',403);const {data,error:e}=await admin.from('recipe_generation_jobs').update({status:'discarded',lease_expires_at:null,updated_at:new Date().toISOString()}).eq('id',discardMatch[1]).eq('user_id',auth.userId).in('status',['queued','processing','ready','failed']).select('id').maybeSingle();if(e)throw e;if(!data)return error(requestId,'conflict','This recipe request can no longer be discarded.',409);return json(requestId,{discarded:true})}
  const saveMatch=path.match(/^\/recipe-jobs\/([0-9a-f-]+)\/save$/i);
  if(req.method==='POST'&&saveMatch){if(!auth.scopes.includes('*'))return error(requestId,'forbidden','Only the signed-in Shua app can save a recipe.',403);const body=await req.json();const parsed=recipeSchema.safeParse(body.recipe);if(!parsed.success)return json(requestId,{code:'validation_error',message:'Review the highlighted recipe fields before saving.',retryable:false,fields:parsed.error.flatten()},422);const {data:jobForPhoto}=await admin.from('recipe_generation_jobs').select('photo_candidates').eq('id',saveMatch[1]).eq('user_id',auth.userId).maybeSingle();const requestedPhotoId=body.selectedPhoto?.id;const photo=requestedPhotoId&&Array.isArray(jobForPhoto?.photo_candidates)?jobForPhoto.photo_candidates.find((candidate:any)=>candidate.id===requestedPhotoId)??null:null;if(requestedPhotoId&&!photo)return error(requestId,'validation_error','Choose one of the reviewed Unsplash photos.',422);const {data,error:e}=await admin.rpc('save_generated_recipe',{p_user:auth.userId,p_job:saveMatch[1],p_recipe:parsed.data,p_photo:photo});if(e?.message?.includes('recipe_job_not'))return error(requestId,'conflict','This recipe draft is not ready to save.',409);if(e?.message?.includes('invalid_photo'))return error(requestId,'validation_error','Choose one of the reviewed Unsplash photos.',422);if(e)throw e;const {error:nutritionError}=await admin.from('recipe_versions').update({calories_per_serving:parsed.data.caloriesPerServing,protein_grams_per_serving:parsed.data.proteinGramsPerServing,leftover_days:1}).eq('id',data.recipeVersionId);if(nutritionError)throw nutritionError;if(photo?.downloadLocation&&Deno.env.get('UNSPLASH_ACCESS_KEY'))await fetch(photo.downloadLocation,{headers:{authorization:`Client-ID ${Deno.env.get('UNSPLASH_ACCESS_KEY')}`,'accept-version':'v1'}}).catch(()=>undefined);return json(requestId,data,201)}
  if(req.method==='POST'&&path==='/prep-jobs'){if(!auth.scopes.includes('*'))return error(requestId,'forbidden','Only the signed-in Shua app can request a prep plan.',403);const body=await req.json();const weekStart=String(body.weekStart??''),sourceFingerprint=String(body.sourceFingerprint??'').slice(0,1000),meals=Array.isArray(body.meals)?body.meals:[];if(!/^\d{4}-\d{2}-\d{2}$/.test(weekStart)||!sourceFingerprint||meals.length<1||meals.length>14)return error(requestId,'validation_error','Choose a valid week with one to fourteen planned meals.');const safeMeals=meals.map((meal:any)=>({mealId:String(meal.mealId??'').slice(0,120),date:String(meal.date??''),title:String(meal.title??'').slice(0,200),servings:Number(meal.servings),recipeTitle:String(meal.recipeTitle??'').slice(0,200),ingredients:Array.isArray(meal.ingredients)?meal.ingredients.slice(0,40).map((item:any)=>({ingredientId:String(item.ingredientId??'').slice(0,200),name:String(item.name??'').slice(0,160),quantity:String(item.quantity??''),unit:String(item.unit??'')})):[],steps:Array.isArray(meal.steps)?meal.steps.map((step:unknown)=>String(step).slice(0,2000)).slice(0,30):[],equipment:Array.isArray(meal.equipment)?meal.equipment.map((item:unknown)=>String(item).slice(0,160)).slice(0,20):[],safetyNote:String(meal.safetyNote??'').slice(0,1000)}));if(safeMeals.some((meal:any)=>!meal.mealId||!/^\d{4}-\d{2}-\d{2}$/.test(meal.date)||!meal.title||!meal.recipeTitle||!Number.isFinite(meal.servings)||meal.servings<=0||meal.ingredients.length<1||meal.ingredients.some((item:any)=>!item.ingredientId||!item.name||!unsignedDecimal.test(item.quantity)||Number(item.quantity)<=0||!allowedUnits.has(item.unit))))return error(requestId,'validation_error','One or more planned meals is incomplete.');const {data,error:e}=await admin.from('weekly_prep_jobs').insert({user_id:auth.userId,week_start:weekStart,source_fingerprint:sourceFingerprint,request:{weekStart,sourceFingerprint,meals:safeMeals}}).select('*').single();if(e)throw e;return json(requestId,data,201)}
  if(req.method==='GET'&&path==='/prep-jobs/latest'){if(!auth.scopes.includes('*'))return error(requestId,'forbidden','Only the signed-in Shua app can read prep plans.',403);const weekStart=url.searchParams.get('weekStart');if(!weekStart)return error(requestId,'validation_error','weekStart is required.');const {data,error:e}=await admin.from('weekly_prep_jobs').select('*').eq('user_id',auth.userId).eq('week_start',weekStart).order('created_at',{ascending:false}).limit(1).maybeSingle();if(e)throw e;return json(requestId,data)}
  const prepJobMatch=path.match(/^\/prep-jobs\/([0-9a-f-]+)$/i);
  if(req.method==='GET'&&prepJobMatch){const {data,error:e}=await admin.from('weekly_prep_jobs').select('*').eq('id',prepJobMatch[1]).eq('user_id',auth.userId).maybeSingle();if(e)throw e;if(!data)return error(requestId,'not_found','Prep request not found.',404);return json(requestId,data)}
  if(req.method==='PATCH'&&prepJobMatch){if(!auth.scopes.includes('*'))return error(requestId,'forbidden','Only the signed-in Shua app can update prep progress.',403);const body=await req.json();const taskIds=Array.isArray(body.completedTaskIds)?body.completedTaskIds.map((id:unknown)=>String(id)).slice(0,100):[];const {data:job}=await admin.from('weekly_prep_jobs').select('prep_plan').eq('id',prepJobMatch[1]).eq('user_id',auth.userId).eq('status','ready').maybeSingle();if(!job)return error(requestId,'not_found','Ready prep plan not found.',404);const allowed=new Set((job.prep_plan?.tasks??[]).map((task:any)=>task.id));if(taskIds.some((id:string)=>!allowed.has(id)))return error(requestId,'validation_error','Prep progress contains an unknown task.',422);const {data,error:e}=await admin.from('weekly_prep_jobs').update({completed_task_ids:[...new Set(taskIds)],updated_at:new Date().toISOString()}).eq('id',prepJobMatch[1]).select('*').single();if(e)throw e;return json(requestId,data)}
  if(req.method==='POST'&&path==='/prep-jobs/claim'){if(!auth.tokenId||!requireScope(auth,'plans:write'))return error(requestId,'forbidden','A Miso token with plans:write is required.',403);const {data,error:e}=await admin.rpc('claim_weekly_prep_job',{p_user:auth.userId});if(e)throw e;const job=Array.isArray(data)?data[0]??null:data;return json(requestId,job)}
  const prepCompleteMatch=path.match(/^\/prep-jobs\/([0-9a-f-]+)\/complete$/i);
  if(req.method==='POST'&&prepCompleteMatch){if(!auth.tokenId||!requireScope(auth,'plans:write'))return error(requestId,'forbidden','A Miso token with plans:write is required.',403);const parsed=weeklyPrepPlanSchema.safeParse(await req.json());if(!parsed.success)return json(requestId,{code:'ai_invalid_response',message:'Miso returned a prep plan that did not pass validation.',retryable:true,fields:parsed.error.flatten()},422);const {data:job}=await admin.from('weekly_prep_jobs').select('id,week_start,request').eq('id',prepCompleteMatch[1]).eq('user_id',auth.userId).eq('status','processing').maybeSingle();if(!job)return error(requestId,'not_found','Claimed prep request not found.',404);if(parsed.data.weekStart!==job.week_start)return error(requestId,'ai_invalid_response','Miso returned the wrong week.',422,true);const mathErrors=validatePrepMath(parsed.data,job.request);if(mathErrors.length)return json(requestId,{code:'ai_invalid_response',message:'Miso returned a prep plan with invalid combined quantities.',retryable:true,fields:{prep:mathErrors}},422);const {data,error:e}=await admin.from('weekly_prep_jobs').update({status:'ready',prep_plan:parsed.data,lease_expires_at:null,completed_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('id',job.id).select('*').single();if(e)throw e;await audit(auth,requestId,'complete_weekly_prep',job.id);return json(requestId,data)}
  const prepFailMatch=path.match(/^\/prep-jobs\/([0-9a-f-]+)\/fail$/i);
  if(req.method==='POST'&&prepFailMatch){if(!auth.tokenId||!requireScope(auth,'plans:write'))return error(requestId,'forbidden','A Miso token with plans:write is required.',403);const body=await req.json();await admin.from('weekly_prep_jobs').update({status:'failed',error_code:String(body.errorCode??'miso_failed').slice(0,120),lease_expires_at:null,updated_at:new Date().toISOString()}).eq('id',prepFailMatch[1]).eq('user_id',auth.userId);await audit(auth,requestId,'fail_weekly_prep',prepFailMatch[1]);return json(requestId,{failed:true})}
  if(req.method==='POST'&&(path==='/recipes/generate'||path==='/recipes/adapt')){if(!requireScope(auth,'recipes:write'))return error(requestId,'forbidden','Missing recipes:write scope.',403);if(Deno.env.get('AI_ENABLED')==='false')return error(requestId,'ai_disabled','AI features are disabled.',503,true);const body=await req.json();const provider=getAIProvider();const started=Date.now();try{const draft=path.endsWith('adapt')?await provider.adaptRecipe(body):await provider.generateRecipe(body);await admin.from('ai_requests').insert({user_id:auth.userId,feature:path.endsWith('adapt')?'adapt_recipe':'generate_recipe',provider:Deno.env.get('AI_PROVIDER')??'mock',model:Deno.env.get('AI_RECIPE_MODEL')??'mock',input_hash:await hash(JSON.stringify(body)),status:'success',estimated_cost:0});return json(requestId,{draft,durationMs:Date.now()-started,saved:false})}catch(e){await admin.from('ai_requests').insert({user_id:auth.userId,feature:'recipe',provider:Deno.env.get('AI_PROVIDER')??'mock',model:Deno.env.get('AI_RECIPE_MODEL')??'mock',input_hash:await hash(JSON.stringify(body)),status:'failed',error_code:String(e)});return error(requestId,'ai_invalid_response','The provider did not return a valid recipe. Your inputs were preserved.',502,true)}}
  if(req.method==='POST'&&path==='/feedback/interpret'){if(!requireScope(auth,'feedback:write'))return error(requestId,'forbidden','Missing feedback:write scope.',403);const body=await req.json();const proposal=await getAIProvider().interpretFeedback({notes:String(body.notes??''),tags:Array.isArray(body.tags)?body.tags:[]});return json(requestId,{proposal,accepted:false,originalPreserved:true})}
  if(req.method==='GET'&&path==='/groceries'){if(!requireScope(auth,'groceries:read'))return error(requestId,'forbidden','Missing groceries:read scope.',403);const {data}=await admin.from('grocery_lists').select('*,grocery_list_items(*)').eq('user_id',auth.userId).eq('status','active').maybeSingle();return json(requestId,data)}
  if(req.method==='GET'&&path==='/budget'){if(!requireScope(auth,'budget:read'))return error(requestId,'forbidden','Missing budget:read scope.',403);const start=new Date();start.setUTCDate(1);const {data:purchases}=await admin.from('grocery_purchases').select('price').eq('user_id',auth.userId).gte('purchased_at',start.toISOString());const {data:prefs}=await admin.from('user_preferences').select('monthly_grocery_budget').eq('user_id',auth.userId).single();const spent=(purchases??[]).reduce((n,p)=>n+Number(p.price),0);const target=Number(prefs?.monthly_grocery_budget??240);return json(requestId,{target,spent,remaining:target-spent})}
  if(req.method==='POST'&&path==='/integration-tokens'){if(!auth.scopes.includes('*'))return error(requestId,'forbidden','Only a signed-in user can create integration tokens.',403);const body=await req.json();const allowed=['inventory:read','inventory:write','plans:read','plans:write','recipes:read','recipes:write','cooking:write','feedback:write','groceries:read','groceries:write','budget:read'];const scopes=Array.isArray(body.scopes)?body.scopes.filter((scope:unknown)=>typeof scope==='string'&&allowed.includes(scope)):[];if(scopes.length===0)return error(requestId,'validation_error','Choose at least one valid scope.');const raw=`shua_${crypto.randomUUID().replaceAll('-','')}${crypto.randomUUID().replaceAll('-','')}`;const {data,error:tokenError}=await admin.from('integration_tokens').insert({user_id:auth.userId,name:String(body.name??'Miso cooking'),token_prefix:raw.slice(0,13),token_hash:await hash(raw),scopes}).select('id,name,token_prefix,scopes,created_at').single();if(tokenError)throw tokenError;return json(requestId,{...data,token:raw,displayedOnce:true},201)}
  return error(requestId,'not_found','API route not found.',404);
}catch(e){const details=e instanceof Error?e.message:JSON.stringify(e);console.error(JSON.stringify({requestId,level:'error',message:details}));return error(requestId,'internal_error','The request could not be completed.',500,true)}});
