import { createClient } from 'npm:@supabase/supabase-js@2.45.1';
import { getAIProvider } from '../_shared/ai.ts';

const cors={'access-control-allow-origin':Deno.env.get('APP_URL')??'http://localhost:5173','access-control-allow-headers':'authorization,content-type,idempotency-key,x-confirmation-token','access-control-allow-methods':'GET,POST,PATCH,DELETE,OPTIONS','x-content-type-options':'nosniff','referrer-policy':'no-referrer'};
const admin=createClient(Deno.env.get('SUPABASE_URL')!,Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!);
type Auth={userId:string;tokenId?:string;scopes:string[]};
const json=(requestId:string,data:unknown,status=200)=>new Response(JSON.stringify(status>=400?{requestId,error:data}:{requestId,data}),{status,headers:{...cors,'content-type':'application/json','x-request-id':requestId}});
const error=(id:string,code:string,message:string,status=400,retryable=false)=>json(id,{code,message,retryable},status);
const hash=async(value:string)=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(`${Deno.env.get('INTEGRATION_TOKEN_PEPPER')}:${value}`)))).map(x=>x.toString(16).padStart(2,'0')).join('');
async function authenticate(req:Request):Promise<Auth|null>{const bearer=req.headers.get('authorization')?.replace(/^Bearer /i,'');if(!bearer)return null;if(bearer.startsWith('shua_')||bearer.startsWith('mise_')){const tokenHash=await hash(bearer);const {data}=await admin.from('integration_tokens').select('id,user_id,scopes,expires_at,revoked_at').eq('token_hash',tokenHash).maybeSingle();if(!data||data.revoked_at||(data.expires_at&&new Date(data.expires_at)<new Date()))return null;await admin.from('integration_tokens').update({last_used_at:new Date().toISOString()}).eq('id',data.id);return {userId:data.user_id,tokenId:data.id,scopes:data.scopes}}const {data}=await admin.auth.getUser(bearer);return data.user?{userId:data.user.id,scopes:['*']}:null}
const requireScope=(auth:Auth,scope:string)=>auth.scopes.includes('*')||auth.scopes.includes(scope);
async function audit(auth:Auth,requestId:string,action:string,resource?:string){if(auth.tokenId)await admin.from('integration_audit_logs').insert({user_id:auth.userId,token_id:auth.tokenId,request_id:requestId,action,resource_id:resource,summary:{source:'integration'}})}
const unsignedDecimal=/^\d+(\.\d{1,4})?$/;
const signedDecimal=/^-?\d+(\.\d{1,4})?$/;
async function priorIdempotent(auth:Auth,key:string,requestHash:string){const {data}=await admin.from('idempotency_records').select('*').eq('user_id',auth.userId).eq('key',key).maybeSingle();if(!data)return null;if(data.request_hash!==requestHash)return {conflict:true as const};return {conflict:false as const,response:data.response_body}}
async function rememberIdempotent(auth:Auth,key:string,requestHash:string,responseBody:unknown,status=200){await admin.from('idempotency_records').insert({user_id:auth.userId,key,request_hash:requestHash,response_status:status,response_body:responseBody,expires_at:new Date(Date.now()+86400000).toISOString()})}

Deno.serve(async req=>{const requestId=req.headers.get('x-request-id')??crypto.randomUUID();if(req.method==='OPTIONS')return new Response(null,{status:204,headers:cors});try{const auth=await authenticate(req);if(!auth)return error(requestId,'unauthorized','A valid user session or integration token is required.',401);const url=new URL(req.url);const path=url.pathname.replace(/^.*\/api\/v1/,'');
  if(req.method==='GET'&&path==='/ingredients'){if(!requireScope(auth,'inventory:read'))return error(requestId,'forbidden','Missing inventory:read scope.',403);const query=url.searchParams.get('q')?.trim();let lookup=admin.from('ingredients').select('id,slug,name,category,default_unit,perishable,default_shelf_days').order('name').limit(100);if(query)lookup=lookup.ilike('name',`%${query.replaceAll('%','')}%`);const {data,error:e}=await lookup;if(e)throw e;return json(requestId,data)}
  if(req.method==='GET'&&path==='/inventory'){if(!requireScope(auth,'inventory:read'))return error(requestId,'forbidden','Missing inventory:read scope.',403);const {data,error:e}=await admin.from('inventory_items').select('*,ingredients(name,category),storage_locations(name)').eq('user_id',auth.userId).order('estimated_expiration_date',{ascending:true,nullsFirst:false});if(e)throw e;return json(requestId,data)}
  if(req.method==='GET'&&path==='/inventory/expiring'){if(!requireScope(auth,'inventory:read'))return error(requestId,'forbidden','Missing inventory:read scope.',403);const cutoff=new Date(Date.now()+3*86400000).toISOString().slice(0,10);const {data}=await admin.from('inventory_items').select('*,ingredients(name)').eq('user_id',auth.userId).lte('estimated_expiration_date',cutoff).gt('quantity',0);return json(requestId,data)}
  if(req.method==='POST'&&path==='/inventory'){
    if(!requireScope(auth,'inventory:write'))return error(requestId,'forbidden','Missing inventory:write scope.',403);
    const body=await req.json();const quantity=String(body.quantity??'');
    if(typeof body.ingredientId!=='string'||!unsignedDecimal.test(quantity)||Number(quantity)<=0||typeof body.unit!=='string')return error(requestId,'validation_error','Ingredient, positive quantity, and unit are required.');
    const key=req.headers.get('idempotency-key');if(!key)return error(requestId,'idempotency_required','Idempotency-Key is required.',400);
    const payloadHash=await hash(JSON.stringify(body));const prior=await priorIdempotent(auth,key,payloadHash);if(prior?.conflict)return error(requestId,'idempotency_conflict','This key was already used for a different request.',409);if(prior)return json(requestId,prior.response);
    const {data,error:e}=await admin.rpc('api_add_inventory_item',{p_user:auth.userId,p_ingredient:body.ingredientId,p_location:String(body.location??'Pantry'),p_quantity:quantity,p_unit:body.unit,p_expiration:body.expiresOn||null,p_idempotency:key});if(e)throw e;
    await rememberIdempotent(auth,key,payloadHash,data,201);await audit(auth,requestId,'add_inventory',data?.id);return json(requestId,data,201);
  }
  if(req.method==='POST'&&path==='/inventory/adjust'){
    if(!requireScope(auth,'inventory:write'))return error(requestId,'forbidden','Missing inventory:write scope.',403);
    const body=await req.json();const delta=String(body.quantityDelta??'');if(!signedDecimal.test(delta))return error(requestId,'validation_error','quantityDelta must be a fixed-precision decimal string.');
    const payloadHash=await hash(JSON.stringify(body));const suppliedConfirmation=req.headers.get('x-confirmation-token');
    if(Math.abs(Number(delta))>25&&!suppliedConfirmation){const token=`confirm_${crypto.randomUUID()}`;const expiresAt=new Date(Date.now()+10*60000).toISOString();const summary=`Adjust inventory by ${delta} ${body.unit}.`;await admin.from('confirmation_tokens').insert({user_id:auth.userId,token_hash:await hash(token),action:'inventory.adjust',payload_hash:payloadHash,summary,expires_at:expiresAt});return json(requestId,{code:'confirmation_required',message:summary,retryable:true,confirmationToken:token,summary,expiresAt},409)}
    if(Math.abs(Number(delta))>25&&suppliedConfirmation){const {data:confirmation}=await admin.from('confirmation_tokens').select('*').eq('user_id',auth.userId).eq('token_hash',await hash(suppliedConfirmation)).eq('action','inventory.adjust').eq('payload_hash',payloadHash).is('consumed_at',null).gt('expires_at',new Date().toISOString()).maybeSingle();if(!confirmation)return error(requestId,'invalid_confirmation','Confirmation is invalid, expired, consumed, or belongs to another payload.',409);await admin.from('confirmation_tokens').update({consumed_at:new Date().toISOString()}).eq('id',confirmation.id)}
    const key=req.headers.get('idempotency-key');if(!key)return error(requestId,'idempotency_required','Idempotency-Key is required.',400);const prior=await priorIdempotent(auth,key,payloadHash);if(prior?.conflict)return error(requestId,'idempotency_conflict','This key was already used for a different request.',409);if(prior)return json(requestId,prior.response);
    const {data,error:e}=await admin.rpc('api_adjust_inventory_quantity',{p_user:auth.userId,p_item:body.inventoryItemId,p_delta:delta,p_reason:String(body.reason??'manual'),p_idempotency:key});if(e?.message?.includes('inventory_item_not_found'))return error(requestId,'not_found','Inventory item not found.',404);if(e)throw e;
    await rememberIdempotent(auth,key,payloadHash,data);await audit(auth,requestId,'adjust_inventory',body.inventoryItemId);return json(requestId,data);
  }
  if(req.method==='GET'&&path==='/plans/current'){if(!requireScope(auth,'plans:read'))return error(requestId,'forbidden','Missing plans:read scope.',403);const today=new Date();const day=(today.getUTCDay()+6)%7;const monday=new Date(today);monday.setUTCDate(today.getUTCDate()-day);const {data}=await admin.from('weekly_plans').select('*,planned_meals(*,recipe_versions(*,recipes(*)))').eq('user_id',auth.userId).eq('week_start',monday.toISOString().slice(0,10)).maybeSingle();return json(requestId,data)}
  if(req.method==='GET'&&path==='/recipes'){if(!requireScope(auth,'recipes:read'))return error(requestId,'forbidden','Missing recipes:read scope.',403);const {data}=await admin.from('recipes').select('*,recipe_versions(*,recipe_ingredients(*),recipe_steps(*))').or(`user_id.eq.${auth.userId},user_id.is.null`).limit(100);return json(requestId,data)}
  if(req.method==='POST'&&(path==='/recipes/generate'||path==='/recipes/adapt')){if(!requireScope(auth,'recipes:write'))return error(requestId,'forbidden','Missing recipes:write scope.',403);if(Deno.env.get('AI_ENABLED')==='false')return error(requestId,'ai_disabled','AI features are disabled.',503,true);const body=await req.json();const provider=getAIProvider();const started=Date.now();try{const draft=path.endsWith('adapt')?await provider.adaptRecipe(body):await provider.generateRecipe(body);await admin.from('ai_requests').insert({user_id:auth.userId,feature:path.endsWith('adapt')?'adapt_recipe':'generate_recipe',provider:Deno.env.get('AI_PROVIDER')??'mock',model:Deno.env.get('AI_RECIPE_MODEL')??'mock',input_hash:await hash(JSON.stringify(body)),status:'success',estimated_cost:0});return json(requestId,{draft,durationMs:Date.now()-started,saved:false})}catch(e){await admin.from('ai_requests').insert({user_id:auth.userId,feature:'recipe',provider:Deno.env.get('AI_PROVIDER')??'mock',model:Deno.env.get('AI_RECIPE_MODEL')??'mock',input_hash:await hash(JSON.stringify(body)),status:'failed',error_code:String(e)});return error(requestId,'ai_invalid_response','The provider did not return a valid recipe. Your inputs were preserved.',502,true)}}
  if(req.method==='POST'&&path==='/feedback/interpret'){if(!requireScope(auth,'feedback:write'))return error(requestId,'forbidden','Missing feedback:write scope.',403);const body=await req.json();const proposal=await getAIProvider().interpretFeedback({notes:String(body.notes??''),tags:Array.isArray(body.tags)?body.tags:[]});return json(requestId,{proposal,accepted:false,originalPreserved:true})}
  if(req.method==='GET'&&path==='/groceries'){if(!requireScope(auth,'groceries:read'))return error(requestId,'forbidden','Missing groceries:read scope.',403);const {data}=await admin.from('grocery_lists').select('*,grocery_list_items(*)').eq('user_id',auth.userId).eq('status','active').maybeSingle();return json(requestId,data)}
  if(req.method==='GET'&&path==='/budget'){if(!requireScope(auth,'budget:read'))return error(requestId,'forbidden','Missing budget:read scope.',403);const start=new Date();start.setUTCDate(1);const {data:purchases}=await admin.from('grocery_purchases').select('price').eq('user_id',auth.userId).gte('purchased_at',start.toISOString());const {data:prefs}=await admin.from('user_preferences').select('monthly_grocery_budget').eq('user_id',auth.userId).single();const spent=(purchases??[]).reduce((n,p)=>n+Number(p.price),0);const target=Number(prefs?.monthly_grocery_budget??240);return json(requestId,{target,spent,remaining:target-spent})}
  if(req.method==='POST'&&path==='/integration-tokens'){if(!auth.scopes.includes('*'))return error(requestId,'forbidden','Only a signed-in user can create integration tokens.',403);const body=await req.json();const allowed=['inventory:read','inventory:write','plans:read','plans:write','recipes:read','recipes:write','cooking:write','feedback:write','groceries:read','groceries:write','budget:read'];const scopes=Array.isArray(body.scopes)?body.scopes.filter((scope:unknown)=>typeof scope==='string'&&allowed.includes(scope)):[];if(scopes.length===0)return error(requestId,'validation_error','Choose at least one valid scope.');const raw=`shua_${crypto.randomUUID().replaceAll('-','')}${crypto.randomUUID().replaceAll('-','')}`;const {data,error:tokenError}=await admin.from('integration_tokens').insert({user_id:auth.userId,name:String(body.name??'Miso cooking'),token_prefix:raw.slice(0,13),token_hash:await hash(raw),scopes}).select('id,name,token_prefix,scopes,created_at').single();if(tokenError)throw tokenError;return json(requestId,{...data,token:raw,displayedOnce:true},201)}
  return error(requestId,'not_found','API route not found.',404);
}catch(e){const details=e instanceof Error?e.message:JSON.stringify(e);console.error(JSON.stringify({requestId,level:'error',message:details}));return error(requestId,'internal_error','The request could not be completed.',500,true)}});
