create extension if not exists pgcrypto;

create type public.inventory_transaction_kind as enum ('starting','purchase','consumption','manual','discarded','expired','undo');
create type public.meal_status as enum ('planned','completed','skipped','eating_out','flexible');
create type public.integration_scope as enum ('inventory:read','inventory:write','plans:read','plans:write','recipes:read','recipes:write','cooking:write','feedback:write','groceries:read','groceries:write','budget:read');

create table public.profiles (id uuid primary key references auth.users on delete cascade, display_name text not null default 'Cook', timezone text not null default 'America/Chicago', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.user_preferences (user_id uuid primary key references public.profiles on delete cascade, monthly_grocery_budget numeric(12,2) not null default 240 check(monthly_grocery_budget>=0), staple_ingredient_ids uuid[] not null default '{}', preferred_proteins text[] not null default array['chicken breast','salmon','ground beef','eggs','white fish'], exclusions text[] not null default '{}', recommendation_weights jsonb not null default '{"preference":0.16,"availability":0.17,"expiration":0.12,"cost":0.10,"budget":0.08,"variety":0.10,"time":0.07,"cleanup":0.05,"leftovers":0.07,"confidence":0.05,"exploration":0.03}', exploration_mix jsonb not null default '{"familiar":0.6,"variation":0.25,"exploratory":0.15}', settings jsonb not null default '{}', updated_at timestamptz not null default now());
create table public.preference_signals (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.profiles on delete cascade, kind text not null, value text not null, sentiment smallint not null check(sentiment between -1 and 1), confidence numeric(4,3) not null check(confidence between 0 and 1), source_feedback_id uuid, accepted_at timestamptz, created_at timestamptz not null default now());

create table public.ingredients (id uuid primary key default gen_random_uuid(), slug text not null unique, name text not null, category text not null, default_unit text not null, perishable boolean not null default false, default_shelf_days integer, created_at timestamptz not null default now());
create table public.ingredient_aliases (id uuid primary key default gen_random_uuid(), ingredient_id uuid not null references public.ingredients on delete cascade, alias text not null unique);
create table public.ingredient_package_defaults (id uuid primary key default gen_random_uuid(), ingredient_id uuid not null references public.ingredients on delete cascade, package_unit text not null, contained_quantity numeric(14,4) not null check(contained_quantity>0), contained_unit text not null, estimated_price numeric(12,2), unique(ingredient_id,package_unit,contained_quantity,contained_unit));
create table public.storage_locations (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.profiles on delete cascade, name text not null, unique(user_id,name));
create table public.inventory_items (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.profiles on delete cascade, ingredient_id uuid not null references public.ingredients, storage_location_id uuid references public.storage_locations on delete set null, quantity numeric(14,4) not null default 0 check(quantity>=0), reserved_quantity numeric(14,4) not null default 0 check(reserved_quantity>=0), unit text not null, confidence numeric(4,3) not null default .5 check(confidence between 0 and 1), source text not null default 'manual', purchase_date date, estimated_expiration_date date, last_confirmed_at timestamptz, version integer not null default 1, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(user_id,ingredient_id,storage_location_id,unit), check(reserved_quantity>=0));
create table public.inventory_transactions (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.profiles on delete cascade, inventory_item_id uuid not null references public.inventory_items, kind public.inventory_transaction_kind not null, quantity_delta numeric(14,4) not null, unit text not null, reason text, related_transaction_id uuid references public.inventory_transactions, planned_meal_id uuid, idempotency_key text, created_at timestamptz not null default now(), unique(user_id,idempotency_key));
create table public.inventory_confirmations (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.profiles on delete cascade, inventory_item_id uuid not null references public.inventory_items on delete cascade, expected_quantity numeric(14,4) not null, confirmed_quantity numeric(14,4), response text not null, confidence numeric(4,3) not null, confirmed_at timestamptz not null default now());

create table public.recipes (id uuid primary key default gen_random_uuid(), user_id uuid references public.profiles on delete cascade, title text not null, description text not null default '', primary_photo_path text, created_at timestamptz not null default now(), archived_at timestamptz);
create table public.recipe_versions (id uuid primary key default gen_random_uuid(), recipe_id uuid not null references public.recipes on delete cascade, version integer not null, parent_version_id uuid references public.recipe_versions, servings numeric(8,2) not null check(servings>0), prep_minutes integer not null check(prep_minutes>=0), cook_minutes integer not null check(cook_minutes>=0), difficulty text not null, estimated_cost numeric(12,2), cuisine text, protein text, cleanup smallint check(cleanup between 1 and 5), leftover_quality smallint check(leftover_quality between 1 and 5), leftover_days integer, reheating text, safety_notes text[] not null default '{}', equipment text[] not null default '{}', substitutions text[] not null default '{}', version_notes text, created_at timestamptz not null default now(), unique(recipe_id,version));
create table public.recipe_ingredients (id uuid primary key default gen_random_uuid(), recipe_version_id uuid not null references public.recipe_versions on delete cascade, ingredient_id uuid references public.ingredients, unresolved_name text, quantity numeric(14,4) not null check(quantity>0), unit text not null, optional boolean not null default false, sort_order integer not null, check(ingredient_id is not null or unresolved_name is not null));
create table public.recipe_steps (id uuid primary key default gen_random_uuid(), recipe_version_id uuid not null references public.recipe_versions on delete cascade, step_number integer not null, instruction text not null, ingredient_refs uuid[] not null default '{}', timer_seconds integer, unique(recipe_version_id,step_number));
create table public.recipe_tags (recipe_id uuid not null references public.recipes on delete cascade, tag text not null, primary key(recipe_id,tag));
create table public.recipe_photos (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.profiles on delete cascade, recipe_id uuid not null references public.recipes on delete cascade, storage_path text not null, alt_text text not null, is_primary boolean not null default false, created_at timestamptz not null default now());

create table public.weekly_plans (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.profiles on delete cascade, week_start date not null, status text not null default 'draft', version integer not null default 1, committed_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(user_id,week_start));
create table public.planned_meals (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.profiles on delete cascade, weekly_plan_id uuid not null references public.weekly_plans on delete cascade, recipe_version_id uuid references public.recipe_versions, meal_date date not null, slot text not null check(slot in ('lunch','dinner')), servings numeric(8,2) not null check(servings>0), status public.meal_status not null default 'planned', title text not null, version integer not null default 1, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(weekly_plan_id,meal_date,slot));
alter table public.inventory_transactions add constraint inventory_transactions_planned_meal_fk foreign key(planned_meal_id) references public.planned_meals on delete set null;
create table public.ingredient_reservations (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.profiles on delete cascade, planned_meal_id uuid not null references public.planned_meals on delete cascade, inventory_item_id uuid not null references public.inventory_items, quantity numeric(14,4) not null check(quantity>0), unit text not null, active boolean not null default true, created_at timestamptz not null default now());
create table public.meal_leftovers (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.profiles on delete cascade, source_planned_meal_id uuid not null references public.planned_meals on delete cascade, assigned_planned_meal_id uuid references public.planned_meals on delete set null, servings numeric(8,2) not null check(servings>0), use_by date not null, reheating text, status text not null default 'available');
create table public.cooking_sessions (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.profiles on delete cascade, planned_meal_id uuid not null references public.planned_meals on delete cascade, current_step integer not null default 0, state jsonb not null default '{}', started_at timestamptz not null default now(), completed_at timestamptz);
create table public.meal_logs (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.profiles on delete cascade, planned_meal_id uuid references public.planned_meals on delete set null, recipe_version_id uuid references public.recipe_versions, servings_produced numeric(8,2), servings_eaten numeric(8,2), completed_at timestamptz not null default now());
create table public.meal_feedback (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.profiles on delete cascade, meal_log_id uuid not null references public.meal_logs on delete cascade, overall_rating smallint not null check(overall_rating between 1 and 10), would_make_again boolean not null, portion text, leftover_rating smallint check(leftover_rating between 1 and 5), effort smallint check(effort between 1 and 5), cleanup smallint check(cleanup between 1 and 5), tags text[] not null default '{}', original_notes text, interpreted jsonb, interpretation_accepted_at timestamptz, created_at timestamptz not null default now());
alter table public.preference_signals add constraint preference_signals_feedback_fk foreign key(source_feedback_id) references public.meal_feedback on delete set null;
create table public.feedback_signals (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.profiles on delete cascade, feedback_id uuid not null references public.meal_feedback on delete cascade, signal_type text not null, value text not null, sentiment smallint not null check(sentiment between -1 and 1), accepted boolean not null default false);

create table public.grocery_lists (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.profiles on delete cascade, weekly_plan_id uuid references public.weekly_plans on delete cascade, status text not null default 'active', expected_checkout numeric(12,2) not null default 0, estimated_consumed numeric(12,2) not null default 0, created_at timestamptz not null default now());
create table public.grocery_list_items (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.profiles on delete cascade, grocery_list_id uuid not null references public.grocery_lists on delete cascade, ingredient_id uuid references public.ingredients, manual_name text, required_quantity numeric(14,4) not null check(required_quantity>0), unit text not null, package_quantity numeric(14,4), estimated_price numeric(12,2), store_section text, checked boolean not null default false, purchased boolean not null default false, recipe_ids uuid[] not null default '{}', check(ingredient_id is not null or manual_name is not null));
create table public.grocery_purchases (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.profiles on delete cascade, grocery_item_id uuid references public.grocery_list_items on delete set null, ingredient_id uuid references public.ingredients, quantity numeric(14,4) not null, unit text not null, price numeric(12,2) not null, store text, purchased_at timestamptz not null default now());
create table public.price_history (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.profiles on delete cascade, ingredient_id uuid not null references public.ingredients, package_quantity numeric(14,4), unit text not null, price numeric(12,2) not null, observed_at timestamptz not null default now());
create table public.budget_periods (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.profiles on delete cascade, starts_on date not null, ends_on date not null, target numeric(12,2) not null, unique(user_id,starts_on), check(ends_on>=starts_on));
create table public.receipt_uploads (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.profiles on delete cascade, storage_path text, store text, purchase_date date, status text not null default 'draft', retained boolean not null default false, created_at timestamptz not null default now());
create table public.receipt_items (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.profiles on delete cascade, receipt_upload_id uuid not null references public.receipt_uploads on delete cascade, raw_text text not null, ingredient_id uuid references public.ingredients, quantity numeric(14,4), unit text, price numeric(12,2), confidence numeric(4,3), accepted boolean);

create table public.ai_requests (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.profiles on delete cascade, feature text not null, provider text not null, model text not null, input_hash text not null, status text not null, input_tokens integer, output_tokens integer, estimated_cost numeric(12,5), error_code text, created_at timestamptz not null default now());
create table public.integration_tokens (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.profiles on delete cascade, name text not null, token_prefix text not null, token_hash text not null unique, scopes public.integration_scope[] not null, expires_at timestamptz, last_used_at timestamptz, revoked_at timestamptz, created_at timestamptz not null default now());
create table public.integration_audit_logs (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.profiles on delete cascade, token_id uuid references public.integration_tokens on delete set null, request_id text not null, action text not null, resource_type text, resource_id text, summary jsonb not null default '{}', ip_hash text, created_at timestamptz not null default now());
create table public.idempotency_records (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.profiles on delete cascade, key text not null, request_hash text not null, response_status integer not null, response_body jsonb not null, expires_at timestamptz not null, created_at timestamptz not null default now(), unique(user_id,key));
create table public.confirmation_tokens (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.profiles on delete cascade, token_hash text not null unique, action text not null, payload_hash text not null, summary text not null, expires_at timestamptz not null, consumed_at timestamptz, created_at timestamptz not null default now());
create table public.integration_rate_limits (token_id uuid not null references public.integration_tokens on delete cascade, window_start timestamptz not null, request_count integer not null default 0, primary key(token_id,window_start));

create index inventory_items_user_expiration_idx on public.inventory_items(user_id,estimated_expiration_date);
create index inventory_transactions_item_created_idx on public.inventory_transactions(inventory_item_id,created_at desc);
create index planned_meals_user_date_idx on public.planned_meals(user_id,meal_date);
create index reservations_active_idx on public.ingredient_reservations(inventory_item_id) where active;
create index recipes_user_created_idx on public.recipes(user_id,created_at desc);
create index audit_user_created_idx on public.integration_audit_logs(user_id,created_at desc);
create index ai_requests_user_created_idx on public.ai_requests(user_id,created_at desc);

create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$ begin insert into public.profiles(id,display_name) values(new.id,coalesce(new.raw_user_meta_data->>'display_name',split_part(new.email,'@',1),'Cook')) on conflict do nothing; insert into public.user_preferences(user_id) values(new.id) on conflict do nothing; return new; end $$;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();

create or replace function public.reserve_planned_meal(p_user uuid,p_plan uuid,p_recipe_version uuid,p_date date,p_slot text,p_servings numeric,p_title text)
returns uuid language plpgsql security definer set search_path=public as $$
declare v_meal uuid; v_existing uuid; v_inventory_item uuid; v_recipe_servings numeric; r record; v_available numeric; v_hold numeric;
begin
  if auth.uid() is distinct from p_user then raise exception 'forbidden'; end if;
  select servings into v_recipe_servings from recipe_versions where id=p_recipe_version;
  if v_recipe_servings is null then raise exception 'recipe_not_found'; end if;
  select id into v_existing from planned_meals where weekly_plan_id=p_plan and meal_date=p_date and slot=p_slot for update;
  if v_existing is not null then perform public.release_meal_reservations(p_user,v_existing); delete from planned_meals where id=v_existing; end if;
  insert into planned_meals(user_id,weekly_plan_id,recipe_version_id,meal_date,slot,servings,title) values(p_user,p_plan,p_recipe_version,p_date,p_slot,p_servings,p_title) returning id into v_meal;
  for r in select ri.*, (ri.quantity*p_servings/v_recipe_servings) needed from recipe_ingredients ri where ri.recipe_version_id=p_recipe_version and not ri.optional and ri.ingredient_id is not null loop
    v_inventory_item:=null; select id, greatest(0,quantity-reserved_quantity) into v_inventory_item,v_available from inventory_items where user_id=p_user and ingredient_id=r.ingredient_id and unit=r.unit order by quantity-reserved_quantity desc limit 1 for update;
    if v_inventory_item is not null then v_hold:=least(v_available,r.needed); if v_hold>0 then insert into ingredient_reservations(user_id,planned_meal_id,inventory_item_id,quantity,unit) values(p_user,v_meal,v_inventory_item,v_hold,r.unit); update inventory_items set reserved_quantity=reserved_quantity+v_hold,version=version+1,updated_at=now() where id=v_inventory_item; end if; end if;
  end loop;
  return v_meal;
end $$;

create or replace function public.release_meal_reservations(p_user uuid,p_meal uuid)
returns void language plpgsql security definer set search_path=public as $$
declare r record; begin if auth.uid() is distinct from p_user then raise exception 'forbidden'; end if;
for r in select * from ingredient_reservations where user_id=p_user and planned_meal_id=p_meal and active for update loop update inventory_items set reserved_quantity=greatest(0,reserved_quantity-r.quantity),version=version+1,updated_at=now() where id=r.inventory_item_id; update ingredient_reservations set active=false where id=r.id; end loop; end $$;

create or replace function public.complete_planned_meal(p_user uuid,p_meal uuid,p_actual jsonb,p_idempotency text)
returns uuid language plpgsql security definer set search_path=public as $$
declare v_log uuid; r record; v_delta numeric; begin if auth.uid() is distinct from p_user then raise exception 'forbidden'; end if;
if exists(select 1 from inventory_transactions where user_id=p_user and left(idempotency_key,length(p_idempotency))=p_idempotency) then select id into v_log from meal_logs where planned_meal_id=p_meal order by completed_at desc limit 1; return v_log; end if;
for r in select * from ingredient_reservations where user_id=p_user and planned_meal_id=p_meal and active for update loop v_delta:=coalesce((p_actual->>r.inventory_item_id::text)::numeric,r.quantity); update inventory_items set quantity=greatest(0,quantity-v_delta),reserved_quantity=greatest(0,reserved_quantity-r.quantity),version=version+1,updated_at=now() where id=r.inventory_item_id; insert into inventory_transactions(user_id,inventory_item_id,kind,quantity_delta,unit,planned_meal_id,idempotency_key) values(p_user,r.inventory_item_id,'consumption',-v_delta,r.unit,p_meal,p_idempotency||':'||r.id); update ingredient_reservations set active=false where id=r.id; end loop;
update planned_meals set status='completed',version=version+1,updated_at=now() where id=p_meal and user_id=p_user; insert into meal_logs(user_id,planned_meal_id,recipe_version_id) select p_user,id,recipe_version_id from planned_meals where id=p_meal returning id into v_log; return v_log; end $$;

alter table public.ingredients enable row level security; alter table public.ingredient_aliases enable row level security; alter table public.ingredient_package_defaults enable row level security;
create policy "authenticated ingredients read" on public.ingredients for select to authenticated using(true);
create policy "authenticated aliases read" on public.ingredient_aliases for select to authenticated using(true);
create policy "authenticated packages read" on public.ingredient_package_defaults for select to authenticated using(true);

alter table public.profiles enable row level security;
create policy "profile owner" on public.profiles for all to authenticated using(id=auth.uid()) with check(id=auth.uid());
do $$ declare t text; begin foreach t in array array['user_preferences','preference_signals','storage_locations','inventory_items','inventory_transactions','inventory_confirmations','recipes','recipe_photos','weekly_plans','planned_meals','ingredient_reservations','meal_leftovers','cooking_sessions','meal_logs','meal_feedback','feedback_signals','grocery_lists','grocery_list_items','grocery_purchases','price_history','budget_periods','receipt_uploads','receipt_items','ai_requests','integration_tokens','integration_audit_logs','idempotency_records','confirmation_tokens'] loop execute format('alter table public.%I enable row level security',t); execute format('create policy "owner all" on public.%I for all to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid())',t); end loop; end $$;
alter table public.recipe_versions enable row level security; alter table public.recipe_ingredients enable row level security; alter table public.recipe_steps enable row level security; alter table public.recipe_tags enable row level security;
create policy "recipe version access" on public.recipe_versions for select to authenticated using(exists(select 1 from public.recipes r where r.id=recipe_id and (r.user_id=auth.uid() or r.user_id is null)));
create policy "recipe ingredient access" on public.recipe_ingredients for select to authenticated using(exists(select 1 from public.recipe_versions v join public.recipes r on r.id=v.recipe_id where v.id=recipe_version_id and (r.user_id=auth.uid() or r.user_id is null)));
create policy "recipe step access" on public.recipe_steps for select to authenticated using(exists(select 1 from public.recipe_versions v join public.recipes r on r.id=v.recipe_id where v.id=recipe_version_id and (r.user_id=auth.uid() or r.user_id is null)));
create policy "recipe tag access" on public.recipe_tags for select to authenticated using(exists(select 1 from public.recipes r where r.id=recipe_id and (r.user_id=auth.uid() or r.user_id is null)));
create policy "global recipe read" on public.recipes for select to authenticated using(user_id is null or user_id=auth.uid());

insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values ('recipe-photos','recipe-photos',false,5242880,array['image/jpeg','image/png','image/webp']),('meal-photos','meal-photos',false,5242880,array['image/jpeg','image/png','image/webp']),('receipts','receipts',false,10485760,array['image/jpeg','image/png','image/webp']) on conflict do nothing;
create policy "user image read" on storage.objects for select to authenticated using(bucket_id in ('recipe-photos','meal-photos','receipts') and (storage.foldername(name))[1]=auth.uid()::text);
create policy "user image insert" on storage.objects for insert to authenticated with check(bucket_id in ('recipe-photos','meal-photos','receipts') and (storage.foldername(name))[1]=auth.uid()::text);
create policy "user image delete" on storage.objects for delete to authenticated using(bucket_id in ('recipe-photos','meal-photos','receipts') and (storage.foldername(name))[1]=auth.uid()::text);

grant usage on schema public to authenticated;
grant select,insert,update,delete on all tables in schema public to authenticated;
grant usage,select on all sequences in schema public to authenticated;
grant execute on all functions in schema public to authenticated;
grant usage on schema public to service_role;
grant all privileges on all tables in schema public to service_role;
grant usage,select on all sequences in schema public to service_role;
grant execute on all functions in schema public to service_role;
revoke all on all tables in schema public from anon;
