alter table public.recipes
  add column if not exists primary_photo_url text,
  add column if not exists photo_attribution jsonb;

create table public.recipe_generation_jobs (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles on delete cascade,
  status text not null default 'queued' check(status in ('queued','processing','ready','failed','saved','discarded')),
  request jsonb not null,
  recipe_draft jsonb,
  photo_candidates jsonb not null default '[]',
  error_code text,
  attempt_count integer not null default 0 check(attempt_count between 0 and 5),
  lease_expires_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  completed_at timestamptz
);

create index recipe_generation_jobs_user_created_idx on public.recipe_generation_jobs(user_id,created_at desc);
create index recipe_generation_jobs_claim_idx on public.recipe_generation_jobs(status,created_at) where status in ('queued','processing');

alter table public.recipe_generation_jobs enable row level security;
create policy "recipe job owner read" on public.recipe_generation_jobs for select to authenticated
  using(user_id=auth.uid());

create or replace function public.claim_recipe_generation_job(p_user uuid)
returns setof public.recipe_generation_jobs
language plpgsql security definer set search_path=public as $$
declare v_id uuid;
begin
  select id into v_id
  from public.recipe_generation_jobs
  where user_id=p_user
    and attempt_count<5
    and (status='queued' or (status='processing' and lease_expires_at<now()))
  order by created_at
  for update skip locked
  limit 1;
  if v_id is null then return; end if;
  return query
    update public.recipe_generation_jobs
    set status='processing',attempt_count=attempt_count+1,lease_expires_at=now()+interval '5 minutes',updated_at=now(),error_code=null
    where id=v_id
    returning *;
end $$;

create or replace function public.save_generated_recipe(p_user uuid,p_job uuid,p_recipe jsonb,p_photo jsonb default null)
returns jsonb
language plpgsql security definer set search_path=public as $$
declare
  v_recipe_id uuid;
  v_version_id uuid;
  v_ingredient uuid;
  v_item jsonb;
  v_step text;
  v_tag text;
  v_sort integer:=0;
  v_job public.recipe_generation_jobs%rowtype;
  v_photo jsonb;
begin
  select * into v_job from public.recipe_generation_jobs where id=p_job and user_id=p_user for update;
  if v_job.id is null then raise exception 'recipe_job_not_found'; end if;
  if v_job.status<>'ready' then raise exception 'recipe_job_not_ready'; end if;
  if p_photo is not null then
    select c into v_photo from jsonb_array_elements(v_job.photo_candidates) c where c->>'id'=p_photo->>'id' limit 1;
    if v_photo is null then raise exception 'invalid_photo_selection'; end if;
  end if;

  insert into public.recipes(user_id,title,description,primary_photo_url,photo_attribution)
  values(p_user,p_recipe->>'title',coalesce(p_recipe->>'description',''),v_photo->>'imageUrl',v_photo)
  returning id into v_recipe_id;

  insert into public.recipe_versions(recipe_id,version,servings,prep_minutes,cook_minutes,difficulty,estimated_cost,cuisine,protein,cleanup,leftover_quality,leftover_days,reheating,safety_notes,equipment,substitutions,version_notes)
  values(v_recipe_id,1,(p_recipe->>'servings')::numeric,(p_recipe->>'prepMinutes')::integer,(p_recipe->>'cookMinutes')::integer,p_recipe->>'difficulty',(p_recipe->>'estimatedCost')::numeric,p_recipe->>'cuisine',p_recipe->>'protein',coalesce((p_recipe->>'cleanup')::integer,2),coalesce((p_recipe->>'leftoverQuality')::integer,3),coalesce((p_recipe->>'leftoverDays')::integer,3),coalesce(p_recipe->>'reheating',p_recipe->>'leftoverGuidance'),array(select jsonb_array_elements_text(coalesce(p_recipe->'safetyNotes','[]'))),array(select jsonb_array_elements_text(coalesce(p_recipe->'equipment','[]'))),array(select jsonb_array_elements_text(coalesce(p_recipe->'substitutions','[]'))),'Generated by Miso and approved in Shua')
  returning id into v_version_id;

  for v_item in select * from jsonb_array_elements(p_recipe->'ingredients') loop
    v_sort:=v_sort+1; v_ingredient:=null;
    begin v_ingredient:=nullif(v_item->>'ingredientId','')::uuid; exception when invalid_text_representation then v_ingredient:=null; end;
    if v_ingredient is not null and not exists(select 1 from public.ingredients where id=v_ingredient) then v_ingredient:=null; end if;
    if v_ingredient is null then
      select i.id into v_ingredient from public.ingredients i left join public.ingredient_aliases a on a.ingredient_id=i.id where lower(i.name)=lower(v_item->>'name') or lower(a.alias)=lower(v_item->>'name') limit 1;
    end if;
    insert into public.recipe_ingredients(recipe_version_id,ingredient_id,unresolved_name,quantity,unit,optional,sort_order)
    values(v_version_id,v_ingredient,case when v_ingredient is null then v_item->>'name' end,(v_item->>'quantity')::numeric,v_item->>'unit',coalesce((v_item->>'optional')::boolean,false),v_sort);
  end loop;

  v_sort:=0;
  for v_step in select * from jsonb_array_elements_text(p_recipe->'steps') loop
    v_sort:=v_sort+1; insert into public.recipe_steps(recipe_version_id,step_number,instruction) values(v_version_id,v_sort,v_step);
  end loop;
  for v_tag in select * from jsonb_array_elements_text(coalesce(p_recipe->'tags','[]')) loop
    insert into public.recipe_tags(recipe_id,tag) values(v_recipe_id,left(v_tag,80)) on conflict do nothing;
  end loop;
  update public.recipe_generation_jobs set status='saved',updated_at=now() where id=p_job;
  return jsonb_build_object('recipeId',v_recipe_id,'recipeVersionId',v_version_id);
end $$;

grant select on public.recipe_generation_jobs to authenticated;
grant all privileges on public.recipe_generation_jobs to service_role;
revoke all on function public.claim_recipe_generation_job(uuid) from public,anon,authenticated;
revoke all on function public.save_generated_recipe(uuid,uuid,jsonb,jsonb) from public,anon,authenticated;
grant execute on function public.claim_recipe_generation_job(uuid) to service_role;
grant execute on function public.save_generated_recipe(uuid,uuid,jsonb,jsonb) to service_role;
