import { AlertTriangle, ArrowRight, CalendarCheck, CookingPot, PackageCheck, Sparkles } from 'lucide-react';
import { Link } from 'react-router-dom';
import { budgetSummary, projected } from '@mise/domain';
import { useStore } from '../store';
import { RecipeCard } from '../components/UI';

export function Dashboard(){const s=useStore();const today=new Date().toISOString().slice(0,10);const tonight=s.meals.find(m=>m.date===today&&m.status==='planned')??s.meals.find(m=>m.status==='planned');const recipe=s.recipes.find(r=>r.id===tonight?.recipeId);const upcoming=s.grocery.reduce((n,g)=>n+Math.max(1,Number(g.quantity)*1.25),0).toFixed(2);const budget=budgetSummary(s.monthlySpent,upcoming,s.settings.monthlyBudget);const expiring=s.inventory.filter(i=>i.expiresOn&&new Date(i.expiresOn).getTime()-Date.now()<3*86400000&&Number(projected(i))>0);return <>
  <div className="mb-9 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="eyebrow">Monday, in your kitchen</p><h1 className="mt-2 text-4xl sm:text-5xl">Good evening, Josh.</h1><p className="mt-3 text-sm text-ink/55">Everything you need to make the week feel lighter.</p></div><Link to="/plan" className="btn-primary"><CalendarCheck size={17}/>Continue planning</Link></div>
  <section className="grid gap-5 lg:grid-cols-[1.4fr_.8fr]">
    <div className="card overflow-hidden p-0">{recipe&&tonight?<div className="grid min-h-[310px] sm:grid-cols-[1fr_.8fr]"><div className="flex flex-col p-7"><p className="eyebrow">Tonight’s dinner</p><h2 className="mt-4 text-3xl">{recipe.title}</h2><p className="mt-3 text-sm leading-6 text-ink/60">{recipe.description}</p><div className="mt-5 flex gap-2"><span className="pill">{recipe.prepMinutes+recipe.cookMinutes} min</span><span className="pill">{tonight.servings} servings</span></div><div className="mt-auto pt-7"><Link to={`/cook/${tonight.id}`} className="btn-primary"><CookingPot size={17}/>Start cooking</Link></div></div><div className="grid place-items-center bg-gradient-to-br from-[#d1aa6e] to-[#7d5933] text-8xl" aria-label="Tasteful chicken meal placeholder">🍲</div></div>:<div className="grid min-h-[310px] place-items-center p-10 text-center"><div><p className="eyebrow">Tonight is open</p><h2 className="mt-3 text-3xl">What sounds good?</h2><p className="mt-2 text-sm text-ink/55">Plan your first meal and projected inventory will update immediately.</p><Link to="/plan" className="btn-primary mt-6">Choose a meal<ArrowRight size={16}/></Link></div></div>}</div>
    <div className="card flex flex-col bg-herb-700 text-white"><p className="text-xs font-semibold uppercase tracking-[.18em] text-white/60">Monthly grocery budget</p><div className="mt-5 flex items-end gap-2"><span className="font-display text-5xl">${budget.remaining}</span><span className="mb-1 text-sm text-white/60">remaining</span></div><div className="mt-6 h-2 overflow-hidden rounded-full bg-white/15"><div className="h-full rounded-full bg-gold" style={{width:`${Math.min(100,(Number(s.monthlySpent)+Number(upcoming))/Math.max(1,Number(s.settings.monthlyBudget))*100)}%`}}/></div><div className="mt-3 flex justify-between text-xs text-white/60"><span>${s.monthlySpent} spent</span><span>${upcoming} expected of ${s.settings.monthlyBudget}</span></div><Link to="/groceries" className="mt-auto flex items-center gap-2 pt-8 text-sm font-semibold">View grocery plan <ArrowRight size={15}/></Link></div>
  </section>
  <section className="mt-5 grid gap-5 md:grid-cols-3">
    <Link to="/kitchen" className="card group"><div className="flex items-center justify-between"><span className="grid size-10 place-items-center rounded-2xl bg-orange-100 text-orange-700"><AlertTriangle size={19}/></span><ArrowRight size={17} className="text-ink/25 group-hover:text-herb-600"/></div><p className="mt-5 font-display text-2xl">{expiring.length} expiring soon</p><p className="mt-1 text-sm text-ink/55">{expiring.slice(0,2).map(i=>i.name).join(' and ')||'Nothing urgent'}</p></Link>
    <Link to="/kitchen" className="card group"><div className="flex items-center justify-between"><span className="grid size-10 place-items-center rounded-2xl bg-herb-100 text-herb-700"><PackageCheck size={19}/></span><ArrowRight size={17} className="text-ink/25 group-hover:text-herb-600"/></div><p className="mt-5 font-display text-2xl">{s.confirmationQueue.length} items to check</p><p className="mt-1 text-sm text-ink/55">A quick confirmation keeps plans accurate.</p></Link>
    <Link to="/history" className="card group"><div className="flex items-center justify-between"><span className="grid size-10 place-items-center rounded-2xl bg-yellow-100 text-yellow-700"><Sparkles size={19}/></span><ArrowRight size={17} className="text-ink/25 group-hover:text-herb-600"/></div><p className="mt-5 font-display text-2xl">{s.feedback[0]?.rating??'—'}/10 last meal</p><p className="mt-1 text-sm text-ink/55">{s.feedback[0]?.mealTitle??'Cook something to start learning.'}</p></Link>
  </section>
  <section className="mt-10"><div className="mb-5 flex items-end justify-between"><div><p className="eyebrow">Chosen for your kitchen</p><h2 className="mt-1 text-3xl">Smart next meals</h2></div><Link to="/plan" className="text-sm font-semibold text-herb-700">See all</Link></div><div className="grid gap-5 md:grid-cols-3">{s.recommendations.slice(0,3).map(x=><RecipeCard key={x.recipe.id} recipe={x.recipe} reason={x.score.reasons[0]??'A balanced fit for your kitchen and this week.'}/>)}</div></section>
  </>}
