import { ArrowLeft, Bot, Check, Image as ImageIcon, Loader2, RefreshCw, Sparkles, Wand2 } from 'lucide-react';
import { useEffect, useState } from 'react';
import { Link, useLocation, useNavigate } from 'react-router-dom';
import type { GeneratedRecipe } from '@mise/contracts';
import type { Recipe } from '@mise/domain';
import { recipeApi, type PhotoCandidate, type RecipeJob } from '../lib/api';
import { demoMode } from '../lib/supabase';
import { useStore } from '../store';

function demoDraft(base:Recipe,servings:number,notes:string):GeneratedRecipe{const factor=servings/base.servings;return {title:`Weeknight ${base.title}`,description:`${base.description} Adapted for ${notes.toLowerCase()}`,servings,prepMinutes:base.prepMinutes,cookMinutes:base.cookMinutes,difficulty:base.difficulty,estimatedCost:String(Number(base.estimatedCost)*factor),caloriesPerServing:base.caloriesPerServing,proteinGramsPerServing:base.proteinGramsPerServing,ingredients:base.ingredients.map(item=>({...item,quantity:String(Number((Number(item.quantity)*factor).toFixed(4)))})),steps:base.steps,equipment:base.equipment,safetyNotes:base.safetyNote?[base.safetyNote]:[],substitutions:[],tags:base.tags,cuisine:base.cuisine,protein:base.protein,cleanup:base.cleanup,leftoverQuality:base.leftoverQuality,leftoverDays:1,reheating:base.reheating,flavorProfile:[],leftoverGuidance:base.reheating,imageSearchQuery:base.title,confidence:.9,unresolvedIngredientMappings:[]}}
function toRecipe(draft:GeneratedRecipe):Recipe{return {id:crypto.randomUUID(),version:1,title:draft.title,description:draft.description,cuisine:draft.cuisine,protein:draft.protein,servings:draft.servings,prepMinutes:draft.prepMinutes,cookMinutes:draft.cookMinutes,difficulty:draft.difficulty,estimatedCost:draft.estimatedCost,caloriesPerServing:draft.caloriesPerServing,proteinGramsPerServing:draft.proteinGramsPerServing,cleanup:draft.cleanup as Recipe['cleanup'],leftoverQuality:draft.leftoverQuality as Recipe['leftoverQuality'],leftoverDays:draft.leftoverDays,ingredients:draft.ingredients.map(item=>({ingredientId:item.ingredientId,name:item.name,quantity:item.quantity,unit:item.unit,...(item.optional===undefined?{}:{optional:item.optional})})),steps:draft.steps,tags:draft.tags,...(draft.safetyNotes[0]?{safetyNote:draft.safetyNotes.join(' ')}:{}),reheating:draft.reheating,equipment:draft.equipment}}

export function GenerateRecipe(){
  const s=useStore();const nav=useNavigate();const adapt=(useLocation().state as {adapt?:Recipe}|null)?.adapt;
  const [job,setJob]=useState<RecipeJob|null>(null);const [draft,setDraft]=useState<GeneratedRecipe|null>(null);const [selectedPhoto,setSelectedPhoto]=useState<PhotoCandidate|null>(null);
  const [protein,setProtein]=useState(adapt?.protein??'Chicken breast');const [minutes,setMinutes]=useState(adapt?String(adapt.prepMinutes+adapt.cookMinutes):'35');const [servings,setServings]=useState(String(adapt?.servings??2));const [notes,setNotes]=useState(adapt?`Adapt ${adapt.title} for fewer dishes.`:'Make a complete dinner with the protein plus rice, pasta, potatoes, and/or cooked vegetables. Save the second serving for lunch tomorrow.');
  const [loading,setLoading]=useState(false);const [saving,setSaving]=useState(false);const [restoring,setRestoring]=useState(!demoMode);const [error,setError]=useState('');

  const applyJob=(next:RecipeJob|null)=>{setJob(next);if(next?.status==='ready'&&next.recipe_draft){setDraft(next.recipe_draft);setSelectedPhoto(next.photo_candidates[0]??null);setError('')}else if(next?.status==='failed')setError(`Miso could not create this draft (${next.error_code??'unknown error'}). You can discard it and try again.`)};
  useEffect(()=>{if(demoMode)return;let active=true;void recipeApi.latestJob().then(next=>{if(active)applyJob(next)}).catch(e=>{if(active)setError(e instanceof Error?e.message:'Your latest recipe request could not be restored.')}).finally(()=>{if(active)setRestoring(false)});return()=>{active=false}},[]);
  useEffect(()=>{if(!job||!['queued','processing'].includes(job.status)||demoMode)return;let checking=false;const check=()=>{if(checking)return;checking=true;void recipeApi.getJob(job.id).then(next=>applyJob(next)).catch(e=>setError(e instanceof Error?e.message:'Recipe status could not be checked. Retrying automatically…')).finally(()=>{checking=false})};const timer=window.setInterval(check,3000);return()=>window.clearInterval(timer)},[job]);

  const generate=async()=>{setLoading(true);setError('');setDraft(null);setSelectedPhoto(null);try{if(demoMode){await new Promise(resolve=>setTimeout(resolve,650));const base=adapt??s.recipes.find(r=>protein==='Any'||r.protein===protein)??s.recipes[0];if(!base)throw new Error('No demo recipe is available.');setDraft(demoDraft(base,Number(servings),notes));setJob(null)}else{setJob(await recipeApi.createJob({protein,minutes:Number(minutes),servings:Number(servings),notes}))}}catch(e){setError(e instanceof Error?e.message:'The recipe request could not be created.')}finally{setLoading(false)}};
  const save=async()=>{if(!draft)return;setSaving(true);setError('');try{if(demoMode)s.addRecipe(toRecipe(draft));else{if(!job)throw new Error('Recipe job is missing.');await recipeApi.saveJob(job.id,draft,selectedPhoto);await s.refreshRecipes()}nav('/recipes')}catch(e){setError(e instanceof Error?e.message:'The recipe could not be saved.')}finally{setSaving(false)}};
  const discard=async()=>{setError('');try{if(job&&!demoMode)await recipeApi.discardJob(job.id);setDraft(null);setJob(null);setSelectedPhoto(null)}catch(e){setError(e instanceof Error?e.message:'The recipe request could not be discarded.')}};
  const waiting=job&&['queued','processing'].includes(job.status);
  const queuedFor=job?Date.now()-new Date(job.created_at).getTime():0;const workerDelayed=Boolean(waiting&&queuedFor>60000);

  return <><Link to={adapt?`/recipes/${adapt.id}`:'/recipes'} className="flex items-center gap-2 text-sm font-semibold text-herb-700"><ArrowLeft size={16}/>Back</Link><div className="mx-auto mt-7 max-w-6xl"><div className="text-center"><p className="eyebrow"><Sparkles className="mr-1 inline" size={13}/>{adapt?'Create a new version':'Miso recipe studio'}</p><h1 className="mt-3 text-4xl sm:text-5xl">{adapt?'Adapt it to fit tonight.':'A fresh idea, grounded in your kitchen.'}</h1><p className="mx-auto mt-3 max-w-2xl text-sm leading-6 text-ink/55">Miso creates the draft on your HP laptop. Shua validates every field and searches Unsplash using the exact recipe title before anything is saved.</p></div>
    {error&&<div role="alert" className="mx-auto mt-6 max-w-3xl rounded-2xl bg-red-50 p-4 text-sm text-red-700">{error}</div>}
    <div className="mt-9 grid gap-6 lg:grid-cols-[.7fr_1.3fr]"><form onSubmit={e=>{e.preventDefault();void generate()}} className="card h-fit"><h2 className="text-2xl">Your guardrails</h2><label className="mt-5 block text-sm font-semibold">Protein<select className="field mt-2" value={protein} onChange={e=>setProtein(e.target.value)}><option>Chicken breast</option><option>Salmon</option><option>White fish</option><option>Ground beef</option><option>Steak</option><option>Eggs</option><option>Shrimp</option><option>Tofu</option><option>Any</option></select></label><div className="mt-5 grid grid-cols-2 gap-3"><label className="text-sm font-semibold">Max minutes<input required min="10" max="720" type="number" className="field mt-2" value={minutes} onChange={e=>setMinutes(e.target.value)}/></label><label className="text-sm font-semibold">Servings<input required min="1" max="24" type="number" className="field mt-2" value={servings} onChange={e=>setServings(e.target.value)}/></label></div><label className="mt-5 block text-sm font-semibold">Priorities and exclusions<textarea className="field mt-2 min-h-32" value={notes} onChange={e=>setNotes(e.target.value)}/></label><button disabled={restoring||loading||Boolean(waiting)} className="btn-primary mt-5 w-full">{restoring||loading||waiting?<Loader2 className="animate-spin" size={17}/>:<Wand2 size={17}/>} {restoring?'Checking for an existing request…':waiting?'Waiting for Miso…':'Generate draft'}</button><p className="mt-3 text-center text-xs text-ink/40">Your request and completed draft stay attached to your account if you leave.</p></form>
      <section className="card min-h-[520px]">{!draft&&!waiting&&!loading&&!restoring?<div className="grid min-h-[470px] place-items-center text-center"><div><span className="mx-auto grid size-16 place-items-center rounded-3xl bg-herb-50 text-herb-600"><Bot size={30}/></span><h2 className="mt-5 text-3xl">{job?.status==='failed'?'That request did not finish':'Your draft will appear here'}</h2><p className="mt-2 text-sm text-ink/50">{job?.status==='failed'?'Discard it or adjust the guardrails and try again.':'Ingredients, units, steps, safety details, and photos remain reviewable.'}</p>{job?.status==='failed'&&<button type="button" onClick={()=>void discard()} className="btn-secondary mt-5">Discard request</button>}</div></div>:!draft?<div className="grid min-h-[470px] place-items-center"><div className="max-w-sm text-center">{workerDelayed?<Bot className="mx-auto text-orange-600" size={34}/>:<Loader2 className="mx-auto animate-spin text-herb-600" size={34}/>}<p className="mt-4 font-semibold">{restoring?'Restoring your latest request…':workerDelayed?'Miso’s worker appears to be offline. Your request is safe.':job?.status==='processing'?'Miso is preparing the recipe…':'Waiting for the Miso worker…'}</p><p className="mt-2 text-sm text-ink/50">{workerDelayed?'The draft will appear after the worker reconnects. You can leave and return without losing it.':'You may leave this page. Shua will restore the request and its result when you return.'}</p>{workerDelayed&&<button type="button" onClick={()=>void discard()} className="btn-secondary mt-5">Discard request</button>}</div></div>:<div><div className="flex items-start justify-between gap-4"><div><p className="eyebrow">Review draft · {Math.round(draft.confidence*100)}% confidence</p><input aria-label="Recipe title" className="field mt-2 text-2xl font-semibold" value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})}/><textarea aria-label="Recipe description" className="field mt-3 min-h-20 text-sm" value={draft.description} onChange={e=>setDraft({...draft,description:e.target.value})}/></div><button onClick={()=>void generate()} className="btn-secondary" aria-label="Regenerate"><RefreshCw size={16}/></button></div><div className="mt-5 flex flex-wrap gap-2"><span className="pill">{draft.servings} servings</span><span className="pill">{draft.prepMinutes+draft.cookMinutes} min</span><span className="pill">${draft.estimatedCost}</span></div>
        <div className="mt-3 flex flex-wrap gap-2"><span className="pill">~{draft.caloriesPerServing} calories / serving</span><span className="pill">~{draft.proteinGramsPerServing}g protein / serving</span></div>{job&&job.photo_candidates.length>0&&<><h3 className="mt-7 flex items-center gap-2 text-xl"><ImageIcon size={18}/>Representative photo</h3><div className="mt-3 grid gap-3 sm:grid-cols-3">{job.photo_candidates.map(photo=><button type="button" key={photo.id} onClick={()=>setSelectedPhoto(photo)} className={`overflow-hidden rounded-2xl border-2 text-left ${selectedPhoto?.id===photo.id?'border-herb-600':'border-transparent'}`}><img src={photo.thumbUrl} alt={photo.altText} className="h-32 w-full object-cover"/></button>)}</div></>}
        <h3 className="mt-7 text-xl">Ingredients</h3><div className="mt-3 space-y-2">{draft.ingredients.map((item,index)=><div key={index} className="flex gap-2"><input aria-label={`Quantity ${item.name}`} value={item.quantity} onChange={e=>setDraft({...draft,ingredients:draft.ingredients.map((x,i)=>i===index?{...x,quantity:e.target.value}:x)})} className="w-20 rounded-xl border px-3 py-2"/><span className="w-16 py-2 text-sm">{item.unit}</span><input aria-label={`Ingredient ${index+1}`} value={item.name} onChange={e=>setDraft({...draft,ingredients:draft.ingredients.map((x,i)=>i===index?{...x,name:e.target.value}:x)})} className="min-w-0 flex-1 rounded-xl border px-3 py-2"/></div>)}</div>{draft.unresolvedIngredientMappings.length>0&&<p className="mt-3 rounded-xl bg-orange-50 p-3 text-xs text-orange-900">Unresolved mappings: {draft.unresolvedIngredientMappings.join(', ')}. These remain named ingredients but will not reserve inventory until mapped.</p>}
        <h3 className="mt-7 text-xl">Method</h3><ol className="mt-3 space-y-3">{draft.steps.map((step,index)=><li key={index} className="flex gap-3 text-sm"><span className="font-semibold text-herb-700">{index+1}.</span><textarea aria-label={`Step ${index+1}`} className="field min-h-16 flex-1" value={step} onChange={e=>setDraft({...draft,steps:draft.steps.map((x,i)=>i===index?e.target.value:x)})}/></li>)}</ol>{draft.safetyNotes.length>0&&<div className="mt-5 rounded-2xl bg-orange-50 p-4 text-sm text-orange-900"><strong>Safety review:</strong> {draft.safetyNotes.join(' ')}</div>}<div className="mt-7 flex gap-2"><button disabled={saving} onClick={()=>void save()} className="btn-primary">{saving?<Loader2 className="animate-spin" size={17}/>:<Check size={17}/>}Accept & save</button><button onClick={()=>void discard()} className="btn-secondary">Discard</button></div></div>}</section></div></div></>;
}
