import { CheckCircle2, Minus, PackageCheck, Pencil, Plus, Search, Trash2 } from 'lucide-react';
import { useState } from 'react';
import { projected } from '@mise/domain';
import { PageTitle } from '../components/UI';
import { useStore } from '../store';

export function Kitchen(){const s=useStore();const [query,setQuery]=useState('');const current=s.confirmationQueue[0];const shown=s.inventory.filter(i=>i.name.toLowerCase().includes(query.toLowerCase()));return <><PageTitle eyebrow="Inventory & confidence" title="Know what you really have." description="Shua tracks confirmed amounts separately from planned reservations, and only asks about items that matter."/>
  {current&&<section className="mb-8 overflow-hidden rounded-3xl bg-herb-700 text-white shadow-soft"><div className="grid lg:grid-cols-[.7fr_1.3fr]"><div className="grid min-h-52 place-items-center bg-white/10 text-7xl" aria-hidden>🥬</div><div className="p-7"><p className="text-xs font-semibold uppercase tracking-[.18em] text-white/60">Quick weekend check · {s.confirmationQueue.length} remaining</p><h2 className="mt-3 text-3xl">Do you still have about {current.quantity} {current.unit} of {current.name.toLowerCase()}?</h2><p className="mt-2 text-sm text-white/65">Last confirmed {new Date(current.lastConfirmedAt).toLocaleDateString()}{current.expiresOn?` · estimated good through ${new Date(current.expiresOn+'T12:00').toLocaleDateString()}`:''}</p><div className="mt-6 flex flex-wrap gap-2"><button onClick={()=>s.confirmInventory(current.id,'correct')} className="btn bg-white text-herb-700"><CheckCircle2 size={16}/>That’s right</button><button onClick={()=>s.confirmInventory(current.id,'none')} className="btn bg-white/10 text-white"><Trash2 size={16}/>None left</button><button onClick={()=>s.confirmInventory(current.id,'less')} className="btn bg-white/10 text-white"><Minus size={16}/>Less</button><button onClick={()=>s.confirmInventory(current.id,'more')} className="btn bg-white/10 text-white"><Plus size={16}/>More</button></div></div></div></section>}
  {!current&&<div className="mb-8 flex items-center gap-3 rounded-3xl bg-herb-100 p-5 text-herb-700"><PackageCheck/>Inventory review complete. Recommendations now use high-confidence quantities.</div>}
  <div className="mb-4 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><h2 className="text-3xl">Your kitchen</h2><label className="relative"><span className="sr-only">Search inventory</span><Search className="absolute left-4 top-3.5 text-ink/35" size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search ingredients" className="field pl-11"/></label></div>
  <div className="overflow-hidden rounded-3xl border border-black/5 bg-white shadow-soft"><div className="hidden grid-cols-[1.5fr_.7fr_.7fr_.8fr_40px] gap-4 border-b bg-black/[.02] px-5 py-3 text-xs font-semibold uppercase tracking-wider text-ink/40 sm:grid"><span>Ingredient</span><span>Confirmed</span><span>Reserved</span><span>Projected</span><span/></div>{shown.map(i=><InventoryRow key={i.id} item={i} onSave={q=>s.adjustInventory(i.id,q)}/>)}</div></>}
function InventoryRow({item,onSave}:{item:any;onSave:(q:string)=>void}){const [editing,setEditing]=useState(false);const [q,setQ]=useState(item.quantity);return <div className="grid gap-3 border-b border-black/5 px-5 py-4 last:border-0 sm:grid-cols-[1.5fr_.7fr_.7fr_.8fr_40px] sm:items-center"><div><p className="font-semibold">{item.name}</p><p className="text-xs text-ink/45">{item.location} · {Math.round(item.confidence*100)}% confidence</p></div><div><span className="text-xs text-ink/40 sm:hidden">Confirmed: </span>{editing?<input aria-label={`Quantity of ${item.name}`} className="w-20 rounded-lg border p-1" value={q} onChange={e=>setQ(e.target.value)} onBlur={()=>{onSave(q);setEditing(false)}} autoFocus/>:<span>{item.quantity} {item.unit}</span>}</div><div><span className="text-xs text-ink/40 sm:hidden">Reserved: </span>{item.reserved} {item.unit}</div><div className="font-semibold text-herb-700"><span className="text-xs font-normal text-ink/40 sm:hidden">Projected: </span>{projected(item)} {item.unit}</div><button onClick={()=>setEditing(true)} aria-label={`Edit ${item.name}`} className="rounded-full p-2 text-ink/40 hover:bg-herb-50 hover:text-herb-700"><Pencil size={16}/></button></div>}
