import { ArrowLeft, Loader2, Plus, Save, Trash2 } from 'lucide-react';
import { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import type { GeneratedRecipe } from '@mise/contracts';
import type { Recipe, Unit } from '@mise/domain';
import { recipeApi } from '../lib/api';
import { demoMode } from '../lib/supabase';
import { useStore } from '../store';

const units:Unit[]=['count','serving','tsp','tbsp','fl_oz','cup','oz','lb','g','kg','ml','l','package','bag','can','bottle','bunch'];
type Ingredient=GeneratedRecipe['ingredients'][number];
const blankIngredient=():Ingredient=>({ingredientId:`manual:${crypto.randomUUID()}`,name:'',quantity:'1',unit:'count',optional:false});

function toRecipe(draft:GeneratedRecipe):Recipe{return {id:crypto.randomUUID(),version:1,title:draft.title,description:draft.description,cuisine:draft.cuisine,protein:draft.protein,servings:draft.servings,prepMinutes:draft.prepMinutes,cookMinutes:draft.cookMinutes,difficulty:draft.difficulty,estimatedCost:draft.estimatedCost,cleanup:draft.cleanup as Recipe['cleanup'],leftoverQuality:draft.leftoverQuality as Recipe['leftoverQuality'],leftoverDays:draft.leftoverDays,ingredients:draft.ingredients.map(item=>({ingredientId:item.ingredientId,name:item.name,quantity:item.quantity,unit:item.unit,...(item.optional===undefined?{}:{optional:item.optional})})),steps:draft.steps,tags:draft.tags,...(draft.safetyNotes[0]?{safetyNote:draft.safetyNotes.join(' ')}:{}),reheating:draft.reheating,equipment:draft.equipment};}

export function ManualRecipe(){
  const store=useStore();const nav=useNavigate();
  const [saving,setSaving]=useState(false);const [error,setError]=useState('');
  const [draft,setDraft]=useState<GeneratedRecipe>({title:'',description:'',servings:4,prepMinutes:10,cookMinutes:20,difficulty:'Easy',estimatedCost:'0',ingredients:[blankIngredient()],steps:[''],equipment:[],safetyNotes:[],substitutions:[],tags:[],cuisine:'Homestyle',protein:'Other',cleanup:2,leftoverQuality:3,leftoverDays:3,reheating:'Reheat until steaming hot.',flavorProfile:[],leftoverGuidance:'',imageSearchQuery:'manual recipe',confidence:1,unresolvedIngredientMappings:[]});
  const setIngredient=(index:number,changes:Partial<Ingredient>)=>setDraft({...draft,ingredients:draft.ingredients.map((item,i)=>i===index?{...item,...changes}:item)});
  const save=async()=>{setError('');if(draft.title.trim().length<3||draft.ingredients.some(i=>!i.name.trim()||!/^[0-9]+(\.[0-9]{1,4})?$/.test(i.quantity)||Number(i.quantity)<=0)||draft.steps.some(s=>s.trim().length<3)){setError('Use a title of at least 3 characters and complete every ingredient quantity, name, and method step.');return}setSaving(true);const recipe={...draft,title:draft.title.trim(),description:draft.description.trim(),ingredients:draft.ingredients.map(i=>({...i,name:i.name.trim()})),steps:draft.steps.map(s=>s.trim()),imageSearchQuery:draft.title.trim()};try{if(demoMode)store.addRecipe(toRecipe(recipe));else{await recipeApi.createManual(recipe);await store.refreshRecipes()}nav('/recipes')}catch(e){setError(e instanceof Error?e.message:'The recipe could not be saved.')}finally{setSaving(false)}};
  return <><Link to="/recipes" className="flex items-center gap-2 text-sm font-semibold text-herb-700"><ArrowLeft size={16}/>Back to recipes</Link><div className="mx-auto mt-7 max-w-5xl"><p className="eyebrow">Manual recipe</p><h1 className="mt-2 text-4xl sm:text-5xl">Add it your way.</h1><p className="mt-3 text-sm text-ink/55">Enter the recipe once; it will use the same ingredient and method layout as every other saved recipe.</p>{error&&<p role="alert" className="mt-5 rounded-2xl bg-red-50 p-4 text-sm text-red-700">{error}</p>}
    <div className="mt-7 grid gap-6 lg:grid-cols-[.75fr_1.25fr]"><section className="card h-fit"><h2 className="text-2xl">Recipe details</h2><label className="mt-5 block text-sm font-semibold">Title<input required className="field mt-2" value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})}/></label><label className="mt-4 block text-sm font-semibold">Description<textarea className="field mt-2 min-h-24" value={draft.description} onChange={e=>setDraft({...draft,description:e.target.value})}/></label><div className="mt-4 grid grid-cols-2 gap-3"><label className="text-sm font-semibold">Cuisine<input className="field mt-2" value={draft.cuisine} onChange={e=>setDraft({...draft,cuisine:e.target.value})}/></label><label className="text-sm font-semibold">Protein<input className="field mt-2" value={draft.protein} onChange={e=>setDraft({...draft,protein:e.target.value})}/></label><label className="text-sm font-semibold">Servings<input type="number" min="1" max="24" className="field mt-2" value={draft.servings} onChange={e=>setDraft({...draft,servings:Number(e.target.value)})}/></label><label className="text-sm font-semibold">Estimated cost<input type="number" min="0" step="0.01" className="field mt-2" value={draft.estimatedCost} onChange={e=>setDraft({...draft,estimatedCost:e.target.value})}/></label><label className="text-sm font-semibold">Prep minutes<input type="number" min="0" className="field mt-2" value={draft.prepMinutes} onChange={e=>setDraft({...draft,prepMinutes:Number(e.target.value)})}/></label><label className="text-sm font-semibold">Cook minutes<input type="number" min="1" className="field mt-2" value={draft.cookMinutes} onChange={e=>setDraft({...draft,cookMinutes:Number(e.target.value)})}/></label></div><label className="mt-4 block text-sm font-semibold">Difficulty<select className="field mt-2" value={draft.difficulty} onChange={e=>setDraft({...draft,difficulty:e.target.value as GeneratedRecipe['difficulty']})}><option>Easy</option><option>Medium</option><option>Ambitious</option></select></label><label className="mt-4 block text-sm font-semibold">Tags (comma separated)<input className="field mt-2" value={draft.tags.join(', ')} onChange={e=>setDraft({...draft,tags:e.target.value.split(',').map(x=>x.trim()).filter(Boolean)})}/></label></section>
      <div className="space-y-6"><section className="card"><div className="flex items-center justify-between"><h2 className="text-2xl">Ingredients</h2><button type="button" className="btn-secondary" onClick={()=>setDraft({...draft,ingredients:[...draft.ingredients,blankIngredient()]})}><Plus size={16}/>Add ingredient</button></div><div className="mt-5 space-y-3">{draft.ingredients.map((item,index)=><div key={item.ingredientId} className="flex flex-wrap gap-2"><input aria-label={`Quantity ${index+1}`} required className="field w-20 px-3" value={item.quantity} onChange={e=>setIngredient(index,{quantity:e.target.value})}/><select aria-label={`Unit ${index+1}`} className="field w-28 px-2" value={item.unit} onChange={e=>setIngredient(index,{unit:e.target.value as Unit})}>{units.map(unit=><option key={unit}>{unit}</option>)}</select><input aria-label={`Ingredient ${index+1}`} required className="field min-w-48 flex-1 px-3" placeholder="Ingredient name" value={item.name} onChange={e=>setIngredient(index,{name:e.target.value})}/><button type="button" disabled={draft.ingredients.length===1} aria-label={`Remove ingredient ${index+1}`} className="rounded-xl p-2 text-red-700 disabled:opacity-25" onClick={()=>setDraft({...draft,ingredients:draft.ingredients.filter((_,i)=>i!==index)})}><Trash2 size={17}/></button></div>)}</div></section>
        <section className="card"><div className="flex items-center justify-between"><h2 className="text-2xl">Method</h2><button type="button" className="btn-secondary" onClick={()=>setDraft({...draft,steps:[...draft.steps,'']})}><Plus size={16}/>Add step</button></div><ol className="mt-5 space-y-4">{draft.steps.map((step,index)=><li key={index} className="flex gap-3"><span className="grid size-9 shrink-0 place-items-center rounded-full bg-herb-600 font-semibold text-white">{index+1}</span><textarea required aria-label={`Step ${index+1}`} className="field min-h-20 flex-1" placeholder="Describe this step" value={step} onChange={e=>setDraft({...draft,steps:draft.steps.map((x,i)=>i===index?e.target.value:x)})}/><button type="button" disabled={draft.steps.length===1} aria-label={`Remove step ${index+1}`} className="self-start rounded-xl p-2 text-red-700 disabled:opacity-25" onClick={()=>setDraft({...draft,steps:draft.steps.filter((_,i)=>i!==index)})}><Trash2 size={17}/></button></li>)}</ol></section><button disabled={saving} onClick={()=>void save()} className="btn-primary w-full">{saving?<Loader2 className="animate-spin" size={17}/>:<Save size={17}/>}Save recipe</button></div></div></div></>;
}
