import { Check, ChevronLeft, ChevronRight, Plus, RotateCcw, Sparkles } from 'lucide-react';
import { useMemo, useState } from 'react';
import { PageTitle, RecipeCard } from '../components/UI';
import { useStore } from '../store';

const monday=()=>{const d=new Date();const day=d.getDay();d.setDate(d.getDate()+((8-day)%7||7));d.setHours(12,0,0,0);return d};
const dates=Array.from({length:7},(_,i)=>{const d=monday();d.setDate(d.getDate()+i);return d});
export function PlanWeek(){const s=useStore();const firstOpen=dates.find(d=>!s.meals.some(m=>m.date===d.toISOString().slice(0,10)&&m.status==='planned'))??dates[0]!;const [selected,setSelected]=useState(firstOpen.toISOString().slice(0,10));const meal=s.meals.find(m=>m.date===selected&&m.status==='planned');const picks=useMemo(()=>s.recommendations.filter(r=>r.recipe.id!==meal?.recipeId).slice(0,6),[s.recommendations,meal]);return <><PageTitle eyebrow="Sequential week planner" title="Plan one good day at a time." description="Each choice reserves its ingredients and reshapes the recommendations, projected inventory, budget, and grocery list for the days that follow." action={<div className="flex gap-2"><button className="btn-secondary" aria-label="Previous week"><ChevronLeft size={17}/></button><button className="btn-secondary" aria-label="Next week"><ChevronRight size={17}/></button></div>}/>
  <div className="grid gap-3 sm:grid-cols-7">{dates.map(d=>{const key=d.toISOString().slice(0,10),planned=s.meals.find(m=>m.date===key&&m.status==='planned');return <button key={key} onClick={()=>setSelected(key)} className={`min-h-28 rounded-3xl border p-3 text-left transition ${selected===key?'border-herb-600 bg-herb-600 text-white shadow-soft':'border-black/5 bg-white hover:border-herb-500'}`}><span className={`text-xs font-semibold uppercase ${selected===key?'text-white/65':'text-ink/40'}`}>{d.toLocaleDateString(undefined,{weekday:'short'})}</span><span className="mt-1 block font-display text-2xl">{d.getDate()}</span><span className={`mt-3 line-clamp-2 text-xs ${selected===key?'text-white/80':'text-ink/55'}`}>{planned?<><Check className="mr-1 inline" size={12}/>{planned.title}</>:'Open dinner'}</span></button>})}</div>
  {meal&&<div className="mt-5 flex flex-col gap-4 rounded-3xl bg-herb-50 p-5 sm:flex-row sm:items-center sm:justify-between"><div><p className="eyebrow">Reserved for {new Date(selected+'T12:00').toLocaleDateString(undefined,{weekday:'long'})}</p><p className="mt-1 font-display text-2xl">{meal.title}</p></div><button className="btn-secondary" onClick={()=>s.removeMeal(meal.id)}><RotateCcw size={16}/>Clear and choose again</button></div>}
  <div className="mt-9 flex items-end justify-between"><div><p className="eyebrow"><Sparkles className="mr-1 inline" size={13}/>Recalculated now</p><h2 className="mt-1 text-3xl">Best for {new Date(selected+'T12:00').toLocaleDateString(undefined,{weekday:'long'})}</h2></div><div className="hidden text-right text-xs text-ink/45 sm:block">{s.inventory.reduce((n,i)=>n+(Number(i.reserved)>0?1:0),0)} ingredients currently reserved<br/>{s.grocery.length} grocery items projected</div></div>
  <div className="mt-5 grid gap-5 md:grid-cols-2 xl:grid-cols-3">{picks.map(x=><div key={x.recipe.id} className="relative"><RecipeCard recipe={x.recipe} reason={x.score.reasons[0]??`Strong ${Math.round(x.score.totalScore*100)}% fit for this week`}/><button onClick={()=>s.planMeal(selected,x.recipe.id)} className="btn-primary absolute bottom-5 right-5 z-10"><Plus size={16}/>Plan</button></div>)}</div></>}
