import { Bot, FilePlus2, LibraryBig, Loader2, Plus, Search } from 'lucide-react';
import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import type { GeneratedRecipe } from '@mise/contracts';
import type { Recipe } from '@mise/domain';
import { EmptyState, PageTitle, RecipeCard } from '../components/UI';
import { recipes as starterRecipes } from '../data';
import { recipeApi, type RecipeJob } from '../lib/api';
import { demoMode } from '../lib/supabase';
import { useStore } from '../store';

const retiredStarterTitles=['Maple mustard salmon','Pesto chicken with burst tomatoes','Mustard herb pork tenderloin','Pork and vegetable fried rice','Greek turkey meatball bowls','White bean turkey chili','Creamy mushroom risotto','Cumin black bean soup','Creamy vegetable korma','Spinach ricotta baked ziti','Italian stuffed peppers','Crispy pesto gnocchi and vegetables','Roasted sweet potato black bean tacos','Roasted tomato basil soup','Hearty pantry minestrone','Creamy tomato tortellini soup','Sesame tofu noodle bowls'];

export function Recipes(){
  const s=useStore();const [q,setQ]=useState('');const [protein,setProtein]=useState('All');const [deleting,setDeleting]=useState('');const [importing,setImporting]=useState(false);const [importError,setImportError]=useState('');const [importMessage,setImportMessage]=useState('');const [misoJob,setMisoJob]=useState<RecipeJob|null>(null);
  useEffect(()=>{if(demoMode)return;let active=true;void recipeApi.latestJob().then(job=>{if(active)setMisoJob(job)}).catch(()=>undefined);return()=>{active=false}},[]);
  const filtered=s.recipes.filter(r=>(r.title+' '+r.cuisine+' '+r.tags.join(' ')).toLowerCase().includes(q.toLowerCase())&&(protein==='All'||r.protein===protein));
  const proteins=['All',...new Set(s.recipes.map(r=>r.protein))];
  const remove=async(id:string,title:string)=>{if(!confirm(`Delete “${title}”? It will be removed from your recipe collection.`))return;setDeleting(id);try{await s.deleteRecipe(id)}finally{setDeleting('')}};
  const asGenerated=(recipe:Recipe):GeneratedRecipe=>({title:recipe.title,description:recipe.description,servings:recipe.servings,prepMinutes:recipe.prepMinutes,cookMinutes:recipe.cookMinutes,difficulty:recipe.difficulty,estimatedCost:recipe.estimatedCost,caloriesPerServing:recipe.caloriesPerServing,proteinGramsPerServing:recipe.proteinGramsPerServing,ingredients:recipe.ingredients,steps:recipe.steps,equipment:recipe.equipment,safetyNotes:recipe.safetyNote?[recipe.safetyNote]:[],substitutions:[],tags:recipe.tags,cuisine:recipe.cuisine,protein:recipe.protein,cleanup:recipe.cleanup,leftoverQuality:recipe.leftoverQuality,leftoverDays:recipe.leftoverDays,reheating:recipe.reheating,flavorProfile:[],leftoverGuidance:recipe.reheating,imageSearchQuery:recipe.title,confidence:1,unresolvedIngredientMappings:[]});
  const importStarter=async()=>{setImporting(true);setImportError('');setImportMessage('');try{const result=await recipeApi.importMany(starterRecipes.map(asGenerated),retiredStarterTitles);await s.refreshRecipes();const summary=result.imported||result.retired||result.imagesAdded?`${result.imported} new recipes added, ${result.imagesAdded} Unsplash images attached, ${result.retired} outdated recipes retired, and ${result.skipped} already up to date.`:'Your recipe collection is already up to date.';setImportMessage(result.imagesMissing?`${summary} ${result.imagesMissing} recipes were not imported because no suitable image was available; sync again to retry.`:summary)}catch(error){setImportError(error instanceof Error?error.message:'The starter collection could not be imported.')}finally{setImporting(false)}};
  const activeJob=misoJob&&['queued','processing','ready'].includes(misoJob.status)?misoJob:null;
  return <><PageTitle eyebrow={`${s.recipes.length} saved recipes`} title="Recipes worth returning to." description="Every recipe keeps its history, practical costs, inventory fit, leftover guidance, and adaptations." action={<div className="flex flex-wrap gap-2">{!demoMode&&<button type="button" onClick={()=>void importStarter()} disabled={importing} className="btn-secondary">{importing?<Loader2 className="animate-spin" size={17}/>:<LibraryBig size={17}/>}Sync starter collection</button>}<Link to="/recipes/new" className="btn-secondary"><FilePlus2 size={17}/>Add manually</Link><Link to="/recipes/generate" className="btn-primary"><Plus size={17}/>Ask Miso for a recipe</Link></div>}/>{activeJob&&<Link to="/recipes/generate" className="mb-6 flex items-center gap-4 rounded-2xl bg-herb-50 p-4 text-herb-800"><span className="grid size-10 shrink-0 place-items-center rounded-full bg-white"><Bot size={19}/></span><span className="min-w-0 flex-1"><strong className="block">{activeJob.status==='ready'?'Your Miso draft is ready to review':'Miso is still working on your recipe'}</strong><span className="text-xs text-herb-700/70">{activeJob.status==='ready'?activeJob.recipe_draft?.title:'You can keep using Shua. This request will be restored automatically.'}</span></span><span className="text-sm font-semibold">Open</span></Link>}{(s.recipesError||importError)&&<p role="alert" className="mb-5 rounded-2xl bg-red-50 p-4 text-sm text-red-700">{s.recipesError||importError}</p>}{importMessage&&<p role="status" className="mb-5 rounded-2xl bg-herb-50 p-4 text-sm text-herb-800">{importMessage}</p>}{s.recipesLoading?<div className="grid min-h-72 place-items-center"><Loader2 className="animate-spin text-herb-600"/></div>:<><div className="mb-7 flex flex-col gap-3 sm:flex-row"><label className="relative flex-1"><span className="sr-only">Search recipes</span><Search size={18} className="absolute left-4 top-3.5 text-ink/35"/><input className="field pl-11" value={q} onChange={e=>setQ(e.target.value)} placeholder="Search recipes, cuisines, or tags"/></label><select className="field sm:w-52" aria-label="Filter by protein" value={protein} onChange={e=>setProtein(e.target.value)}>{proteins.map(p=><option key={p}>{p}</option>)}</select></div>{filtered.length?<div className="grid gap-5 sm:grid-cols-2 xl:grid-cols-3">{filtered.map(r=><RecipeCard key={r.id} recipe={r} deleting={deleting===r.id} onDelete={()=>void remove(r.id,r.title)}/>)}</div>:<EmptyState title="No saved recipes yet" body="Add one manually or ask Miso to create a recipe, then save it here." action={<Link to="/recipes/new" className="btn-primary"><FilePlus2 size={17}/>Add a recipe</Link>}/>}</>}</>;
}
